import os, sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))  # tools/question-banks
from bankgen import build

LEARN, FOWLER, RG, WIKI, MSIO, AWS = "Microsoft Learn", "Martin Fowler", "Refactoring.Guru", "Wikipedia", "microservices.io", "Amazon Builders' Library"

M = {
 "arch-principles": ("article", "Architectural principles", "https://learn.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/architectural-principles", LEARN, "SOLID, separation of concerns and other principles for maintainable apps.", False),
 "lsp": ("article", "Liskov substitution principle", "https://en.wikipedia.org/wiki/Liskov_substitution_principle", WIKI, "Subtypes must honour the contract of their base type.", False),
 "composition": ("article", "Composition over inheritance", "https://en.wikipedia.org/wiki/Composition_over_inheritance", WIKI, "Why composing behaviour usually beats deep class hierarchies.", False),
 "yagni": ("article", "Yagni", "https://martinfowler.com/bliki/Yagni.html", FOWLER, "Don't build capabilities for presumptive future needs.", False),
 "rule-of-three": ("article", "Rule of three (computer programming)", "https://en.wikipedia.org/wiki/Rule_of_three_(computer_programming)", WIKI, "Wait for the third duplication before abstracting.", False),
 "fowler-bliki": ("link", "Martin Fowler's bliki", "https://martinfowler.com/bliki/", FOWLER, "Short, careful definitions of design and architecture terms.", False),
 "di-dotnet": ("article", "Dependency injection in .NET", "https://learn.microsoft.com/en-us/dotnet/core/extensions/dependency-injection", LEARN, "Constructor injection, lifetimes and the built-in container.", False),
 "rg-catalogue": ("link", "Refactoring.Guru design patterns catalogue", "https://refactoring.guru/design-patterns", RG, "A free, illustrated catalogue of the classic patterns.", False),
 "rg-strategy": ("article", "Strategy pattern", "https://refactoring.guru/design-patterns/strategy", RG, "Swappable algorithms behind a common interface.", False),
 "rg-factory-method": ("article", "Factory Method pattern", "https://refactoring.guru/design-patterns/factory-method", RG, "Let subclasses decide which object to create.", False),
 "rg-abstract-factory": ("article", "Abstract Factory pattern", "https://refactoring.guru/design-patterns/abstract-factory", RG, "Create families of related objects without naming concrete classes.", False),
 "rg-decorator": ("article", "Decorator pattern", "https://refactoring.guru/design-patterns/decorator", RG, "Add behaviour by wrapping an object behind the same interface.", False),
 "rg-adapter": ("article", "Adapter pattern", "https://refactoring.guru/design-patterns/adapter", RG, "Convert one interface into another that clients expect.", False),
 "rg-facade": ("article", "Facade pattern", "https://refactoring.guru/design-patterns/facade", RG, "A simple interface over a complex subsystem.", False),
 "rg-observer": ("article", "Observer pattern", "https://refactoring.guru/design-patterns/observer", RG, "Subscribers notified of changes in a publisher.", False),
 "rg-singleton": ("article", "Singleton pattern", "https://refactoring.guru/design-patterns/singleton", RG, "One instance with global access, and why that is risky.", False),
 "persistence-layer": ("article", "Design the infrastructure persistence layer", "https://learn.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/infrastructure-persistence-layer-design", LEARN, "Repositories and unit of work with EF Core.", False),
 "bounded-context": ("article", "Bounded context", "https://martinfowler.com/bliki/BoundedContext.html", FOWLER, "Dividing a large model into contexts with explicit boundaries.", False),
 "domain-analysis": ("article", "Using domain analysis to model microservices", "https://learn.microsoft.com/en-us/azure/architecture/microservices/model/domain-analysis", LEARN, "Finding bounded contexts from the business domain.", False),
 "tactical-ddd": ("article", "Using tactical DDD to design microservices", "https://learn.microsoft.com/en-us/azure/architecture/microservices/model/tactical-ddd", LEARN, "Entities, value objects, aggregates and domain services.", False),
 "ddd-aggregate": ("article", "DDD Aggregate", "https://martinfowler.com/bliki/DDD_Aggregate.html", FOWLER, "Clusters of objects treated as one consistency unit.", False),
 "domain-model-layer": ("article", "Design a microservice domain model", "https://learn.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/microservice-domain-model", LEARN, "Building the domain model layer with aggregates in .NET.", False),
 "domain-events": ("article", "Domain events: design and implementation", "https://learn.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/domain-events-design-implementation", LEARN, "Domain events versus integration events.", False),
 "anemic": ("article", "Anemic domain model", "https://martinfowler.com/bliki/AnemicDomainModel.html", FOWLER, "Why data-only entities with logic elsewhere is an anti-pattern.", False),
 "hexagonal": ("article", "Hexagonal architecture", "https://alistair.cockburn.us/hexagonal-architecture/", "Alistair Cockburn", "Ports and adapters, from the pattern's author.", False),
 "clean-arch": ("article", "The Clean Architecture", "https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html", "Robert C. Martin", "The dependency rule and concentric layers.", False),
 "vertical-slice": ("article", "Vertical slice architecture", "https://www.jimmybogard.com/vertical-slice-architecture/", "Jimmy Bogard", "Organizing code by feature instead of by layer.", False),
 "acl": ("article", "Anti-corruption Layer pattern", "https://learn.microsoft.com/en-us/azure/architecture/patterns/anti-corruption-layer", LEARN, "Translating between your model and a foreign or legacy one.", False),
 "cqrs": ("article", "Apply simplified CQRS and DDD patterns in a microservice", "https://learn.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/apply-simplified-microservice-cqrs-ddd-patterns", LEARN, "Separating read and write models without full event sourcing.", False),
 "cap": ("article", "CAP theorem", "https://en.wikipedia.org/wiki/CAP_theorem", WIKI, "Consistency versus availability under network partitions.", False),
 "pacelc": ("article", "PACELC theorem", "https://en.wikipedia.org/wiki/PACELC_theorem", WIKI, "The latency-consistency trade-off when there is no partition.", False),
 "fallacies": ("article", "Fallacies of distributed computing", "https://en.wikipedia.org/wiki/Fallacies_of_distributed_computing", WIKI, "Eight false assumptions about networks.", False),
 "jepsen": ("article", "Jepsen: consistency models", "https://jepsen.io/consistency", "Jepsen", "A map of consistency models and what each guarantees.", False),
 "2pc": ("article", "Two-phase commit protocol", "https://en.wikipedia.org/wiki/Two-phase_commit_protocol", WIKI, "How 2PC works and why it blocks.", False),
 "saga-azure": ("article", "Saga distributed transactions pattern", "https://learn.microsoft.com/en-us/azure/architecture/patterns/saga", LEARN, "Local transactions with compensations, orchestrated or choreographed.", False),
 "msio-patterns": ("link", "microservices.io pattern language", "https://microservices.io/patterns/index.html", MSIO, "Data consistency, decomposition and messaging patterns.", False),
 "choreography": ("article", "Choreography pattern", "https://learn.microsoft.com/en-us/azure/architecture/patterns/choreography", LEARN, "Services coordinating through events without a central coordinator.", False),
 "msio-saga": ("article", "Pattern: Saga", "https://microservices.io/patterns/data/saga.html", MSIO, "Maintaining consistency across services with compensations.", False),
 "event-sourcing-azure": ("article", "Event Sourcing pattern", "https://learn.microsoft.com/en-us/azure/architecture/patterns/event-sourcing", LEARN, "Storing state as an append-only log of events.", False),
 "event-sourcing-fowler": ("article", "Event Sourcing", "https://martinfowler.com/eaaDev/EventSourcing.html", FOWLER, "Capturing all changes to application state as events.", False),
 "idempotent-consumer": ("article", "Pattern: Idempotent consumer", "https://microservices.io/patterns/communication-style/idempotent-consumer.html", MSIO, "Handling duplicate messages safely.", False),
 "leader-election": ("article", "Leader Election pattern", "https://learn.microsoft.com/en-us/azure/architecture/patterns/leader-election", LEARN, "Electing one instance to coordinate work.", False),
 "kleppmann-locking": ("article", "How to do distributed locking", "https://martin.kleppmann.com/2016/02/08/how-to-do-distributed-locking.html", "Martin Kleppmann", "Why leases need fencing tokens to be safe.", False),
 "lamport": ("article", "Time, Clocks, and the Ordering of Events in a Distributed System", "https://lamport.azurewebsites.net/pubs/time-clocks.pdf", "Leslie Lamport", "The classic paper on logical clocks and causality.", True),
 "raft": ("link", "The Raft consensus algorithm", "https://raft.github.io/", "Raft", "An understandable consensus algorithm, with a visualization.", False),
 "outbox": ("article", "Pattern: Transactional outbox", "https://microservices.io/patterns/data/transactional-outbox.html", MSIO, "Publishing events reliably without dual writes.", False),
 "log-tailing": ("article", "Pattern: Transaction log tailing", "https://microservices.io/patterns/data/transaction-log-tailing.html", MSIO, "Relaying outbox messages with change data capture.", False),
 "debezium": ("link", "Debezium documentation", "https://debezium.io/documentation/", "Debezium", "Change data capture from database logs into Kafka.", True),
 "azure-patterns": ("link", "Azure Architecture Center: cloud design patterns", "https://learn.microsoft.com/en-us/azure/architecture/patterns/", LEARN, "One page per pattern, with when to use it and when not to.", False),
 "circuit-breaker": ("article", "Circuit Breaker pattern", "https://learn.microsoft.com/en-us/azure/architecture/patterns/circuit-breaker", LEARN, "Failing fast when a dependency is unhealthy.", False),
 "retry-pattern": ("article", "Retry pattern", "https://learn.microsoft.com/en-us/azure/architecture/patterns/retry", LEARN, "Retrying transient failures safely.", False),
 "aws-backoff": ("article", "Timeouts, retries and backoff with jitter", "https://aws.amazon.com/builders-library/timeouts-retries-and-backoff-with-jitter/", AWS, "How Amazon sets timeouts and avoids retry amplification.", False),
 "bulkhead": ("article", "Bulkhead pattern", "https://learn.microsoft.com/en-us/azure/architecture/patterns/bulkhead", LEARN, "Isolating resources so one failure can't sink everything.", False),
 "rate-limiting-pattern": ("article", "Rate Limiting pattern", "https://learn.microsoft.com/en-us/azure/architecture/patterns/rate-limiting-pattern", LEARN, "Controlling consumption to avoid throttling and overload.", False),
 "aws-load-shedding": ("article", "Using load shedding to avoid overload", "https://aws.amazon.com/builders-library/using-load-shedding-to-avoid-overload/", AWS, "Dropping excess work to protect the core service.", False),
 "aws-builders": ("link", "Amazon Builders' Library", "https://aws.amazon.com/builders-library/", AWS, "Production lessons on retries, load shedding and more.", False),
 "cache-aside": ("article", "Cache-Aside pattern", "https://learn.microsoft.com/en-us/azure/architecture/patterns/cache-aside", LEARN, "Loading data into a cache on demand.", False),
 "caching-guidance": ("article", "Caching guidance", "https://learn.microsoft.com/en-us/azure/architecture/best-practices/caching", LEARN, "Strategies, invalidation and consistency for caches.", False),
 "twelve-factor": ("link", "The Twelve-Factor App", "https://12factor.net/", "Adam Wiggins", "Principles for stateless, portable, scalable services.", False),
 "sharding": ("article", "Sharding pattern", "https://learn.microsoft.com/en-us/azure/architecture/patterns/sharding", LEARN, "Splitting data across horizontal partitions.", False),
 "data-partitioning": ("article", "Data partitioning guidance", "https://learn.microsoft.com/en-us/azure/architecture/best-practices/data-partitioning", LEARN, "Choosing partition keys and avoiding hot partitions.", False),
 "competing-consumers": ("article", "Competing Consumers pattern", "https://learn.microsoft.com/en-us/azure/architecture/patterns/competing-consumers", LEARN, "Many consumers processing one queue concurrently.", False),
 "queue-leveling": ("article", "Queue-Based Load Leveling pattern", "https://learn.microsoft.com/en-us/azure/architecture/patterns/queue-based-load-leveling", LEARN, "A queue as a buffer between bursty producers and steady consumers.", False),
 "gateway": ("article", "Use API gateways in microservices", "https://learn.microsoft.com/en-us/azure/architecture/microservices/design/gateway", LEARN, "Routing, aggregation and offloading at a single entry point.", False),
 "bff": ("article", "Backends for Frontends pattern", "https://learn.microsoft.com/en-us/azure/architecture/patterns/backends-for-frontends", LEARN, "A dedicated backend per client type.", False),
 "sidecar": ("article", "Sidecar pattern", "https://learn.microsoft.com/en-us/azure/architecture/patterns/sidecar", LEARN, "Deploying cross-cutting concerns next to each service.", False),
 "pubsub": ("article", "Publisher-Subscriber pattern", "https://learn.microsoft.com/en-us/azure/architecture/patterns/publisher-subscriber", LEARN, "Announcing events to many interested consumers.", False),
 "claim-check": ("article", "Claim-Check pattern", "https://learn.microsoft.com/en-us/azure/architecture/patterns/claim-check", LEARN, "Sending a reference to a large payload instead of the payload.", False),
 "blue-green": ("article", "Blue-green deployment", "https://martinfowler.com/bliki/BlueGreenDeployment.html", FOWLER, "Switching traffic between two production environments.", False),
 "canary": ("article", "Canary release", "https://martinfowler.com/bliki/CanaryRelease.html", FOWLER, "Rolling out to a small share of users first.", False),
 "feature-toggles": ("article", "Feature toggles (aka feature flags)", "https://martinfowler.com/articles/feature-toggles.html", "Pete Hodgson", "Kinds of toggles, and how to manage them.", False),
 "sd-primer": ("link", "System Design Primer", "https://github.com/donnemartin/system-design-primer", "Donne Martin", "Practice questions with worked answers.", False),
 "stripe-rate": ("article", "Scaling your API with rate limiters", "https://stripe.com/blog/rate-limiters", "Stripe", "How Stripe uses several kinds of limiters in production.", True),
 "multitenant": ("article", "Architect multitenant solutions on Azure", "https://learn.microsoft.com/en-us/azure/architecture/guide/multitenant/overview", LEARN, "Isolation, noisy neighbours and multitenancy trade-offs.", False),
 "tenancy-models": ("article", "Tenancy models for a multitenant solution", "https://learn.microsoft.com/en-us/azure/architecture/guide/multitenant/considerations/tenancy-models", LEARN, "Shared, per-schema and per-database models compared.", False),
 "priority-queue": ("article", "Priority Queue pattern", "https://learn.microsoft.com/en-us/azure/architecture/patterns/priority-queue", LEARN, "Processing high-priority work before the rest.", False),
 "audit-log": ("article", "Audit log", "https://martinfowler.com/eaaDev/AuditLog.html", FOWLER, "Recording a simple log of changes.", False),
 "otel-docs": ("link", "OpenTelemetry documentation", "https://opentelemetry.io/docs/", "OpenTelemetry", "Vendor-neutral logs, metrics and traces.", False),
 "sre-monitoring": ("article", "Monitoring distributed systems", "https://sre.google/sre-book/monitoring-distributed-systems/", "Google SRE", "The four golden signals and alerting philosophy.", False),
 "adr": ("link", "Architecture decision records", "https://adr.github.io/", "ADR GitHub organization", "Templates and tooling for recording decisions.", False),
 "nygard-adr": ("article", "Documenting architecture decisions", "https://cognitect.com/blog/2011/11/15/documenting-architecture-decisions", "Michael Nygard", "The post that introduced the ADR format.", False),
 "monolith-first": ("article", "Monolith First", "https://martinfowler.com/bliki/MonolithFirst.html", FOWLER, "Why most successful microservice systems started as monoliths.", False),
 "waf": ("article", "Azure Well-Architected Framework", "https://learn.microsoft.com/en-us/azure/well-architected/", LEARN, "Pillars for reliable, secure, efficient workloads.", False),
 "tech-debt": ("article", "Technical debt", "https://martinfowler.com/bliki/TechnicalDebt.html", FOWLER, "The debt metaphor and how to reason about it.", False),
 "debt-quadrant": ("article", "Technical debt quadrant", "https://martinfowler.com/bliki/TechnicalDebtQuadrant.html", FOWLER, "Deliberate or inadvertent, prudent or reckless.", False),
 "c4": ("link", "The C4 model", "https://c4model.com/", "Simon Brown", "Context, container, component and code diagrams.", False),
 "design-docs": ("article", "Design docs at Google", "https://www.industrialempathy.com/posts/design-docs-at-google/", "Malte Ubl", "What a good design doc contains and when to write one.", False),
 "staffeng": ("link", "StaffEng guides", "https://staffeng.com/guides/", "Will Larson", "Guides on operating as a Staff-plus engineer.", False),
}

D1, D2, D3, D4, D5 = "Design Principles & Patterns", "DDD & Application Architecture", "Distributed Systems", "Resilience & Scalability", "System Design & Judgement"

Q = [
 ("Which description of the SOLID principles is accurate?", [D1, "SOLID"], "medium",
  "Single responsibility, open-closed, Liskov substitution, interface segregation and dependency inversion, applied with judgement rather than dogma.",
  ["SOLID requires an interface for every class, because dependency inversion forbids depending on any concrete type, even private helpers inside one module.",
   "They are five performance rules: single thread, open connections, lazy loading, inline methods and direct database access.",
   "Liskov substitution says subclasses may change the base contract freely, as long as the method signatures stay the same."],
  "Single responsibility (one reason to change), open-closed (extend without editing), Liskov substitution (subtypes honour the base contract), interface segregation (small client-specific interfaces), dependency inversion (depend on abstractions you own). Then the caveat: applied dogmatically they produce needless interfaces.",
  ["arch-principles", "lsp"]),
 ("Should you prefer composition or inheritance?", [D1], "easy",
  "Prefer composition for flexibility and testability; use inheritance for true is-a relationships with a stable base type.",
  ["Prefer inheritance everywhere, because deep class hierarchies maximize code reuse and make every behaviour easy and safe to override later.",
   "Composition is only possible in functional languages; in C# inheritance is the sole mechanism for reuse.",
   "A subclass overriding a method to throw NotSupportedException is the recommended way to opt out of base behaviour."],
  "Prefer composition: it is flexible, testable and avoids the fragile base class problem. Inheritance fits true is-a relationships with stable base types and shared behaviour. A smell: a subclass that overrides to throw NotSupported, which breaks Liskov.",
  ["composition"]),
 ("How do DRY, KISS and YAGNI interact, and when do they conflict?", [D1], "medium",
  "DRY removes duplicated knowledge, not text, and YAGNI avoids speculative features, so wait for the rule of three before abstracting.",
  ["DRY means any two code blocks that look the same must be merged immediately, even when they change for different business reasons over time.",
   "YAGNI means building every extension point up front, so that future requirements never require changing code.",
   "KISS forbids abstractions entirely, so all three principles agree that duplication is always preferable."],
  "DRY removes duplicated knowledge, not duplicated text; merging two things that merely look alike couples them. YAGNI says do not build for speculative needs. Wait for the third occurrence (rule of three) before abstracting, and weigh the cost of a wrong abstraction against some duplication.",
  ["yagni", "rule-of-three", "fowler-bliki"]),
 ("How does dependency injection differ from inversion of control and a service locator?", [D1, "Dependency injection"], "medium",
  "IoC means the framework calls your code; DI passes collaborators in explicitly, while a service locator hides them behind a global lookup.",
  ["They are three names for the same technique, so a service locator is exactly as explicit and testable as constructor injection in practice.",
   "A service locator makes dependencies visible in the constructor, while DI resolves them through a static registry.",
   "Inversion of control means your code calls the framework directly, instead of the framework calling you."],
  "Inversion of control means the framework calls your code. Dependency injection passes collaborators in, usually through the constructor, which makes dependencies explicit and testable. A service locator hides them behind a global lookup, so dependencies are invisible and fail at runtime.",
  ["di-dotnet"]),
 ("When is the Strategy pattern the right tool?", [D1, "Patterns"], "easy",
  "When behaviour varies by context and should be swappable without conditionals, such as pricing rules or export formats.",
  ["When a complex object must be assembled step by step while remaining valid at every intermediate stage of its construction.",
   "When an object must notify many listeners of its state changes without knowing who they are.",
   "When you need exactly one instance of a class shared globally across the application."],
  "When behaviour varies by context and you want to swap it without conditionals: pricing rules, retry policies, export formats. Inject the strategy, pick it by key or rule. In C# a delegate is often enough; a full interface pays off when the strategy has state or several methods.",
  ["rg-strategy", "rg-catalogue"]),
 ("How do Factory Method, Abstract Factory and Builder differ?", [D1, "Patterns"], "medium",
  "Factory Method defers which subtype is created, Abstract Factory creates families of related objects, and Builder assembles one complex object step by step.",
  ["Factories are always required alongside a DI container, because the container cannot construct objects with constructor parameters on its own.",
   "They are interchangeable names for any static method that returns a new instance.",
   "Builder creates families of related objects, while Abstract Factory assembles a single object in many steps."],
  "Factory Method defers which subtype is created. Abstract Factory creates families of related objects. Builder assembles a complex object step by step and keeps it valid. In DI-based code, factories are mostly needed when the type depends on runtime data.",
  ["rg-factory-method", "rg-abstract-factory"]),
 ("How do Decorator, Adapter, Facade and Proxy differ?", [D1, "Patterns"], "medium",
  "All wrap an object: Decorator adds behaviour behind the same interface, Adapter converts interfaces, Facade simplifies a subsystem, Proxy controls access.",
  ["They differ only in the shape of their class diagrams, so the intent behind a wrapper never matters when you choose between the four of them.",
   "Decorator converts one interface into another, while Adapter adds logging or caching behind the same interface.",
   "Facade and Proxy are identical, and both exist only to lazy-load objects from a database."],
  "All wrap another object. Decorator adds behaviour behind the same interface (logging, caching, retry). Adapter converts one interface into another. Facade offers a simpler interface over a subsystem. Proxy controls access (lazy loading, auth). Name the intent, not the structure.",
  ["rg-decorator", "rg-adapter", "rg-facade"]),
 ("When is Observer or an in-process event bus a good idea, and when is it harmful?", [D1, "Patterns"], "medium",
  "Good for decoupled side effects of a change; harmful when core flow becomes invisible and ordering or error handling are unclear.",
  ["Use events for the core business flow and direct method calls only for logging, since events make every step of the main flow easier to trace.",
   "Always better than direct calls, because events make every flow easier to follow and debug.",
   "Harmful only for performance; every in-process bus guarantees ordering and error handling."],
  "Good for decoupled reactions to a change. Harmful when flow becomes invisible, ordering and error handling are unclear, or handlers leak (see the event-leak question in the .NET set). Prefer explicit calls for core flow and events for genuine side effects.",
  ["rg-observer"]),
 ("Why is the Singleton pattern often considered a smell?", [D1, "Patterns"], "easy",
  "It brings global mutable state and hidden dependencies that are hard to test; prefer a singleton lifetime in the DI container.",
  ["Because the DI container cannot register singleton lifetimes, so a hand-written static instance is the only way to share one object.",
   "Because a singleton allocates a new instance on every access, which wastes memory.",
   "Because singletons can never be made thread-safe in .NET."],
  "Global mutable state, hidden dependencies, hard to test, and thread-safety risks. In .NET prefer a singleton lifetime in the DI container over a hand-written static instance, and keep that instance stateless or thread-safe.",
  ["rg-singleton"]),
 ("Are Repository and Unit of Work still useful with EF Core?", [D1, "EF Core"], "medium",
  "A thin generic wrapper adds little, since DbContext is already a unit of work, but an aggregate-focused repository can still earn its place.",
  ["Yes, always wrap DbContext in a generic repository that exposes IQueryable to callers, so any layer can compose whatever query it needs.",
   "No, because EF Core can't track changes across several entities without an explicit unit-of-work class.",
   "Repositories are required by EF Core, which refuses to save entities not accessed through one."],
  "DbContext already is a unit of work and DbSet a repository, so a thin generic wrapper adds little. A repository still earns its place as an aggregate-focused abstraction in a domain model, or to hide complex queries. Do not leak IQueryable through it.",
  ["persistence-layer"]),

 ("What is a bounded context, and how do you find one?", [D2, "DDD"], "medium",
  "A boundary within which a model and its terms have one consistent meaning; find it by listening for where words change meaning.",
  ["A shared enterprise-wide model in which every business term must mean exactly the same thing to every team in the whole organization.",
   "A single database table plus the service that owns it, so every table becomes its own bounded context.",
   "A deployment unit such as a container, so the number of contexts always equals the number of services."],
  "A boundary inside which a model and its words have one consistent meaning (\"campaign\" means something different to billing and to delivery). Find them by listening to language, to who owns what, and to where the same word changes meaning. They guide service and module boundaries.",
  ["bounded-context", "domain-analysis"]),
 ("What are entities, value objects and aggregates?", [D2, "DDD"], "easy",
  "An entity has lasting identity, a value object is immutable and defined by its values, and an aggregate is a consistency unit with one root.",
  ["An entity is immutable and defined only by its values, while a value object has an identity that persists over time and across changes.",
   "An aggregate is any set of entities loaded together for reporting, with no rules about access.",
   "Value objects need a database id, so they can be updated in place when a field changes."],
  "An entity has identity that persists over time. A value object is defined by its values, is immutable and is replaceable (money, address, date range). An aggregate is a cluster of objects treated as one consistency unit, with a single root as its only entry point.",
  ["tactical-ddd", "ddd-aggregate"]),
 ("How should you design aggregate boundaries?", [D2, "DDD"], "hard",
  "Keep them small and built around true invariants, reference other aggregates by id, and change one aggregate per transaction.",
  ["Update several aggregates in a single transaction whenever one use case touches them, so you never have to deal with eventual consistency.",
   "Make aggregates as large as possible, so one transaction keeps the whole domain consistent.",
   "Reference other aggregates by object reference, so they always load together in one query."],
  "Keep them small and based on true invariants that must be consistent in one transaction. Reference other aggregates by id, not object. One aggregate per transaction; use eventual consistency (events) between aggregates. Large aggregates cause contention and slow loads.",
  ["ddd-aggregate", "domain-model-layer"]),
 ("What is the difference between a domain event and an integration event?", [D2, "DDD"], "medium",
  "A domain event happens inside a bounded context and is handled in-process; an integration event is a published contract for other services.",
  ["They are the same thing, so domain events should be published directly to other services as your public contract, without any translation.",
   "Integration events are handled in the same database transaction, while domain events always travel through a broker.",
   "Domain events need a stable versioned schema, while integration events can change freely."],
  "A domain event is something that happened inside a bounded context, handled in-process and often in the same transaction. An integration event is a published contract that other services consume; it needs a stable schema and reliable delivery (the outbox). Do not expose domain events as your public contract.",
  ["domain-events"]),
 ("What is the difference between an anemic and a rich domain model?", [D2, "DDD"], "medium",
  "An anemic model keeps logic in services so invariants can be bypassed; a rich model protects invariants behind behaviour on the entities.",
  ["A rich model stores more columns per entity, while an anemic model normalizes the same data across many more database tables to save space.",
   "Anemic models are always wrong, even for simple CRUD without business rules.",
   "A rich model keeps all logic in application services and entities as property bags."],
  "An anemic model holds data in entities and logic in services, so invariants can be bypassed. A rich model puts behaviour with the data and protects invariants behind methods. Rich is better for complex rules; plain data and services are fine for simple CRUD. Say which you chose and why.",
  ["anemic"]),
 ("What do clean, hexagonal and onion architecture have in common?", [D2, "Architecture"], "medium",
  "They invert dependencies so the domain owns ports and outer adapters plug in, at the cost of indirection and mapping code.",
  ["They place the database at the centre, so the domain model depends directly on the persistence framework and its generated entity types.",
   "They have no trade-offs, since the extra layers add neither boilerplate nor mapping code.",
   "They require microservices, since a single deployable can't have a core and adapters."],
  "All invert dependencies so the domain does not depend on frameworks, databases or UI: the core defines ports (interfaces), outer layers provide adapters. Benefits: testability and replaceable infrastructure. Cost: indirection, mapping code and boilerplate.",
  ["hexagonal", "clean-arch"]),
 ("When would you choose vertical slice over layered architecture?", [D2, "Architecture"], "medium",
  "Slices group everything for one feature and cut cross-layer churn; layers group by technical role and suit strict, uniform structure.",
  ["Vertical slices group code by technical role, while layers group everything one feature needs, from the endpoint down to its data access.",
   "Never, because vertical slices forbid sharing any code between features.",
   "Layers and slices can't be combined, so each project must pick exactly one."],
  "Layers group code by technical role; slices group everything for one feature (endpoint, handler, data access). Slices cut cross-layer churn and let each feature choose its own complexity. Layers give uniform structure and can suit a large team with strict rules. Many teams combine them.",
  ["vertical-slice"]),
 ("What is an anti-corruption layer, and when do you need one?", [D2, "Integration"], "medium",
  "A translation layer that keeps a foreign or legacy model out of yours, used when integrating partners or legacy systems.",
  ["A shared client library that every service imports, so all services work directly with the partner's own data model and naming everywhere.",
   "A firewall rule that blocks malicious requests before they reach the domain model.",
   "A database trigger that rejects rows violating the domain's invariants."],
  "A translation layer that stops a foreign or legacy model from leaking into yours. Use it when integrating with partner APIs (Klaviyo, Zapier) or legacy systems whose concepts differ from your domain. It centralizes mapping and gives one place to absorb their changes.",
  ["acl"]),
 ("Is a mediator or in-process command bus worth it?", [D2, "Architecture"], "medium",
  "It standardizes handlers and pipeline behaviours at the cost of indirection, so it's worth it only if you need those pipelines.",
  ["Always, because it removes all coupling between components and also makes navigating the code base easier for every new team member.",
   "Never, because it can't be combined with dependency injection or validation.",
   "It is mandatory for CQRS, which cannot be built without a mediator library."],
  "It standardizes handlers, and pipelines for validation, logging and transactions. Costs: indirection, harder navigation, hidden coupling, and a library dependency. Plain application services or minimal-API handlers are often enough. Judge by whether you need the pipeline behaviours.",
  ["cqrs"]),
 ("Where does a business rule belong: entity, domain service or application service?", [D2, "DDD"], "hard",
  "In the entity for its own invariants and a domain service when it spans aggregates; the application service only orchestrates.",
  ["Always in the application service, so that entities stay simple data holders that the ORM can map without needing any custom configuration.",
   "In the controller, because that is where request data is validated first.",
   "In the repository, since it loads the data and can check rules while saving."],
  "If it concerns one aggregate's own invariants, in the entity. If it spans aggregates and has no natural owner, a domain service. The application service only orchestrates: load, call, save, publish. Keep I/O and transactions out of the domain layer.",
  ["tactical-ddd"]),

 ("What do the CAP theorem and PACELC mean in practice?", [D3, "Consistency"], "hard",
  "During a partition you choose consistency or availability; PACELC adds a latency-versus-consistency trade-off even without one.",
  ["You can pick any two of consistency, availability and partition tolerance, so giving up partition tolerance is a valid choice on a real network.",
   "A product is permanently either CP or AP, so the choice is made once rather than per operation.",
   "CAP applies only to SQL databases, and PACELC says partitions never happen."],
  "When a network partition happens you must choose between consistency and availability; you cannot give up partition tolerance on a real network. PACELC adds that even without a partition you trade latency for consistency. Real systems choose per operation, not per product.",
  ["cap", "pacelc", "fallacies"]),
 ("What does eventual consistency mean for users?", [D3, "Consistency"], "medium",
  "Replicas converge if writes stop, with no time bound, so design the UX around pending states and read-your-writes.",
  ["Every read returns the latest write, but only after a fixed delay of a few seconds that the database guarantees for every replica in the cluster.",
   "Data is consistent within one request but may stay different between replicas forever.",
   "It guarantees causal ordering for all users, so reversals are impossible."],
  "Strong (linearizable), sequential, causal, read-your-writes, eventual. Eventual means replicas converge if writes stop, with no promise about when. Design the user experience around it: show pending states, read from the primary after a write, avoid surprising reversals.",
  ["jepsen"]),
 ("Why avoid two-phase commit across services, and what do you use instead?", [D3, "Transactions"], "hard",
  "2PC blocks when the coordinator fails and ties availability to every participant; use local transactions, sagas and the outbox.",
  ["2PC is the recommended default for microservices, because every modern message queue and database supports it natively and without any blocking.",
   "Use one shared database for all services, so distributed transactions are never needed.",
   "Replace it with retries alone, since retried writes are always consistent across services."],
  "2PC blocks while the coordinator is down, ties availability to every participant and is unsupported by most modern stores and queues. Use local transactions plus sagas and compensations, with the outbox for reliable messaging.",
  ["2pc", "saga-azure", "msio-patterns"]),
 ("Should a saga use orchestration or choreography?", [D3, "Sagas"], "hard",
  "Orchestration keeps the flow visible and testable in one coordinator; choreography decouples services but hides the overall flow.",
  ["Choreography is always better, because a central coordinator makes the overall flow harder to see, test and change than services reacting to events.",
   "Orchestration requires every service to share one database, while choreography does not.",
   "They behave identically at runtime and differ only in how the diagrams are drawn."],
  "Orchestration: a central coordinator (such as a Temporal workflow) holds the flow, which is visible, testable and easy to change, but is a coordination point. Choreography: services react to each other's events, which is decoupled but makes the overall flow hard to see and debug. Prefer orchestration for long or critical business flows.",
  ["choreography", "msio-saga"]),
 ("What is event sourcing, and what does it cost?", [D3, "Event sourcing"], "hard",
  "State is stored as an append-only event log and rebuilt by replay; costs include event schema evolution, replay time and eventual reads.",
  ["It means publishing every database change to Kafka, while the current-state tables remain the source of truth that all reads and writes rely on.",
   "A free upgrade over CRUD with no extra complexity, so it should be the default for every service.",
   "Events are mutable records, updated in place whenever the business state changes."],
  "State is stored as an append-only sequence of events and rebuilt by replay. You get a full audit trail, time travel and new projections. Costs: schema evolution of old events, replay time (snapshots), eventual read models, and a steep learning curve. Not a default; use it where history is the business.",
  ["event-sourcing-azure", "event-sourcing-fowler"]),
 ("Is exactly-once delivery possible end to end?", [D3, "Messaging"], "medium",
  "Not end to end; combine at-least-once delivery with idempotent processing to get the effect of exactly-once.",
  ["Yes, every modern broker guarantees exactly-once delivery to any external system out of the box, as long as idempotent producers are enabled.",
   "Yes, as long as the consumer commits its offset before it processes the message.",
   "No, so consumers have to accept occasional duplicate side effects as unavoidable."],
  "Not end to end. You get at-least-once delivery plus idempotent processing, which has the effect of exactly-once. Implement it with an idempotency key or message id stored in the same transaction as the side effect (the inbox).",
  ["idempotent-consumer"]),
 ("How do distributed locks and leader election work, and why are they risky?", [D3, "Coordination"], "hard",
  "A lease in a shared store elects one holder, but pauses and clock skew can produce two holders, so protect the resource with fencing tokens.",
  ["Locks held in Redis are perfectly safe, because the clocks of machines in one cluster never drift and processes never pause while holding a lease.",
   "Leader election needs no shared store, since each node decides on its own that it leads.",
   "Distributed locks are always preferable to idempotent work, because they cost nothing."],
  "A lease in a shared store (database, Redis, etcd, a blob) elects one holder. Risks: pauses and clock skew let two nodes believe they hold it, so protect the resource with a fencing token. Prefer designs that need no lock, such as idempotent work or SKIP LOCKED claims.",
  ["leader-election", "kleppmann-locking"]),
 ("How do you order events across machines when clocks disagree?", [D3, "Ordering"], "hard",
  "Don't trust wall clocks: use per-key log ordering, sequence numbers or logical clocks, and order per entity when that's enough.",
  ["Synchronize every server with NTP and sort all events by their wall-clock timestamp, which yields an exact and reliable global order across machines.",
   "Global ordering is always required, so route every event through one single-partition topic.",
   "Ordering is irrelevant in distributed systems, so consumers can process events in any order."],
  "Wall clocks drift, so do not rely on them for ordering. Use per-key ordering in a log partition, sequence numbers, or logical and vector clocks to capture causality. Say what ordering the business really needs: usually per entity, not global.",
  ["lamport"]),
 ("What should a back-end engineer know about consensus algorithms such as Raft?", [D3, "Consensus"], "medium",
  "A majority quorum agrees on a replicated log through an elected leader; it tolerates minority failures and underlies etcd and Consul.",
  ["Consensus works best with an even number of nodes, so that a tie between two equal halves can be broken by a random election among the leaders.",
   "Raft needs every node to agree before committing, so one failed node halts the cluster.",
   "Every service that needs replication should implement its own Raft from scratch."],
  "A cluster agrees on a log using a majority quorum; a leader replicates entries and a new leader is elected on failure. It tolerates minority failure, and needs an odd number of nodes. It underlies etcd, Consul and many databases. You need to use it wisely, not implement it.",
  ["raft"]),
 ("How do you keep a database and a message broker consistent?", [D3, "Messaging"], "hard",
  "Write the event to an outbox table in the same transaction, then relay it by polling or CDC to idempotent consumers.",
  ["Write to the database and then publish to the broker in the same method; the two calls run back to back, so they are atomic in practice.",
   "Publish to the broker first and let consumers write the database, so nothing can diverge.",
   "Use a distributed two-phase commit between the database and Kafka on every write."],
  "Writing to both can leave one updated and the other not. Write the event into an outbox table in the same transaction, then publish it by polling or by change data capture on the log (Debezium). Consumers must be idempotent because relays deliver at least once.",
  ["outbox", "log-tailing", "debezium"]),

 ("How do timeouts, retries and circuit breakers fit together?", [D4, "Resilience"], "medium",
  "Every remote call gets a timeout, retries cover only transient idempotent failures with jittered backoff, and a breaker fails fast.",
  ["Retry every failure immediately and indefinitely, because a circuit breaker only adds latency and hides the real error from callers and operators.",
   "Timeouts are unnecessary when retries exist, because retries eventually succeed.",
   "A circuit breaker retries calls more aggressively while a dependency is failing."],
  "Every remote call gets a timeout. Retry only transient, idempotent failures, with exponential backoff and jitter and a retry budget. A circuit breaker stops calling a failing dependency so it can recover and callers fail fast. Layered wrongly, retries multiply load (a retry storm).",
  ["circuit-breaker", "retry-pattern", "aws-backoff", "azure-patterns"]),
 ("What is the bulkhead pattern, and how does it limit blast radius?", [D4, "Resilience"], "medium",
  "Partition resources such as pools, queues or deployments, so one failing part or noisy tenant can't exhaust the rest.",
  ["Put all tenants into one shared pool of threads and connections, so spare capacity is always available to whichever tenant happens to need it most.",
   "Replicate every service three times, so any single failure is invisible to users.",
   "A bulkhead is a firewall in front of the database that blocks slow queries."],
  "Partition resources (thread pools, connection pools, queues, whole deployments for tenant groups) so one failing part cannot exhaust the rest. A noisy tenant or a slow partner then hurts only its own compartment. Cells take it further by isolating whole slices of the system.",
  ["bulkhead"]),
 ("How do backpressure, load shedding and rate limiting differ?", [D4, "Scalability"], "medium",
  "Backpressure slows producers, load shedding drops low-priority work under overload, and rate limiting caps each caller's rate.",
  ["They are three names for one mechanism, which rejects excess requests with HTTP 429 regardless of where the overload is actually coming from.",
   "Load shedding drops the most important work first, so the system recovers faster.",
   "Backpressure means adding more servers automatically whenever a queue grows."],
  "Backpressure tells producers to slow down (bounded queues, flow control). Load shedding drops low-priority work to protect the core when overloaded. Rate limiting caps request rates per caller (token bucket, sliding window). Together they keep the system degrading gracefully instead of collapsing.",
  ["rate-limiting-pattern", "aws-load-shedding", "aws-builders"]),
 ("How do cache-aside, write-through and write-behind compare?", [D4, "Caching"], "medium",
  "Cache-aside loads on a miss and is the usual default; write-through keeps the cache fresh at a write cost; write-behind risks losing writes.",
  ["Write-behind is the safest of the three, because writes buffered in the cache can never be lost even if the cache node crashes before flushing them.",
   "Cache-aside writes to the cache and the database together on every update.",
   "With any of these strategies, invalidation and stampedes stop being concerns."],
  "Cache-aside: the app loads on a miss and writes to the cache; simple and the common default. Write-through writes both together, keeping the cache fresh at higher write latency. Write-behind buffers writes and risks loss. Discuss invalidation, TTL, stampedes and what happens if the cache is down.",
  ["cache-aside", "caching-guidance"]),
 ("What makes a service horizontally scalable?", [D4, "Scalability"], "easy",
  "Stateless instances behind a load balancer, state in a shared store, config from the environment, and graceful shutdown.",
  ["Keeping user sessions and uploaded files on each instance's local disk, which avoids network hops and makes every added instance faster than the last.",
   "Running one very large server, since vertical scaling is what horizontal scaling means.",
   "Adding instances is always enough, since the database is never the bottleneck."],
  "Stateless instances behind a load balancer, with state in a shared store, no local session data or files, config from the environment, fast startup and graceful shutdown. Identify the real bottleneck first, which is often the database, and scale that deliberately.",
  ["twelve-factor"]),
 ("How do you shard data, and what is a hot partition?", [D4, "Data"], "hard",
  "Pick a key that spreads load and keeps related data together; a hot partition is one key receiving a disproportionate share.",
  ["Shard by a random value per row, so related data is spread across as many shards as possible and cross-shard queries become the fast path.",
   "A hot partition is a shard that failed over to a replica, and resharding is free.",
   "Cross-shard transactions are cheap, so the choice of shard key rarely matters."],
  "Choose a key that spreads load evenly and keeps related data together (tenant id, hash of id, time range). A hot partition occurs when one key gets a disproportionate share, as with a huge tenant or a celebrity. Resharding is costly, so plan for it and avoid cross-shard queries and transactions.",
  ["sharding", "data-partitioning"]),
 ("When do you use competing consumers and queue-based load leveling?", [D4, "Messaging"], "medium",
  "A queue absorbs bursts and several consumers share it for throughput; handlers must be idempotent, with a dead-letter queue.",
  ["When strict global ordering is required, because competing consumers always process messages in the exact order in which they were produced.",
   "When every message must be processed once by every consumer in the group.",
   "Only for synchronous request-response calls that need an immediate answer."],
  "A queue absorbs bursts so workers process at a steady rate, and several consumers share the queue to scale throughput. Requirements: idempotent handlers, visibility timeouts, a dead-letter queue, and awareness that ordering is lost unless you partition by key.",
  ["competing-consumers", "queue-leveling"]),
 ("What distinguishes an API gateway, a backend for frontend and a service mesh?", [D4, "Integration"], "medium",
  "A gateway is the single entry point, a BFF is a gateway tailored to one client, and a mesh handles service-to-service concerns via sidecars.",
  ["They are the same component, and business logic belongs in the gateway so that the services behind it can stay thin and almost free of rules.",
   "A service mesh is the public entry point for browsers, while a gateway handles mTLS.",
   "A BFF is a database view optimized for front-end queries."],
  "A gateway is the single entry point for routing, auth, throttling and aggregation. A BFF is a gateway tailored to one client type. A service mesh handles service-to-service concerns (mTLS, retries, telemetry) through sidecars. Risks: a gateway can become a bottleneck or a place where logic piles up.",
  ["gateway", "bff", "sidecar"]),
 ("What is the difference between a command and an event, and what is a claim check?", [D4, "Messaging"], "medium",
  "A command asks one receiver to act and can be rejected; an event states a past fact; a claim check sends a reference to a large payload.",
  ["An event asks one receiver to do something and can be rejected, while a command broadcasts a fact that already happened to any number of subscribers.",
   "A claim check embeds the whole payload in every message, so no storage is needed.",
   "Commands and events are interchangeable, and both always have one subscriber."],
  "A command asks one receiver to do something and can be rejected; an event states a fact that already happened and has any number of subscribers. The claim check keeps large payloads in blob storage and sends only a reference, which keeps messages small and within broker limits.",
  ["pubsub", "claim-check"]),
 ("How do blue-green, canary and feature-flag releases compare?", [D4, "Delivery"], "medium",
  "Blue-green switches between two environments, canary shifts a small share of traffic, and feature flags separate deploy from release.",
  ["Feature flags remove the need for backward-compatible data changes, and once added they never need to be cleaned up or removed from the code.",
   "Canary deploys to every server at once and rolls back only if all users report errors.",
   "Blue-green means two versions with separate databases that never share data."],
  "Blue-green switches traffic between two full environments for instant rollback. Canary sends a small share of traffic to the new version and watches metrics. Feature flags separate deploy from release and allow per-tenant rollout. All require backward-compatible data changes, and flags need cleanup.",
  ["blue-green", "canary", "feature-toggles"]),

 ("How should you approach a system design interview question?", [D5, "System design"], "medium",
  "Clarify requirements and scale, define the API and data model, sketch a simple design, then find the bottleneck from the numbers.",
  ["Start drawing the most scalable architecture you know straight away, since the requirements can safely be assumed and asking questions wastes time.",
   "Add caching, queues and sharding up front, regardless of the expected load.",
   "Focus on naming technologies; trade-offs and failure modes are out of scope."],
  "Clarify requirements and scale (users, reads versus writes, latency, data size). Define the API and data model. Sketch the simplest design, estimate load, find the bottleneck, then add caching, queues, partitioning or replication where the numbers demand it. Name the trade-offs and failure modes aloud. Example to practise: a URL shortener (id generation, redirects, caching, analytics).",
  ["sd-primer"]),
 ("How would you design a distributed rate limiter?", [D5, "System design"], "hard",
  "Choose an algorithm and a key, keep shared counters in Redis with atomic operations, and decide whether to fail open or closed.",
  ["Use only per-instance in-memory counters, which stay exact across a cluster of any size because the load balancer spreads requests perfectly evenly.",
   "Return HTTP 500 when the limit is reached, so clients retry immediately.",
   "Keep counters in the primary SQL database with a row lock per request."],
  "Choose an algorithm (token bucket or sliding window), a key (API key, tenant, IP) and where it runs (gateway, middleware). Shared counters in Redis with atomic operations give accuracy across instances; local limits are cheaper but approximate. Decide fail-open or fail-closed, the response (429 with Retry-After) and how to keep the limiter itself from becoming a bottleneck.",
  ["rate-limiting-pattern", "stripe-rate"]),
 ("How do you design a multi-tenant SaaS data layer?", [D5, "Multi-tenancy"], "hard",
  "Choose shared schema, schema per tenant or database per tenant by weighing isolation against cost, and mix models by tier.",
  ["Always use one database per tenant, since isolation never needs to be weighed against cost, operations effort or the number of tenants you serve.",
   "A shared schema needs no tenant id, because the application never mixes tenants.",
   "Store each tenant's data in a separate JSON file on the web server."],
  "Three models: shared schema with a tenant id (cheapest, needs strong isolation such as row-level security), schema per tenant, database per tenant (strongest isolation, highest cost). Weigh isolation, noisy neighbours, per-tenant customization, backup and restore, compliance and operational cost. Mix models by customer tier.",
  ["multitenant", "tenancy-models"]),
 ("How would you design a system that sends scheduled campaigns to millions of recipients?", [D5, "System design"], "hard",
  "Persist and chunk the audience, fan out through queues with per-provider rate limits, and keep idempotent per-recipient state.",
  ["Loop over every recipient inside one web request and call the email provider synchronously for each one, which keeps the design as simple as possible.",
   "Send everything at the scheduled time at once, ignoring provider limits and bounces.",
   "Track progress only in memory, since a failed send can restart from the beginning."],
  "Persist the campaign, plan and chunk the audience, fan out through queues, rate limit per provider, keep per-recipient state with idempotent sends, handle bounces and webhooks, and report progress. Use a workflow engine for the long-running orchestration, and discuss priority, cost and provider outages.",
  ["priority-queue", "queue-leveling"]),
 ("How do you build an audit log or change history?", [D5, "Data"], "medium",
  "Write append-only who-did-what-when records in the same transaction as the change, planning for retention, PII and querying.",
  ["Write audit entries asynchronously after the transaction commits, accepting that a few changes will be missing whenever a process crashes in between.",
   "Update the audit row in place whenever a record changes, keeping the latest action.",
   "Rely on application logs alone, since they are tamper-proof and kept forever."],
  "Append-only records of who did what, when and to what, written in the same transaction as the change (or from the outbox). Choices: triggers or CDC for completeness, application-level events for meaning. Cover tamper resistance, retention, PII handling, partitioning by time and how it is queried.",
  ["audit-log", "event-sourcing-azure"]),
 ("How do you design observability for a distributed system?", [D5, "Observability"], "medium",
  "Structured logs with correlation ids, RED metrics plus saturation, and propagated traces, with SLO-based alerts that have runbooks.",
  ["Log everything at debug level and keep it forever, since storage cost doesn't matter and more data always makes incidents faster to diagnose and resolve.",
   "Alert on every individual error, so no problem ever goes unnoticed.",
   "Use logs only, because metrics and traces duplicate what the logs already contain."],
  "Structured logs with correlation ids, RED metrics per service (rate, errors, duration) plus saturation, distributed traces propagated across HTTP, queues and workflows. Control cost with sampling and retention. Tie alerts to SLOs, and give each alert a runbook.",
  ["otel-docs", "sre-monitoring"]),
 ("How do you make and record an architectural decision?", [D5, "Decisions"], "medium",
  "Compare real alternatives against the quality attributes that matter, decide, and write a short ADR with context and consequences.",
  ["Write the decision record once and never revisit it, even after the context changes, so that the history of the architecture stays stable and clean.",
   "Choose the newest technology and avoid writing anything down, so the decision can change quietly.",
   "Let the most senior engineer decide alone, without recording alternatives."],
  "List the quality attributes that matter (latency, cost, security, changeability), generate real alternatives, compare them against those attributes, decide, and write a short architecture decision record with context, decision and consequences. Revisit it when the context changes.",
  ["adr", "nygard-adr"]),
 ("What is evolutionary architecture, and when should you split a monolith?", [D5, "Architecture"], "hard",
  "Keep change cheap with clear modules and fitness functions, and extract a service only when a real force such as scaling requires it.",
  ["Split the monolith into microservices on day one, before any module boundaries are known, because services are easier to merge later than to split.",
   "Never split a monolith, since services cannot evolve independently.",
   "Evolutionary architecture means rewriting the system from scratch each year."],
  "Design so change is cheap: clear module boundaries, automated tests and fitness functions that guard architectural rules in the build. Start as a modular monolith and extract a service only when a real force requires it (scaling, team autonomy, release cadence, isolation).",
  ["monolith-first", "waf"]),
 ("How do you decide build versus buy, and manage technical debt?", [D5, "Decisions"], "medium",
  "Build what differentiates the business, buy commodity needs counting total cost, and track debt and pay it down with a business reason.",
  ["Always build everything in-house, since buying or adopting open source only creates lock-in and integration work without delivering any real benefit.",
   "Always buy the cheapest tool, since licence price is the only cost that matters.",
   "Ignore technical debt until the system fails, then rewrite it from scratch."],
  "Build what differentiates the business; buy or adopt open source for commodity needs, counting integration, licence, lock-in and operating cost, not just price. Treat debt as deliberate or accidental, prudent or reckless; track it, size it, and pay it down alongside feature work with a business reason.",
  ["tech-debt", "debt-quadrant"]),
 ("How do you communicate a design and lead without owning every line?", [D5, "Leadership"], "medium",
  "Write a design doc with goals, non-goals and risks, draw C4 views, review early, and raise others' ability to decide.",
  ["Present only the option you already chose, hiding the alternatives and risks from reviewers so that the discussion stays short and the team moves faster.",
   "Write all the code yourself, so the design is never misunderstood.",
   "Skip documentation, since docs and diagrams slow teams down at Staff level."],
  "Write a design doc with goals, non-goals, options and risks; draw the C4 context and container views; get early review from the people who will run and use it; make the decision visible and the trade-offs honest. At Staff level, show how you raised others' ability and aligned teams, not only how you designed.",
  ["c4", "design-docs", "staffeng"]),
]


# Trim the long distractor in a few questions so the correct answer is the
# longest about as often as chance would give (see gen_lib.build).
SHORTER = {
 3: "DRY means merging any two code blocks that look alike, even if they change for different reasons.",
 9: "Because the DI container cannot register singletons, so a static instance is the only option.",
 14: "They are the same, so domain events should be published directly as your public contract.",
 19: "Always, because it removes all coupling between components and makes navigation easier.",
 26: "Yes, every modern broker guarantees exactly-once delivery to any external system.",
 33: "They are three names for one mechanism that rejects excess requests with HTTP 429.",
 41: "Start drawing the most scalable architecture at once, since requirements can be assumed.",
 47: "Write the decision record once and never revisit it, even after the context changes.",
}
Q = [(p, t, d, c, [SHORTER[i]] + w[1:] if i in SHORTER else w, e, m)
     for i, (p, t, d, c, w, e, m) in enumerate(Q, 1)]

assert len(Q) == 50, len(Q)
build("50 design, architecture and pattern questions", M, Q, sys.argv[1])
