import os, sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))  # tools/question-banks
from bankgen import build

LEARN, PG, IETF, OWASP = "Microsoft Learn", "PostgreSQL documentation", "IETF", "OWASP"

M = {
 "cs12": ("article", "What's new in C# 12", "https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-12", LEARN, "Primary constructors, collection expressions and other C# 12 features.", False),
 "required": ("article", "required modifier (C# reference)", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/required", LEARN, "Forcing callers to initialize a member at construction.", True),
 "lock-blog": ("link", "Andrew Lock's blog", "https://andrewlock.net/", "Andrew Lock", "ASP.NET Core internals and C# language features in depth.", False),
 "pattern-matching": ("article", "Pattern matching overview", "https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/patterns/pattern-matching", LEARN, "is, switch expressions and property patterns.", False),
 "switch-expr": ("article", "switch expression (C# reference)", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/switch-expression", LEARN, "Arms, guards and exhaustiveness warnings.", True),
 "init": ("article", "init keyword (C# reference)", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/init", LEARN, "Init-only setters for immutable objects.", True),
 "with": ("article", "with expression (C# reference)", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/with-expression", LEARN, "Non-destructive mutation of records and structs.", True),
 "constraints": ("article", "Constraints on type parameters", "https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/generics/constraints-on-type-parameters", LEARN, "where clauses and what they let the compiler allow.", False),
 "generic-math": ("article", "Generic math", "https://learn.microsoft.com/en-us/dotnet/standard/generics/math", LEARN, "INumber<T> and static abstract interface members.", False),
 "expression-trees": ("article", "Expression trees", "https://learn.microsoft.com/en-us/dotnet/csharp/advanced-topics/expression-trees/", LEARN, "Code as data, and how providers translate it.", False),
 "reflection": ("article", "Reflection in .NET", "https://learn.microsoft.com/en-us/dotnet/fundamentals/reflection/overview", LEARN, "Inspecting and invoking types at runtime.", True),
 "source-gen": ("article", "Source generators overview", "https://learn.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview", LEARN, "Generating code at compile time with Roslyn.", False),
 "stj-sourcegen": ("article", "System.Text.Json source generation", "https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/source-generation", LEARN, "Reflection-free, AOT-friendly JSON serialization.", False),
 "dotnet-blog": ("link", ".NET Blog", "https://devblogs.microsoft.com/dotnet/", ".NET Blog", "Performance write-ups and language news for every release.", False),
 "async-streams": ("article", "Generate and consume async streams", "https://learn.microsoft.com/en-us/dotnet/csharp/asynchronous-programming/generate-consume-asynchronous-stream", LEARN, "IAsyncEnumerable<T> and await foreach.", False),
 "ref-struct": ("article", "ref struct types (C# reference)", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/ref-struct", LEARN, "Stack-only types and their restrictions.", True),
 "struct-types": ("article", "Structure types (C# reference)", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/struct", LEARN, "readonly structs, in parameters and copying behaviour.", False),
 "lambdas": ("article", "Lambda expressions (C# reference)", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/lambda-expressions", LEARN, "Captures, static lambdas and natural types.", False),
 "stj-overview": ("article", "System.Text.Json overview", "https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/overview", LEARN, "The built-in JSON library, its defaults and options.", False),
 "select-collection": ("article", "Select a collection class", "https://learn.microsoft.com/en-us/dotnet/standard/collections/selecting-a-collection-class", LEARN, "Choosing the right collection for the access pattern.", False),
 "collections": ("article", "Collections and data structures", "https://learn.microsoft.com/en-us/dotnet/standard/collections/", LEARN, "Overview of the .NET collection types.", False),
 "dictionary": ("article", "Dictionary<TKey,TValue> class", "https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2", LEARN, "API reference, including hashing and thread-safety remarks.", False),
 "priorityqueue": ("article", "PriorityQueue<TElement,TPriority> class", "https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.priorityqueue-2", LEARN, "A min-heap for schedulers and top-k problems.", False),
 "threadsafe-collections": ("article", "Thread-safe collections", "https://learn.microsoft.com/en-us/dotnet/standard/collections/thread-safe/", LEARN, "The System.Collections.Concurrent types and their guarantees.", False),
 "concurrentdictionary": ("article", "ConcurrentDictionary<TKey,TValue> class", "https://learn.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentdictionary-2", LEARN, "API reference, including GetOrAdd factory behaviour.", False),
 "immutable": ("article", "System.Collections.Immutable namespace", "https://learn.microsoft.com/en-us/dotnet/api/system.collections.immutable", LEARN, "Immutable collections that are safe to share.", True),
 "frozen": ("article", "FrozenDictionary<TKey,TValue> class", "https://learn.microsoft.com/en-us/dotnet/api/system.collections.frozen.frozendictionary-2", LEARN, "Read-optimized dictionaries built once.", True),
 "linq-overview": ("article", "LINQ overview", "https://learn.microsoft.com/en-us/dotnet/csharp/linq/", LEARN, "Language-Integrated Query across objects, databases and XML.", False),
 "comparisons": ("article", "Comparisons and sorts within collections", "https://learn.microsoft.com/en-us/dotnet/standard/collections/comparisons-and-sorts-within-collections", LEARN, "IComparable, IComparer and equality in collections.", True),
 "caching-overview": ("article", "Caching overview in ASP.NET Core", "https://learn.microsoft.com/en-us/aspnet/core/performance/caching/overview", LEARN, "In-memory, distributed and output caching.", False),
 "distributed-caching": ("article", "Distributed caching in ASP.NET Core", "https://learn.microsoft.com/en-us/aspnet/core/performance/caching/distributed", LEARN, "IDistributedCache with Redis and SQL Server.", False),
 "hybridcache": ("article", "HybridCache library in ASP.NET Core", "https://learn.microsoft.com/en-us/aspnet/core/performance/caching/hybrid", LEARN, "Two-level caching with stampede protection.", True),
 "pg-isolation": ("article", "Transaction isolation", "https://www.postgresql.org/docs/current/transaction-iso.html", PG, "Isolation levels and the anomalies each prevents.", False),
 "pg-docs": ("link", "PostgreSQL documentation", "https://www.postgresql.org/docs/current/", PG, "The best single reference for PostgreSQL behaviour.", False),
 "pg-index-types": ("article", "Index types", "https://www.postgresql.org/docs/current/indexes-types.html", PG, "B-tree, hash, GiST, SP-GiST, GIN and BRIN.", False),
 "pg-indexes": ("article", "Indexes", "https://www.postgresql.org/docs/current/indexes.html", PG, "Multicolumn, partial and expression indexes.", False),
 "use-the-index-luke": ("link", "Use The Index, Luke!", "https://use-the-index-luke.com/", "Markus Winand", "A free guide to SQL indexing and performance.", False),
 "pg-explain": ("article", "Using EXPLAIN", "https://www.postgresql.org/docs/current/using-explain.html", PG, "Reading query plans and actual row counts.", False),
 "postgis-docs": ("link", "PostGIS documentation", "https://postgis.net/documentation/", "PostGIS", "Spatial types, functions and indexes.", True),
 "postgis-indexing": ("article", "PostGIS workshop: spatial indexing", "https://postgis.net/workshops/postgis-intro/indexing.html", "PostGIS", "How GiST indexes speed up spatial queries.", True),
 "pg-partitioning": ("article", "Table partitioning", "https://www.postgresql.org/docs/current/ddl-partitioning.html", PG, "Declarative range, list and hash partitioning.", False),
 "pg-rls": ("article", "Row security policies", "https://www.postgresql.org/docs/current/ddl-rowsecurity.html", PG, "Row-level security for tenant isolation.", False),
 "pg-locking": ("article", "Explicit locking", "https://www.postgresql.org/docs/current/explicit-locking.html", PG, "Row locks, table locks and advisory locks.", False),
 "pg-select": ("article", "SELECT (locking clause)", "https://www.postgresql.org/docs/current/sql-select.html", PG, "FOR UPDATE, NOWAIT and SKIP LOCKED.", False),
 "pg-mvcc": ("article", "Concurrency control (MVCC)", "https://www.postgresql.org/docs/current/mvcc.html", PG, "Snapshots and row versions.", False),
 "pg-vacuum": ("article", "Routine vacuuming", "https://www.postgresql.org/docs/current/routine-vacuuming.html", PG, "Reclaiming dead tuples and preventing bloat.", False),
 "ef-migrations": ("article", "Applying migrations (EF Core)", "https://learn.microsoft.com/en-us/ef/core/managing-schemas/migrations/applying", LEARN, "SQL scripts, bundles and why not to migrate at startup.", True),
 "parallel-change": ("article", "Parallel change", "https://martinfowler.com/bliki/ParallelChange.html", "Martin Fowler", "Expand and contract for backward-compatible changes.", True),
 "ef-execute": ("article", "ExecuteUpdate and ExecuteDelete", "https://learn.microsoft.com/en-us/ef/core/saving/execute-insert-update-delete", LEARN, "Set-based updates and deletes without loading entities.", True),
 "ef-perf": ("article", "Advanced performance topics (EF Core)", "https://learn.microsoft.com/en-us/ef/core/performance/advanced-performance-topics", LEARN, "Compiled queries, pooling and other EF Core performance techniques.", False),
 "npgsql-conn": ("article", "Npgsql connection string parameters", "https://www.npgsql.org/doc/connection-string-parameters.html", "Npgsql", "Pooling, timeouts and other connection settings.", True),
 "npgsql-ef": ("article", "Npgsql Entity Framework Core provider", "https://www.npgsql.org/efcore/", "Npgsql", "Using EF Core with PostgreSQL.", True),
 "owasp-api": ("article", "OWASP API Security Top 10 (2023)", "https://owasp.org/API-Security/editions/2023/en/0x11-t10/", OWASP, "The ten most critical API security risks.", False),
 "owasp-api-project": ("link", "OWASP API Security Project", "https://owasp.org/www-project-api-security/", OWASP, "The project behind the API Top 10.", False),
 "rfc6749": ("article", "The OAuth 2.0 Authorization Framework (RFC 6749)", "https://datatracker.ietf.org/doc/html/rfc6749", IETF, "The core OAuth 2.0 specification.", False),
 "rfc7636": ("article", "Proof Key for Code Exchange (RFC 7636)", "https://datatracker.ietf.org/doc/html/rfc7636", IETF, "PKCE for public clients.", False),
 "oidc": ("article", "OpenID Connect Core 1.0", "https://openid.net/specs/openid-connect-core-1_0.html", "OpenID Foundation", "Identity on top of OAuth 2.0.", False),
 "app-secrets": ("article", "Safe storage of app secrets in development", "https://learn.microsoft.com/en-us/aspnet/core/security/app-secrets", LEARN, "User secrets and keeping secrets out of source.", False),
 "data-protection": ("article", "ASP.NET Core Data Protection overview", "https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/introduction", LEARN, "Key management and encryption for app data.", False),
 "cors": ("article", "Enable Cross-Origin Requests (CORS)", "https://learn.microsoft.com/en-us/aspnet/core/security/cors", LEARN, "Configuring cross-origin policies.", False),
 "csrf": ("article", "Prevent Cross-Site Request Forgery (CSRF)", "https://learn.microsoft.com/en-us/aspnet/core/security/anti-request-forgery", LEARN, "Anti-forgery tokens and SameSite cookies.", False),
 "xss": ("article", "Prevent Cross-Site Scripting (XSS)", "https://learn.microsoft.com/en-us/aspnet/core/security/cross-site-scripting", LEARN, "Output encoding and content security policy.", False),
 "owasp-cheatsheets": ("link", "OWASP Cheat Sheet Series", "https://cheatsheetseries.owasp.org/", OWASP, "Short, practical security guidance.", False),
 "sqli-cheatsheet": ("article", "SQL Injection Prevention Cheat Sheet", "https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html", OWASP, "Parameterized queries and other defences.", False),
 "api-design": ("article", "Web API design best practices", "https://learn.microsoft.com/en-us/azure/architecture/best-practices/api-design", LEARN, "Resources, verbs, pagination and versioning.", False),
 "rfc9110": ("article", "HTTP Semantics (RFC 9110)", "https://datatracker.ietf.org/doc/html/rfc9110", IETF, "Methods, status codes and idempotency.", False),
 "rfc9457": ("article", "Problem Details for HTTP APIs (RFC 9457)", "https://datatracker.ietf.org/doc/html/rfc9457", IETF, "A standard error format for HTTP APIs.", False),
 "api-versioning": ("link", "ASP.NET API Versioning", "https://github.com/dotnet/aspnet-api-versioning", ".NET Foundation", "Versioning for ASP.NET Core APIs.", True),
 "openapi": ("article", "OpenAPI support in ASP.NET Core", "https://learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/overview", LEARN, "Generating OpenAPI documents from your API.", True),
 "fixedtimeequals": ("article", "CryptographicOperations.FixedTimeEquals", "https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.cryptographicoperations.fixedtimeequals", LEARN, "Constant-time comparison for signatures.", True),
 "grpc-comparison": ("article", "Compare gRPC services with HTTP APIs", "https://learn.microsoft.com/en-us/aspnet/core/grpc/comparison", LEARN, "When gRPC fits and when it doesn't.", True),
 "http3": ("article", "Use HTTP/3 with Kestrel", "https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/http3", LEARN, "QUIC and HTTP/3 support in ASP.NET Core.", True),
 "kafka-docs": ("link", "Apache Kafka documentation", "https://kafka.apache.org/documentation/", "Apache Kafka", "Topics, partitions, consumer groups and delivery semantics.", False),
 "confluent": ("article", "Confluent .NET client documentation", "https://docs.confluent.io/kafka-clients/dotnet/current/overview.html", "Confluent", "Producing and consuming Kafka messages from .NET.", True),
 "schema-registry": ("article", "Schema Registry overview", "https://docs.confluent.io/platform/current/schema-registry/index.html", "Confluent", "Schemas and compatibility rules for Kafka messages.", True),
 "messaging-patterns": ("article", "Messaging patterns", "https://learn.microsoft.com/en-us/azure/architecture/patterns/category/messaging", LEARN, "Queues, pub-sub and related cloud patterns.", True),
 "temporal": ("article", "Temporal .NET developer guide", "https://docs.temporal.io/develop/dotnet", "Temporal", "Durable workflows, activities and determinism rules in .NET.", True),
 "temporal-workflows": ("article", "Temporal workflows", "https://docs.temporal.io/workflows", "Temporal", "Workflow execution, replay and versioning.", True),
 "containerize": ("article", "Containerize a .NET app", "https://learn.microsoft.com/en-us/dotnet/core/docker/build-container", LEARN, "Building container images for .NET services.", False),
 "health-checks": ("article", "Health checks in ASP.NET Core", "https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks", LEARN, "Liveness and readiness probes.", False),
 "ci": ("article", ".NET CLI and continuous integration", "https://learn.microsoft.com/en-us/dotnet/devops/dotnet-cli-and-continuous-integration", LEARN, "Using the .NET CLI in CI pipelines.", True),
 "sre-slo": ("article", "Service level objectives", "https://sre.google/sre-book/service-level-objectives/", "Google SRE", "SLIs, SLOs and error budgets.", False),
 "queue-leveling": ("article", "Queue-Based Load Leveling pattern", "https://learn.microsoft.com/en-us/azure/architecture/patterns/queue-based-load-leveling", LEARN, "A queue as a buffer between bursty producers and steady consumers.", True),
 "strangler": ("article", "Strangler Fig pattern", "https://learn.microsoft.com/en-us/azure/architecture/patterns/strangler-fig", LEARN, "Incrementally replacing a legacy system.", False),
 "azure-patterns": ("link", "Azure Architecture Center: cloud design patterns", "https://learn.microsoft.com/en-us/azure/architecture/patterns/", LEARN, "One page per pattern, with when to use it and when not to.", False),
 "adr": ("link", "Architecture decision records", "https://adr.github.io/", "ADR GitHub organization", "Templates and tooling for recording decisions.", True),
}

M1, M2, M3, M4, M5 = "Modern C#", "Collections & Data Structures", "SQL, PostgreSQL & EF Core", "Security & API Design", "Messaging, Delivery & System Design"

Q = [
 ("What do primary constructors, required members and collection expressions give you?", [M1, "C# 12"], "medium",
  "Less boilerplate: primary-constructor parameters are captured state, required forces initialization, and [1, 2, 3] unifies collections.",
  ["Primary constructor parameters on a class become readonly fields automatically, so they can never be reassigned anywhere in the class body after construction.",
   "required members are checked at runtime by the JIT, which throws if a JSON payload omits them.",
   "Collection expressions work only with arrays; lists and spans still need the older initializer syntax."],
  "Primary constructors capture parameters without boilerplate fields; on a class the parameters are captured state, not readonly fields, so mutation surprises are possible. required forces callers to set a property at construction. Collection expressions ([1, 2, 3]) unify array, list and span initialization. Say which you would use in a domain model and which you would avoid.",
  ["cs12", "required", "lock-blog"]),
 ("How does pattern matching improve code, and what are its limits?", [M1, "Pattern matching"], "medium",
  "Switch expressions with property, relational and list patterns replace nested ifs and casts, but open hierarchies still need a default arm.",
  ["The compiler proves exhaustiveness for every class hierarchy, including open ones, so a default arm is never needed in a switch expression over any type.",
   "Pattern matching works only on constants and enums; property patterns need reflection at runtime.",
   "Patterns should replace all virtual methods, because polymorphism is slower and harder to read."],
  "is, switch expressions, property, relational, list and and/or/not patterns replace nested if and casts. The compiler checks exhaustiveness on closed sets, but not for open hierarchies, so a default arm still matters. Overuse can hide polymorphism that belongs in the type.",
  ["pattern-matching", "switch-expr"]),
 ("How do init, readonly and with support immutable design?", [M1, "Immutability"], "medium",
  "init allows assignment only during construction and with copies with changes, but the copy is shallow, so nested collections stay shared.",
  ["with performs a deep clone, so mutable collections inside a record are copied too.",
   "init properties can be reassigned at any time, while readonly ones are set only in the constructor.",
   "Immutable models remove all allocations, because changes are applied in place."],
  "init allows assignment only during construction. with makes a copy with changes and is shallow, so a mutable collection inside is still shared. Immutable models make concurrency and caching easier, at the cost of allocations on every change.",
  ["init", "with"]),
 ("How do generic constraints, static abstract members and generic math work?", [M1, "Generics"], "hard",
  "Constraints let the compiler allow operations on T, and static abstract interface members enable INumber<T> math without boxing.",
  ["Generic math relies on dynamic dispatch through reflection, so every numeric value passed through an INumber<T> method is boxed and unboxed on each operation.",
   "Constraints are only checked at runtime, so they can change freely without affecting a public API.",
   "Static abstract members can appear only on abstract classes, which is why INumber<T> is a class."],
  "Constraints (where T : struct, IComparable<T>) let the compiler allow operations on T. Static abstract interface members enable generic math (INumber<T>) without boxing or reflection. Know when a constraint beats a base class, and that constraints are part of your public contract.",
  ["constraints", "generic-math"]),
 ("What do reflection and expression trees cost, and how do you reduce it?", [M1, "Reflection"], "hard",
  "Reflection is slow per call and hurts trimming and AOT; cache metadata, compile delegates once, or move the work to source generators.",
  ["Reflection is as fast as a direct call after the first use, and it behaves exactly the same under trimming and Native AOT, so there is nothing to optimize there.",
   "Expression trees run faster than compiled code, so EF Core executes them directly instead of producing SQL.",
   "Call MethodInfo.Invoke more often, since the runtime caches each result per argument value."],
  "Reflection is slow per call and defeats trimming and Native AOT. Cache MethodInfo, compile delegates or expression trees once, or move the work to build time with source generators. Expression trees are code as data; EF Core uses them to produce SQL.",
  ["expression-trees", "reflection"]),
 ("What are source generators and why do they matter?", [M1, "Source generators"], "medium",
  "They add code at compile time instead of using runtime reflection, giving speed and AOT-friendliness, as in System.Text.Json and LoggerMessage.",
  ["They generate code at runtime the first time a type is used, which is why apps that rely on them usually start noticeably slower than reflection-based ones.",
   "They are a Visual Studio-only feature, so CI builds ignore them and fall back to reflection.",
   "They rewrite your source files on disk, so the generated changes must be committed."],
  "They run at compile time and add code, replacing runtime reflection. Benefits: speed, AOT and trimming friendliness, compile-time errors. Examples: System.Text.Json serializers, logging (LoggerMessage), regex. Trade-offs: harder to debug and they slow the build if poorly written.",
  ["source-gen", "stj-sourcegen", "dotnet-blog"]),
 ("What is IAsyncEnumerable<T>, and when do you use it?", [M1, "Async"], "medium",
  "An async stream consumed with await foreach, for items produced over time such as paged results, without loading everything first.",
  ["A collection that loads every item into memory first and then exposes them one by one asynchronously.",
   "It replaces Task<T> for single results, since awaiting one value through a stream is faster.",
   "Cancellation is impossible with async streams, so a slow consumer can't release the producer."],
  "Async streams let a consumer await foreach over items produced over time, such as paged API results or a database cursor, without loading everything. Pass a CancellationToken with [EnumeratorCancellation]. Remember that ASP.NET Core can stream it as JSON, and that a slow consumer holds the producer's resources open.",
  ["async-streams"]),
 ("What are ref struct, readonly struct, in parameters and ref returns for?", [M1, "Performance"], "hard",
  "Avoiding copies and allocations: readonly struct prevents defensive copies, in passes read-only by reference, and ref returns expose storage.",
  ["They move structs onto the heap, so values can be stored in class fields, boxed into object and captured across await boundaries without any restrictions.",
   "in parameters copy the argument twice for safety, so they belong on every method by default.",
   "ref struct types can be boxed and stored in collections like any other value type."],
  "They avoid copies and allocations. readonly struct stops defensive copies; in passes by reference read-only; ref returns hand back a reference into existing storage. A ref struct is stack-only, so no boxing, no fields in classes, no await across it. Use them only after measuring.",
  ["ref-struct", "struct-types"]),
 ("How do closures and lambdas allocate, and how do you avoid it?", [M1, "Performance"], "medium",
  "A capturing lambda allocates a closure and often a delegate; static lambdas forbid captures, and state can be passed as a parameter instead.",
  ["Lambdas never allocate, because the compiler inlines them into the caller.",
   "Only non-capturing lambdas allocate, while capturing ones reuse a cached delegate.",
   "static lambdas capture every local automatically, which avoids the closure object."],
  "A lambda that captures variables allocates a closure object, and a delegate each time unless cached. Capturing a loop variable in older code was a classic bug. Use static lambdas to forbid captures, pass state as a parameter, and avoid lambdas in hot paths.",
  ["lambdas"]),
 ("Should you use System.Text.Json or Newtonsoft.Json?", [M1, "Serialization"], "medium",
  "System.Text.Json is faster and stricter with source generation; Newtonsoft is more forgiving; silent mismatches at the boundary are the risk.",
  ["Newtonsoft.Json is always faster, because System.Text.Json falls back to reflection for every property of every object it serializes, even with source generation enabled.",
   "System.Text.Json ignores casing differences by default, so strict boundaries need no configuration.",
   "They behave identically, so switching between them never changes how payloads are read."],
  "STJ is faster, lower-allocation, strict by default and has source generation; Newtonsoft is more forgiving and has more features. Know custom converters, naming policies, polymorphism, case-insensitivity and the danger of silently ignoring unknown or missing properties at an API boundary.",
  ["stj-overview"]),

 ("How do you choose between an array, List<T>, LinkedList<T> and Queue<T>?", [M2, "Collections"], "easy",
  "Arrays and lists are contiguous and cache-friendly with fast indexing; LinkedList rarely wins; Queue and Stack serve FIFO and LIFO.",
  ["LinkedList is the best default, because inserting in the middle is O(1) and allocating a separate node per item keeps the elements close together in memory.",
   "List<T> appends cost O(n) every time, so growing data should always use a fixed array.",
   "Queue<T> offers O(1) random access by index, making it a better general-purpose list."],
  "Arrays and lists are contiguous: fast indexing, cache-friendly, appends amortized O(1), inserts in the middle O(n). LinkedList rarely wins in practice because of per-node allocation and poor locality. Set an initial capacity when you know the size. Queue and stack for FIFO and LIFO access.",
  ["select-collection", "collections"]),
 ("How does Dictionary<TKey,TValue> work, and what can go wrong?", [M2, "Collections"], "medium",
  "A hash table with O(1) average lookup; keys need a stable GetHashCode and Equals, and a key mutated after insertion becomes unreachable.",
  ["It keeps its keys in a balanced search tree, so every lookup is O(log n) and the key's GetHashCode is never called by the dictionary at all.",
   "It is safe for concurrent writes from many threads, because each operation takes an internal lock.",
   "Mutating a key after insertion is fine, since the dictionary rehashes keys on every lookup."],
  "A hash table with buckets: lookup is O(1) on average, O(n) if many keys collide. Keys need a correct, stable GetHashCode and Equals; a key mutated after insertion becomes unreachable. It is not thread-safe for concurrent writes. Mention resize cost and custom comparers (such as ordinal-ignore-case).",
  ["dictionary"]),
 ("When do you use HashSet, SortedDictionary, SortedSet or PriorityQueue?", [M2, "Collections"], "medium",
  "HashSet for membership and de-duplication, sorted collections for ordered iteration and ranges, and PriorityQueue for schedulers and top-k.",
  ["PriorityQueue is stable for equal priorities, so ties come out in insertion order.",
   "SortedSet gives O(1) lookups, which makes it faster than HashSet for membership.",
   "HashSet keeps insertion order, so it suits ordered iteration and range queries."],
  "HashSet for fast membership and de-duplication. Sorted collections give ordered iteration and range queries at O(log n). PriorityQueue<TElement,TPriority> gives the next-highest-priority item, ideal for schedulers and top-k problems. Note it is not stable for equal priorities.",
  ["priorityqueue", "select-collection"]),
 ("What are the traps of ConcurrentDictionary?", [M2, "Concurrency"], "hard",
  "Single operations are thread-safe but compound logic isn't, and the GetOrAdd factory may run more than once, so keep it free of side effects.",
  ["GetOrAdd guarantees that its value factory runs exactly once per key, even under heavy contention, so expensive or side-effecting factories are completely safe.",
   "Count and enumeration are cheap, consistent snapshots that can be called freely in hot paths.",
   "Every check-then-act sequence is atomic, because the whole dictionary is locked during each call."],
  "Single operations are thread-safe, but compound logic is not. The factory delegate in GetOrAdd can run more than once and its result be discarded, so it must be side-effect free. Use Lazy<T> values when creation is expensive. Count and enumeration are not cheap snapshots.",
  ["threadsafe-collections", "concurrentdictionary"]),
 ("What are immutable and frozen collections for?", [M2, "Collections"], "medium",
  "Immutable collections make thread-safe sharing trivial, while frozen ones are built once and optimized for very fast reads of fixed data.",
  ["FrozenDictionary is optimized for frequent writes, which makes it the natural choice for caches and counters that change on every single incoming request.",
   "Immutable collections modify themselves in place, which is why they are safe to share across threads.",
   "Frozen collections are cheaper to create than a normal Dictionary, so build them on every call."],
  "ImmutableArray and friends make safe sharing across threads trivial; updates return new instances. FrozenDictionary and FrozenSet are built once and optimized for very fast reads, which suits configuration and lookup tables that never change. Creation is slower than a normal dictionary.",
  ["immutable", "frozen"]),
 ("What should a method accept and return: List<T>, IEnumerable<T> or IReadOnlyList<T>?", [M2, "API design"], "medium",
  "Accept the most general type you need and return a useful read-only type such as IReadOnlyList<T>, not a mutable list or a deferred query.",
  ["Accept List<T> so that callers must materialize their data first, and return IEnumerable<T> so the cost of any deferred query stays hidden from the caller.",
   "Always return a mutable List<T> from properties, so callers can add to the object's internal state.",
   "Return IEnumerable<T> everywhere, since callers can always get Count and index into it cheaply."],
  "Accept the most general type you need (often IEnumerable<T>); return the most useful read-only type (IReadOnlyList<T>) so callers know the count and can index it. Returning IEnumerable<T> from a deferred query hides cost; returning a mutable List<T> from a property lets callers corrupt state.",
  ["collections"]),
 ("What are common LINQ performance mistakes?", [M2, "LINQ"], "medium",
  "Count() > 0 instead of Any(), enumerating twice, Contains on a list inside a loop, and materializing a provider query before filtering.",
  ["Using Any() instead of Count() > 0, since Any() reads the whole sequence.",
   "Calling ToList() before Where() on a provider, which moves filtering into the database.",
   "Using a HashSet for lookups inside loops, which makes Contains O(n²)."],
  "Count() > 0 instead of Any(); enumerating twice; OrderBy inside a loop; Contains on a list inside a loop (O(n²), use a HashSet); LINQ over huge in-memory data in hot paths. Also know that ToList before Where on a query provider moves filtering to memory.",
  ["linq-overview"]),
 ("How do IComparable, IComparer and sort stability work?", [M2, "Collections"], "medium",
  "IComparable gives a natural order and IComparer an alternative one; List.Sort is unstable, OrderBy is stable, and comparers must be consistent.",
  ["List.Sort is stable and OrderBy is unstable, so equal elements keep their original relative order only when you sort a list in place with List.Sort.",
   "A comparer may be inconsistent, because sorting algorithms detect and correct contradictions.",
   "IComparer can only be implemented by the element type itself, never by a separate class."],
  "IComparable<T> gives a type its natural order; IComparer<T> gives an alternative order. List.Sort is unstable; OrderBy is stable. A comparer must be consistent (transitive, antisymmetric) or sorting misbehaves. Compare strings ordinally or with an explicit culture.",
  ["comparisons"]),
 ("How do you cache in .NET, and what is a cache stampede?", [M2, "Caching"], "hard",
  "Use in-memory or distributed caching with expirations; a stampede is many requests rebuilding an expired hot key at once, fixed by coalescing.",
  ["A stampede happens when the cache fills up and evicts every entry at once, and it is prevented by never setting an expiration on any cached key.",
   "Distributed caches are for a single instance, while in-memory caches are shared across servers.",
   "Giving every key the same expiration prevents stampedes, because all keys refresh together."],
  "In-memory cache for one instance, distributed cache (Redis) for many. Set expirations and size limits. A stampede happens when a popular key expires and many requests rebuild it at once; prevent it with per-key locking, request coalescing or HybridCache, plus jittered expirations. Know what is safe to cache and how to invalidate.",
  ["caching-overview", "distributed-caching", "hybridcache"]),
 ("How would you find the top 10 most frequent items in a very large stream?", [M2, "Algorithms"], "hard",
  "Count with a dictionary if keys fit in memory and keep a size-10 min-heap; otherwise use approximate sketches, or partition by hash and merge.",
  ["Sort the whole stream in memory and take the first ten items, which is O(n) for any input size because sorting large inputs is linear in .NET.",
   "Keep a max-heap of every distinct item, since a heap of size 10 can't track frequencies.",
   "Use a single List<T> and call Contains for each item, which keeps the work linear."],
  "Count with a dictionary if the distinct keys fit in memory, then keep a min-heap of size 10 (O(n log 10)) instead of sorting everything. If they do not fit, discuss approximate structures (count-min sketch), partitioning by hash and merging, or pushing the work into the database. State complexity out loud.",
  ["priorityqueue"]),

 ("What do transaction isolation levels prevent, and how does PostgreSQL behave?", [M3, "PostgreSQL"], "hard",
  "They guard against dirty, non-repeatable and phantom reads and write skew; Postgres defaults to read committed, and serializable may abort, so retry.",
  ["PostgreSQL defaults to serializable isolation, which takes table-level locks so that concurrent transactions never conflict and never need to be retried.",
   "Read committed prevents write skew and phantom reads, so higher levels add nothing in PostgreSQL.",
   "Repeatable read in PostgreSQL re-reads the latest committed data on every statement."],
  "Dirty read, non-repeatable read, phantom read, write skew. PostgreSQL's default is read committed; repeatable read gives a stable snapshot; serializable detects dangerous patterns and aborts one transaction, so the application must retry. Higher isolation costs retries, not locks.",
  ["pg-isolation", "pg-docs"]),
 ("Which index types does PostgreSQL offer, and when do you use each?", [M3, "PostgreSQL"], "medium",
  "B-tree for equality and ranges, GIN for arrays, JSONB and full text, GiST for geometry and ranges, BRIN for huge naturally ordered tables.",
  ["GIN is the default for equality and range queries, and B-tree is reserved for full-text search.",
   "BRIN suits small, randomly ordered tables, because it stores an entry for every single row.",
   "Indexes add no cost to writes, so every column should get its own index."],
  "B-tree for equality and ranges (the default); GIN for arrays, JSONB and full text; GiST for geometry and ranges; BRIN for huge append-only, naturally ordered tables. Partial indexes cover a subset; multicolumn index order matters; every index slows writes.",
  ["pg-index-types", "pg-indexes", "use-the-index-luke"]),
 ("How do you find out why a PostgreSQL query is slow?", [M3, "PostgreSQL"], "medium",
  "Run EXPLAIN (ANALYZE, BUFFERS), compare estimated and actual rows, look for big sequential scans and spilled sorts, then fix and re-measure.",
  ["Run plain EXPLAIN without ANALYZE, because the actual row counts and timings are irrelevant to the planner and only the estimated costs matter for tuning.",
   "Index every column the query touches, then skip measuring, since indexes always help.",
   "Restart the database to reset statistics, because stale statistics make queries faster."],
  "Run EXPLAIN (ANALYZE, BUFFERS). Compare estimated and actual rows (bad estimates mean stale statistics), look for sequential scans on big tables, nested loops over large sets, and sorts spilling to disk. Fix with an index, a rewrite or fresh statistics, then re-measure.",
  ["pg-explain"]),
 ("How does PostGIS index and query spatial data?", [M3, "PostGIS"], "hard",
  "A GiST index makes bounding-box searches fast and functions like ST_DWithin use it; know geometry versus geography and SRIDs.",
  ["PostGIS stores coordinates in B-tree indexes on latitude, so wrapping the column in a function still lets the planner use that index for every spatial query.",
   "Geometry and geography are identical, and distances measured in degrees are accurate everywhere.",
   "Spatial queries can't use indexes at all, so every search scans the full table."],
  "A GiST index over geometry or geography makes bounding-box searches fast; functions such as ST_DWithin use it, while wrapping the column in a function can defeat it. Know geometry versus geography (planar versus spherical), SRIDs, and why distance in degrees is wrong.",
  ["postgis-docs", "postgis-indexing"]),
 ("How do you partition a table and isolate tenants in PostgreSQL?", [M3, "PostgreSQL"], "hard",
  "Partition by range or list/hash for pruning and cheap drops, and add row-level security as a second line of tenant isolation.",
  ["Partitioning the table by tenant replaces the need for any isolation checks, because a query can never read rows from a partition other than its own.",
   "Row-level security returns every row when the tenant setting is missing, which is the safe default.",
   "The partition key is easy to change later, so it can be chosen arbitrarily at first."],
  "Declarative partitioning by range (time) or list/hash (tenant) speeds pruning and makes dropping old data instant. Row-level security enforces tenant isolation in the database as a second line of defence; set the tenant per connection or transaction and test that a missing setting returns nothing. Partition-key choice is hard to change later.",
  ["pg-partitioning", "pg-rls"]),
 ("How do SELECT ... FOR UPDATE SKIP LOCKED and advisory locks help?", [M3, "PostgreSQL"], "hard",
  "SKIP LOCKED lets workers claim different queue or outbox rows without blocking, and advisory locks give application-level mutual exclusion.",
  ["SKIP LOCKED makes every worker wait on the same locked row until it is released, which guarantees that a queue table is processed in strict order.",
   "Advisory locks lock the whole table, so they are best held for hours to keep a single leader.",
   "Long transactions holding these locks help vacuum by freezing rows early."],
  "SKIP LOCKED lets many workers claim different rows from a queue or outbox table without blocking each other. Advisory locks give application-level mutual exclusion (such as one leader). Both need short transactions; a long-held lock blocks vacuum and other writers.",
  ["pg-locking", "pg-select"]),
 ("What is MVCC, and why do vacuum and bloat matter?", [M3, "PostgreSQL"], "hard",
  "Updates create new row versions so readers don't block writers; dead versions pile up until vacuum runs, and long transactions block cleanup.",
  ["MVCC updates rows in place, so dead tuples never pile up and vacuum is unnecessary.",
   "Idle-in-transaction sessions speed up vacuum, because they hold clean snapshots.",
   "Under MVCC readers block writers, so long reports must run at night."],
  "Updates create new row versions; readers see a snapshot and do not block writers. Dead versions pile up until vacuum reclaims them. Long-running transactions and idle-in-transaction sessions stop cleanup, causing bloat and slowdowns. Monitor dead tuples and autovacuum.",
  ["pg-mvcc", "pg-vacuum"]),
 ("How do you run EF Core migrations safely in production?", [M3, "EF Core"], "hard",
  "Review generated SQL scripts, avoid auto-migrating from many instances at once, and use expand-and-contract across releases.",
  ["Call Database.Migrate() at startup in every instance, so all replicas race to apply the schema change and whichever finishes first wins the deployment.",
   "Rename columns in a single release, since old and new code never run at the same time.",
   "Drop the old column in the same deployment that adds the new one, to keep the schema clean."],
  "Generate SQL scripts and review them; do not auto-migrate at app start with many instances. Use expand-and-contract: add the new column, deploy code that writes both, backfill, switch reads, then drop the old column in a later release. Avoid long table locks and know your rollback.",
  ["ef-migrations", "parallel-change"]),
 ("How do you make EF Core fast for bulk work and hot paths?", [M3, "EF Core"], "hard",
  "Use ExecuteUpdate and ExecuteDelete, compiled queries, AsNoTracking projections and split queries, and raw SQL for the hottest paths.",
  ["Load every entity, change it in a loop and call SaveChanges after each one, because per-row round trips are what make bulk updates in EF Core fast and safe.",
   "Always keep tracking on for reads, because AsNoTracking makes projections slower.",
   "Avoid split queries, since cartesian explosions occur only with raw SQL."],
  "ExecuteUpdate and ExecuteDelete run set-based SQL without loading entities. Use compiled queries, AsNoTracking, projections to DTOs, split queries to avoid cartesian explosions, and batching. Drop to Dapper or raw SQL for the few hot or complex queries, and explain why.",
  ["ef-execute", "ef-perf"]),
 ("How does connection pooling work, and how do you get pool exhaustion?", [M3, "PostgreSQL"], "medium",
  "The driver reuses connections up to a maximum; leaks, long transactions and slow queries exhaust it, so size pools against the server's limit.",
  ["Every request opens a brand-new physical connection to the database, so the configured pool size has no measurable effect on the service's throughput.",
   "Fix exhaustion by raising each instance's pool size, regardless of the database's connection limit.",
   "Undisposed connections return to the pool automatically on the next garbage collection."],
  "The driver reuses open connections up to a maximum; each request holds one while it runs. Leaks (an undisposed connection), long transactions and slow queries exhaust the pool, so requests wait and time out. Size pools against the database's connection limit across all instances, and consider PgBouncer for many clients.",
  ["npgsql-conn", "npgsql-ef"]),

 ("What are the biggest API security risks?", [M4, "Security"], "medium",
  "Broken object-level authorization tops OWASP's API list, alongside broken authentication, excessive data exposure and missing rate limits.",
  ["Slow response times top the OWASP API list, ahead of authorization flaws.",
   "Returning full entities is safest, since clients can ignore fields they shouldn't see.",
   "Once a user is authenticated, object-level checks are unnecessary because ids are hard to guess."],
  "Broken object-level authorization (a caller reads another tenant's record by changing an id) tops the OWASP API list. Also broken authentication, excessive data exposure, missing rate limits, and mass assignment. Mitigate with per-object authorization checks, DTOs instead of entities, and tests that try cross-tenant access.",
  ["owasp-api", "owasp-api-project"]),
 ("What are OAuth 2.0 and OpenID Connect, and which flow fits which client?", [M4, "Security"], "hard",
  "OAuth 2.0 delegates authorization and OIDC adds identity; apps use authorization code with PKCE, and services use client credentials.",
  ["OpenID Connect handles authorization while OAuth 2.0 proves identity, and browser-based apps should keep using the implicit flow because it needs no back end.",
   "Service-to-service calls should use authorization code with PKCE, because no user is present.",
   "ID tokens should be sent to APIs as access tokens, since they contain the user's scopes."],
  "OAuth 2.0 delegates authorization; OIDC adds identity on top. Browser or mobile apps use authorization code with PKCE; service-to-service uses client credentials. Know access versus ID versus refresh tokens, scopes, and why the implicit flow is discouraged.",
  ["rfc6749", "rfc7636", "oidc"]),
 ("How do you manage secrets and encryption keys in a .NET service?", [M4, "Security"], "medium",
  "Keep them out of source and images: use a secret store with managed identity, user-secrets locally, rotation, and shared Data Protection keys.",
  ["Store secrets in appsettings.json in the repository, because the build pipeline encrypts configuration files automatically before they reach any environment.",
   "Bake secrets into the container image, so every instance has them without extra configuration.",
   "Keep Data Protection keys in each instance's memory, since every instance decrypts only its own data."],
  "Never in source control or images. Use a secret store (Azure Key Vault or similar) with managed identity, user-secrets locally, and rotation. The Data Protection API handles app-level encryption keys, which need shared persistent storage across instances.",
  ["app-secrets", "data-protection"]),
 ("What are CORS, CSRF and XSS, and what stops each?", [M4, "Security"], "medium",
  "CORS relaxes cross-origin reads and isn't authentication; CSRF is stopped by anti-forgery tokens or SameSite; XSS by output encoding and a CSP.",
  ["CORS is an authentication mechanism that stops attackers from calling your API with stolen tokens, so enabling it correctly protects every endpoint.",
   "CSRF mostly affects bearer-token APIs, so anti-forgery tokens are mandatory on every JSON endpoint.",
   "XSS is prevented by allowing CORS from all origins, which stops injected scripts from running."],
  "CORS is a browser rule for cross-origin reads, relaxed by server headers; it is not authentication. CSRF tricks a browser into sending cookies to your site; stop it with anti-forgery tokens or SameSite cookies (not needed for bearer-token APIs). XSS injects script into pages; stop it with output encoding and a Content-Security-Policy.",
  ["cors", "csrf", "xss", "owasp-cheatsheets"]),
 ("How do you prevent SQL injection and mass assignment?", [M4, "Security"], "medium",
  "Parameterize every query and bind requests to input DTOs with only the allowed fields, so clients can't set IsAdmin or TenantId.",
  ["Escape the quotes in user input with string.Replace and then build the SQL by concatenation, which is just as safe as parameters and keeps the query readable.",
   "Bind request bodies directly to entities, because EF Core ignores fields clients shouldn't set.",
   "SQL injection only affects stored procedures, so inline queries are safe without parameters."],
  "Parameterize every query (EF Core and Dapper do so by default; string-built SQL does not). Never bind request bodies straight to entities: use input DTOs with only the allowed fields, so a client cannot set IsAdmin or TenantId. Validate at the boundary and encode at output.",
  ["sqli-cheatsheet"]),
 ("What makes a REST API well designed?", [M4, "API design"], "medium",
  "Resource nouns, correct verbs and status codes, respected idempotency, 201 with Location, and consistent ProblemDetails errors.",
  ["Verbs in every URL, POST for every operation, and 200 OK with an error flag on failure.",
   "POST is idempotent and PUT is not, so retries should always use POST.",
   "Expose database entities directly, so the API mirrors the internal model exactly."],
  "Nouns for resources, correct verbs and status codes, safe and idempotent methods respected (GET, PUT, DELETE idempotent; POST not). Know PUT versus PATCH, 201 with Location, 409 versus 422, consistent errors (ProblemDetails) and no leaking of internal models.",
  ["api-design", "rfc9110", "rfc9457"]),
 ("How do you version a public API without breaking partners?", [M4, "API design"], "hard",
  "Keep changes additive, version in the URL or a header, deprecate on a published timeline, and diff the OpenAPI document in CI.",
  ["Renaming a field is a non-breaking change, as long as the new field keeps the same type, because partners' JSON parsers match fields by type and position.",
   "Remove old versions as soon as a new one ships, so partners are pushed to upgrade quickly.",
   "Changing a field's meaning while keeping its name and type is always backward compatible."],
  "Additive changes are compatible; removing or renaming fields, changing types or semantics is breaking. Version in the URL or a header, support old versions on a published deprecation timeline, and catch breaks automatically by diffing the OpenAPI document in CI.",
  ["api-versioning", "openapi"]),
 ("How do you paginate, filter and cache API responses?", [M4, "API design"], "medium",
  "Prefer cursor (keyset) pagination for large changing data, cap the page size, and use ETags and Cache-Control for conditional caching.",
  ["Offset pagination stays stable and fast on huge tables, so cursors aren't needed.",
   "Let clients request unlimited page sizes, so they can fetch everything in one call.",
   "ETags force a full response every time, so they should be avoided on GET requests."],
  "Offset pagination is simple but slow and unstable on large or changing data; cursor (keyset) pagination is stable and fast. Cap page size. Use ETags with If-None-Match for conditional GETs, and Cache-Control for what is safe to cache.",
  ["api-design"]),
 ("How do you design webhooks to be safe and reliable?", [M4, "Integration"], "hard",
  "Sign payloads with HMAC plus a timestamp, deliver at-least-once with retries and event ids, and expose delivery logs and manual replay.",
  ["Send each webhook exactly once with no retries, and verify the signature with an ordinary string equality check, since timing differences are too small to exploit.",
   "Skip signatures, since only the receiver knows the webhook URL and it can never leak.",
   "Process the event fully before responding, however long it takes, to guarantee ordering."],
  "Sign each payload (HMAC with a shared secret, compared in constant time) and include a timestamp to stop replays. Deliver at-least-once with retries and backoff, include an event id so receivers can de-duplicate, respond fast and process async, and expose delivery logs and a manual replay.",
  ["fixedtimeequals"]),
 ("When do you choose REST, gRPC or GraphQL, and what do HTTP/2 and HTTP/3 change?", [M4, "API design"], "hard",
  "REST for public cache-friendly APIs, gRPC for internal contracts, GraphQL for flexible queries; HTTP/2 multiplexes and HTTP/3 runs on QUIC.",
  ["gRPC is the best fit for public browser-facing APIs, because its binary protocol is the most cache-friendly option and every browser supports it natively.",
   "GraphQL makes HTTP caching and query-cost control easier than REST does.",
   "HTTP/3 runs over TCP, which adds the head-of-line blocking that HTTP/2 avoids."],
  "REST for public, cache-friendly APIs; gRPC for efficient internal service calls with contracts; GraphQL when clients need flexible queries, at the cost of caching and query-cost control. HTTP/2 multiplexes requests on one connection; HTTP/3 runs over QUIC and avoids head-of-line blocking on lossy networks.",
  ["grpc-comparison", "http3"]),

 ("How do Kafka partitions, consumer groups and offsets work?", [M5, "Kafka"], "hard",
  "Order holds only within a partition, each partition goes to one consumer in a group, and committing after processing gives at-least-once.",
  ["Kafka orders messages across all partitions of a topic, and any number of consumers in one group can read the same partition in parallel to scale out.",
   "Committing offsets before processing gives at-least-once delivery, since nothing can be skipped.",
   "Rebalances never pause consumption, so handler speed has no effect on group stability."],
  "A topic is split into partitions; order holds only within one. Each partition is read by one consumer in a group, so partitions cap parallelism. Offsets record progress; committing after processing gives at-least-once. A rebalance pauses consumption, so keep handlers fast and use static membership where it helps.",
  ["kafka-docs", "confluent"]),
 ("How do you handle poison messages and schema changes in Kafka?", [M5, "Kafka"], "hard",
  "Retry a bounded number of times, then dead-letter with error context, and use a schema registry with compatibility rules.",
  ["Retry a poison message forever, blocking its partition until someone manually fixes the payload, so that no message is ever processed out of order.",
   "Reuse a removed field's name for a new meaning, since the schema registry tracks it.",
   "Make every new field required, so old consumers fail fast on new messages."],
  "Retry a bounded number of times, then send the message to a dead-letter topic with error context and alert. Use a schema registry with compatibility rules (backward, forward, full) so producers cannot break consumers; make fields optional and never reuse a field's meaning.",
  ["schema-registry"]),
 ("How do you choose between a message queue, an event stream and a database table?", [M5, "Messaging"], "medium",
  "Queues for task distribution with acknowledgements, streams for replayable ordered logs, and a SKIP LOCKED table for low-volume work.",
  ["Kafka is always right, since queues and tables can't distribute work.",
   "Queues replay long-term history to many readers, which streams can't do.",
   "A table can't serve as a queue, because rows can't be claimed concurrently."],
  "Queues (Service Bus, RabbitMQ) suit task distribution with per-message acknowledgement. Streams (Kafka) suit replayable, ordered event logs with many readers. A table with SKIP LOCKED is enough for low-volume work and avoids a new dependency. Pick by replay, ordering, throughput and operations cost.",
  ["messaging-patterns"]),
 ("What are Temporal's determinism rules, and why do they exist?", [M5, "Temporal"], "hard",
  "Workflows are replayed from history, so they must decide identically: no randomness, wall-clock time or direct I/O; side effects go in activities.",
  ["Workflow code runs exactly once and is never replayed, so generating random numbers, reading the clock and making direct HTTP calls inside it are all perfectly safe.",
   "Activities must be deterministic, while workflow code may perform any I/O it needs.",
   "Workflow code can change freely, because running executions always restart from the start."],
  "Workflow code is replayed from history after a crash, so it must make the same decisions each time: no random numbers, wall-clock time, direct I/O or non-deterministic iteration inside a workflow. Side effects belong in activities; use the workflow APIs for time and timers. Changing workflow code needs versioning for running executions.",
  ["temporal", "temporal-workflows"]),
 ("How do you containerize and deploy a .NET service well?", [M5, "Delivery"], "medium",
  "Multi-stage builds, a small runtime image, a non-root user, liveness and readiness probes, config from the environment and graceful shutdown.",
  ["Use the full SDK image as the runtime image and run the process as root, so compilers and debugging tools are always available inside production containers.",
   "Liveness and readiness are interchangeable, so one endpoint can check the database for both.",
   "Ship migrations that break the old version, since rolling deploys stop old instances first."],
  "Multi-stage Dockerfile, a small runtime image, non-root user, health probes (liveness versus readiness), config from environment, graceful shutdown on SIGTERM. Deploy with rolling or blue-green releases, and keep migrations compatible with the old and new version running together.",
  ["containerize", "health-checks"]),
 ("What belongs in a CI/CD pipeline for a back-end service?", [M5, "Delivery"], "medium",
  "Build, unit and Testcontainers integration tests, scanning, an OpenAPI breaking-change check, then one artifact promoted through environments.",
  ["Rebuild the artifact separately for every environment, so that staging and production each get a fresh build that includes the latest dependency versions.",
   "Skip integration tests in CI, since staging will catch the same problems later anyway.",
   "Deploy to production first, then smoke test in staging to save time."],
  "Build, unit and integration tests (Testcontainers), static analysis and vulnerability scanning, OpenAPI breaking-change check, container build, deploy to staging, smoke tests, then gated promotion. Keep it fast, and make the same artifact move through every environment.",
  ["ci"]),
 ("What are SLIs, SLOs and error budgets, and how do you use them?", [M5, "Reliability"], "medium",
  "An SLI is a measurement, an SLO is its target, and the error budget is the allowed shortfall; alert on burn rate rather than single errors.",
  ["An SLO is the measurement, and an SLI is the contract with penalties.",
   "Error budgets must never be spent, so releases stop at the first error.",
   "Alert on each failed request, because burn rates hide real problems."],
  "An SLI is a measurement (such as the share of requests under 300 ms); an SLO is the target for it; the error budget is the allowed shortfall. Alert on budget burn rate rather than single errors, and spend the budget deliberately on releases. Pick SLOs users actually feel.",
  ["sre-slo"]),
 ("How would you design a system to send a million emails or SMS messages reliably?", [M5, "System design"], "hard",
  "Persist the job, fan out batches through a queue, rate limit per provider, send idempotently, and track per-recipient state and webhooks.",
  ["Send every message from one web request in a tight loop and retry each failure immediately, since providers handle any volume and dedupe repeated sends for you.",
   "Skip per-recipient state, because providers guarantee delivery and never send bounces.",
   "Use one provider with no rate limiting, because providers accept unlimited traffic."],
  "Clarify scale and deadlines. Accept the job, persist it, fan out in batches through a queue, rate limit per provider, make each send idempotent, track state per recipient, handle provider webhooks and bounces, and expose progress. Discuss backpressure, retries, cost and what to do when a provider is down.",
  ["queue-leveling"]),
 ("How do you migrate a legacy system with no downtime?", [M5, "Migration"], "hard",
  "Use the strangler fig: put a facade in front, move one capability at a time, run both in parallel and compare, then retire the old path.",
  ["Rewrite the entire system in one go and switch over during a single weekend cutover, skipping any parallel run so the team can focus on the new code.",
   "Turn off the legacy system first, then build the replacement from its database.",
   "Copy the old code into a new repository, which counts as a migration without risk."],
  "Strangler fig: put a facade in front, move one capability at a time to the new system, run both in parallel, compare results, then retire the old path. Use dual reads or shadow traffic to build confidence, and always keep a rollback plan.",
  ["strangler", "azure-patterns"]),
 ("How should you answer \"tell me about a hard decision you made with incomplete information\"?", [M5, "Behavioural"], "medium",
  "Tell a short story: the context, options and costs, how you reduced uncertainty, who you involved, the decision, the outcome and lessons.",
  ["Describe only the final technology you picked and why it was objectively correct, leaving out the alternatives you rejected and what actually happened afterwards.",
   "Explain that you never decide without full information, and wait until everything is known.",
   "Focus on who made the mistake, rather than on what you learned or would change."],
  "Use a short story: the context, the options and their costs, how you reduced uncertainty (a spike, a measurement), who you involved, what you decided and why, what happened, and what you would change. Staff-level answers show influence beyond your own code and honesty about being wrong.",
  ["adr"]),
]

assert len(Q) == 50, len(Q)
build("50 more .NET interview questions (51 to 100)", M, Q, sys.argv[1])
