"""Generates apps/api/seeds/dotnet-interview.json from the 50-question study guide."""
import json, os, sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))  # tools/question-banks
from tag_map import mapped

LEARN, BLOG, CLEARY, MSIO = "Microsoft Learn", ".NET Blog", "Stephen Cleary", "microservices.io"
U = " Link not verified by the study guide; if it doesn't open, search for its title."

# key: (type, title, url, author, description, unverified)
M = {
 "types": ("article", "The C# type system", "https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/types/", LEARN, "Value types, reference types and how the C# type system fits together.", False),
 "structs-spec": ("article", "Structs (C# language specification)", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/structs", LEARN, "The formal rules for struct semantics, copying and default values.", False),
 "records": ("article", "Records (C# reference)", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/record", LEARN, "Record classes and record structs: value equality, with-expressions, immutability.", True),
 "boxing": ("article", "Boxing and unboxing", "https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/types/boxing-and-unboxing", LEARN, "What boxing allocates and how to avoid it.", False),
 "conversions": ("article", "Type conversions, casting and boxing", "https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/types/conversions", LEARN, "Implicit and explicit conversions, casts and boxing.", False),
 "nrt": ("article", "Nullable reference types", "https://learn.microsoft.com/en-us/dotnet/csharp/nullable-references", LEARN, "How nullable annotations and warnings work, and their limits.", True),
 "nullable-value": ("article", "Nullable value types", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-value-types", LEARN, "Nullable<T>, lifted operators and HasValue.", False),
 "linq-intro": ("article", "Introduction to LINQ queries", "https://learn.microsoft.com/en-us/dotnet/csharp/linq/get-started/introduction-to-linq-queries", LEARN, "Query anatomy and deferred execution.", False),
 "linq-overview": ("article", "LINQ overview", "https://learn.microsoft.com/en-us/dotnet/csharp/linq/", LEARN, "Language-Integrated Query across objects, databases and XML.", False),
 "iqueryable": ("article", "IQueryable interface", "https://learn.microsoft.com/en-us/dotnet/api/system.linq.iqueryable", LEARN, "API reference: expression trees and query providers.", True),
 "delegates": ("article", "Delegates overview", "https://learn.microsoft.com/en-us/dotnet/csharp/delegates-overview", LEARN, "Delegates, Func and Action, multicast invocation.", True),
 "events": ("article", "Events overview", "https://learn.microsoft.com/en-us/dotnet/csharp/events-overview", LEARN, "Declaring, raising and subscribing to events.", True),
 "variance-cs": ("article", "Covariance and contravariance (C#)", "https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/covariance-contravariance/", LEARN, "in/out variance on interfaces and delegates, and array covariance.", False),
 "variance-generics": ("article", "Covariance and contravariance in generics", "https://learn.microsoft.com/en-us/dotnet/standard/generics/covariance-and-contravariance", LEARN, "Variant generic interfaces and delegates in .NET.", False),
 "string-ops": ("article", "String operations: matching, performance and span-based search", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/string-operations", LEARN, "Immutability, comparisons and allocation-free string handling.", False),
 "value-equality": ("article", "How to define value equality for a type", "https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/how-to-define-value-equality-for-a-type", LEARN, "Implementing Equals, GetHashCode, == and IEquatable<T> correctly.", False),
 "equality-comparisons": ("article", "Equality comparisons", "https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/equality-comparisons", LEARN, "Reference equality versus value equality in C#.", False),
 "pattern-matching": ("article", "Pattern matching overview", "https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/patterns/pattern-matching", LEARN, "is, switch expressions and property patterns — a frequent follow-up question.", False),
 "async-faq": ("article", "Async/Await FAQ", "https://devblogs.microsoft.com/dotnet/asyncawait-faq/", BLOG, "What the compiler and runtime actually do for async methods.", False),
 "tap-consuming": ("article", "Consuming the task-based asynchronous pattern", "https://learn.microsoft.com/en-us/dotnet/standard/asynchronous-programming-patterns/consuming-the-task-based-asynchronous-pattern", LEARN, "Awaiting tasks, continuations, combinators and exceptions.", False),
 "configureawait": ("article", "ConfigureAwait FAQ", "https://devblogs.microsoft.com/dotnet/configureawait-faq/", BLOG, "Stephen Toub on synchronization contexts and when ConfigureAwait(false) matters.", False),
 "valuetask": ("article", "Understanding the whys, whats and whens of ValueTask", "https://devblogs.microsoft.com/dotnet/understanding-the-whys-whats-and-whens-of-valuetask/", BLOG, "When ValueTask saves allocations and the rules for consuming it.", False),
 "valuetask-pooling": ("article", "Async ValueTask pooling in .NET 5", "https://devblogs.microsoft.com/dotnet/async-valuetask-pooling-in-net-5/", BLOG, "How the runtime pools async state machines behind ValueTask.", False),
 "dont-block": ("article", "Don't block on async code", "https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html", CLEARY, "The classic explanation of the .Result / .Wait() deadlock.", False),
 "threadpool": ("article", "ThreadPool class", "https://learn.microsoft.com/en-us/dotnet/api/system.threading.threadpool?view=net-10.0", LEARN, "API reference for the managed thread pool.", False),
 "threading-config": ("article", "Runtime configuration options for threading", "https://learn.microsoft.com/en-us/dotnet/core/runtime-config/threading", LEARN, "Thread-pool settings such as minimum threads.", False),
 "cancellation": ("article", "Cancellation in managed threads", "https://learn.microsoft.com/en-us/dotnet/standard/threading/cancellation-in-managed-threads", LEARN, "The cooperative cancellation model with CancellationToken.", False),
 "cleary-cancellation": ("article", "Cancellation, part 1: overview", "https://blog.stephencleary.com/2022/02/cancellation-1-overview.html", CLEARY, "A practical series on cooperative cancellation.", False),
 "using-threads": ("article", "Using threads and threading", "https://learn.microsoft.com/en-us/dotnet/standard/threading/using-threads-and-threading", LEARN, "Creating threads and synchronizing access to shared data.", False),
 "threading-basics": ("article", "Managed threading basics", "https://learn.microsoft.com/en-us/dotnet/standard/threading/managed-threading-basics", LEARN, "Threads, synchronization primitives and their trade-offs.", False),
 "channels": ("article", "Channels", "https://learn.microsoft.com/en-us/dotnet/core/extensions/channels", LEARN, "Bounded and unbounded async producer-consumer queues.", False),
 "channels-intro": ("article", "An introduction to System.Threading.Channels", "https://devblogs.microsoft.com/dotnet/an-introduction-to-system-threading-channels/", BLOG, "Design and usage of channels, with backpressure.", False),
 "foreachasync": ("article", "Parallel.ForEachAsync method", "https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.parallel.foreachasync?view=net-7.0", LEARN, "Bounded-concurrency async loops with MaxDegreeOfParallelism.", False),
 "bgservice": ("article", "BackgroundService gotcha: silent failures", "https://blog.stephencleary.com/2020/05/backgroundservice-gotcha-silent-failure.html", CLEARY, "Why exceptions in ExecuteAsync used to vanish, and how to handle them.", False),
 "gc-fundamentals": ("article", "Fundamentals of garbage collection", "https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/fundamentals", LEARN, "Generations, the large object heap, compaction and background GC.", False),
 "gc-overview": ("article", ".NET garbage collection", "https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/", LEARN, "Overview of automatic memory management in .NET.", False),
 "aspnet-memory": ("article", "Memory management and patterns in ASP.NET Core", "https://learn.microsoft.com/en-us/aspnet/core/performance/memory?view=aspnetcore-9.0", LEARN, "Allocation patterns, the LOH, pooling and HttpClient in web apps.", False),
 "workstation-server": ("article", "Workstation vs. server garbage collection", "https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/workstation-server-gc", LEARN, "How the two GC flavours trade footprint for throughput.", False),
 "gc-config": ("article", "Runtime configuration options for garbage collection", "https://learn.microsoft.com/en-us/dotnet/core/runtime-config/garbage-collector", LEARN, "GC settings, including behaviour under container limits.", False),
 "dispose": ("article", "Implement a Dispose method", "https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose", LEARN, "The dispose pattern, finalizers and SafeHandle.", False),
 "memory-span": ("article", "Memory<T> and Span<T> usage guidelines", "https://learn.microsoft.com/en-us/dotnet/standard/memory-and-spans/memory-t-usage-guidelines", LEARN, "Ownership and lifetime rules for spans and memory.", False),
 "span-api": ("article", "Span<T> struct", "https://learn.microsoft.com/en-us/dotnet/api/system.span-1?view=net-10.0", LEARN, "API reference for Span<T>.", False),
 "span-video": ("video", "A complete .NET developer's guide to Span with Stephen Toub", "https://learn.microsoft.com/en-us/shows/on-dotnet/a-complete-dotnet-developers-guide-to-span-with-stephen-toub", "Stephen Toub", "Deep-dive video on Span<T> internals and usage.", False),
 "native-aot": ("article", "Native AOT diagnostics", "https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/diagnostics", LEARN, "What changes when there is no JIT at runtime.", False),
 "net9-runtime": ("article", "What's new in the .NET 9 runtime", "https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-9/runtime", LEARN, "JIT, tiering and code-generation improvements in .NET 9.", False),
 "benchmarkdotnet": ("link", "BenchmarkDotNet overview", "https://benchmarkdotnet.org/articles/overview.html", "BenchmarkDotNet", "The standard .NET micro-benchmarking library.", True),
 "diagnostics": ("article", ".NET diagnostics tools", "https://learn.microsoft.com/en-us/dotnet/core/diagnostics/", LEARN, "Overview of counters, tracing and dump tools.", True),
 "dotnet-counters": ("article", "dotnet-counters", "https://learn.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-counters", LEARN, "Live GC, thread-pool and request counters.", True),
 "exceptions": ("article", "Best practices for exceptions", "https://learn.microsoft.com/en-us/dotnet/standard/exceptions/best-practices-for-exceptions", LEARN, "When to throw, what to catch and how to rethrow.", True),
 "middleware": ("article", "ASP.NET Core middleware", "https://learn.microsoft.com/en-us/aspnet/core/fundamentals/middleware/", LEARN, "The request pipeline and middleware ordering.", False),
 "custom-middleware": ("article", "Write custom ASP.NET Core middleware", "https://learn.microsoft.com/en-us/aspnet/core/fundamentals/middleware/write", LEARN, "Building your own middleware components.", False),
 "di": ("article", "Dependency injection in ASP.NET Core", "https://learn.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection", LEARN, "Service lifetimes, scope validation and captive dependencies.", False),
 "minimal-apis": ("article", "Minimal APIs overview", "https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis", LEARN, "Endpoint-based APIs with minimal ceremony.", False),
 "aspnet-fundamentals": ("article", "ASP.NET Core fundamentals", "https://learn.microsoft.com/en-us/aspnet/core/fundamentals/", LEARN, "Hosting, configuration, routing and the overall app model.", False),
 "options": ("article", "Options pattern in ASP.NET Core", "https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options", LEARN, "IOptions, IOptionsSnapshot, IOptionsMonitor and validation.", True),
 "error-handling": ("article", "Handle errors in ASP.NET Core", "https://learn.microsoft.com/en-us/aspnet/core/fundamentals/error-handling", LEARN, "Exception handling middleware and IExceptionHandler.", False),
 "api-errors": ("article", "Handle errors in ASP.NET Core APIs", "https://learn.microsoft.com/en-us/aspnet/core/web-api/handle-errors", LEARN, "ProblemDetails responses for web APIs.", False),
 "authn": ("article", "Overview of ASP.NET Core authentication", "https://learn.microsoft.com/en-us/aspnet/core/security/authentication/", LEARN, "Schemes, handlers and JWT bearer authentication.", False),
 "minimal-security": ("article", "Authentication and authorization in minimal APIs", "https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/security", LEARN, "Securing endpoints with policies, roles and claims.", False),
 "httpclientfactory": ("article", "IHttpClientFactory with .NET", "https://learn.microsoft.com/en-us/dotnet/core/extensions/httpclient-factory", LEARN, "Typed and named clients, and avoiding socket exhaustion.", True),
 "http-resilience": ("article", "Build resilient HTTP apps", "https://learn.microsoft.com/en-us/dotnet/core/resilience/http-resilience", LEARN, "The standard resilience handler: retries, breaker, timeouts.", False),
 "rate-limit": ("article", "Rate limiting middleware in ASP.NET Core", "https://learn.microsoft.com/en-us/aspnet/core/performance/rate-limit", LEARN, "Fixed window, sliding window, token bucket and concurrency limiters.", False),
 "rate-limit-samples": ("article", "Rate limiting samples", "https://learn.microsoft.com/en-us/aspnet/core/performance/rate-limit-samples", LEARN, "Worked examples, including partitioned limiters.", False),
 "change-tracking": ("article", "Change tracking in EF Core", "https://learn.microsoft.com/en-us/ef/core/change-tracking/", LEARN, "How the context tracks and diffs entities.", True),
 "related-data": ("article", "Loading related data", "https://learn.microsoft.com/en-us/ef/core/querying/related-data/", LEARN, "Eager, explicit and lazy loading, and split queries.", True),
 "ef-perf": ("article", "Advanced performance topics (EF Core)", "https://learn.microsoft.com/en-us/ef/core/performance/advanced-performance-topics", LEARN, "Compiled queries, pooling and other EF Core performance techniques.", False),
 "ef-concurrency": ("article", "Handling concurrency conflicts", "https://learn.microsoft.com/en-us/ef/core/saving/concurrency", LEARN, "Optimistic concurrency with tokens and row versions.", False),
 "ef-saving": ("article", "Saving data (EF Core)", "https://learn.microsoft.com/en-us/ef/core/saving/", LEARN, "SaveChanges, transactions and execution strategies.", False),
 "ef-overview": ("article", "Entity Framework Core overview", "https://learn.microsoft.com/en-us/ef/core/", LEARN, "Getting started with EF Core.", False),
 "web-architectures": ("article", "Common web application architectures", "https://learn.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/common-web-application-architectures", LEARN, "Layered and clean architecture for ASP.NET Core apps.", False),
 "netarchtest": ("link", "NetArchTest", "https://github.com/BenMorris/NetArchTest", "Ben Morris", "A library for enforcing architecture rules in unit tests.", True),
 "microservices-guide": ("article", ".NET microservices: architecture for containerized .NET applications", "https://learn.microsoft.com/en-us/dotnet/architecture/microservices/", LEARN, "Microsoft's guide to designing and running microservices.", False),
 "distributed-data": ("article", "Distributed data", "https://learn.microsoft.com/en-us/dotnet/architecture/cloud-native/distributed-data", LEARN, "Data consistency challenges across services.", False),
 "cqrs": ("article", "Apply simplified CQRS and DDD patterns in a microservice", "https://learn.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/apply-simplified-microservice-cqrs-ddd-patterns", LEARN, "Separating read and write models without full event sourcing.", False),
 "outbox": ("article", "Pattern: Transactional outbox", "https://microservices.io/patterns/data/transactional-outbox.html", MSIO, "Publishing events reliably without dual writes.", False),
 "log-tailing": ("article", "Pattern: Transaction log tailing", "https://microservices.io/patterns/data/transaction-log-tailing.html", MSIO, "Relaying outbox messages with change data capture.", False),
 "saga": ("article", "Pattern: Saga", "https://microservices.io/patterns/data/saga.html", MSIO, "Maintaining consistency across services with compensations.", False),
 "temporal": ("article", "Temporal .NET developer guide", "https://docs.temporal.io/develop/dotnet", "Temporal", "Durable workflows, activities and determinism rules in .NET.", True),
 "retry-storm": ("article", "Retry storm antipattern", "https://learn.microsoft.com/en-us/azure/architecture/antipatterns/retry-storm/", LEARN, "How naive retries amplify outages, and how to avoid it.", False),
 "transient-faults": ("article", "Recommendations for handling transient faults", "https://learn.microsoft.com/en-us/azure/well-architected/design-guides/handle-transient-faults", LEARN, "Backoff, jitter, idempotency and retry budgets.", False),
 "resiliency-patterns": ("article", "Application resiliency patterns", "https://learn.microsoft.com/en-us/dotnet/architecture/cloud-native/application-resiliency-patterns", LEARN, "Retry, circuit breaker and other cloud-native resilience patterns.", False),
 "resilience": ("article", "Introduction to resilient app development", "https://learn.microsoft.com/en-us/dotnet/core/resilience/", LEARN, "Microsoft.Extensions.Resilience and composing pipelines.", False),
 "test-services": ("article", "Testing ASP.NET Core services and web apps", "https://learn.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/test-aspnet-core-services-web-apps", LEARN, "Unit, integration and functional tests for services.", False),
 "integration-tests": ("article", "Integration tests in ASP.NET Core", "https://learn.microsoft.com/en-us/aspnet/core/test/integration-tests", LEARN, "WebApplicationFactory and in-memory test servers.", False),
 "testcontainers": ("link", "Testcontainers for .NET", "https://dotnet.testcontainers.org/", "Testcontainers", "Throwaway Docker dependencies for integration tests.", False),
 "otel": ("link", "OpenTelemetry .NET", "https://opentelemetry.io/docs/languages/dotnet/", "OpenTelemetry", "Logs, metrics and traces with one instrumentation API.", True),
 "confluent": ("article", "Confluent .NET client documentation", "https://docs.confluent.io/kafka-clients/dotnet/current/overview.html", "Confluent", "Producing and consuming Kafka messages from .NET.", True),
 "cleary-blog": ("link", "Stephen Cleary's blog", "https://blog.stephencleary.com/", CLEARY, "Async and concurrency done right.", False),
 "lock-blog": ("link", "Andrew Lock's blog", "https://andrewlock.net/", "Andrew Lock", "ASP.NET Core internals, explained in depth.", False),
 "dotnet-blog": ("link", ".NET Blog", "https://devblogs.microsoft.com/dotnet/", BLOG, "Performance write-ups for every .NET release.", False),
}

A1, A2, A3, A4, A5 = "C#", "Async & Concurrency", "Memory & Performance", "ASP.NET Core & EF Core", "Architecture & Distributed Systems"

# (prompt, tags, difficulty, [A,B,C,D], correct index, explanation, material keys)
Q = [
 ("What is the key difference between value types and reference types in C#?", [A1], "easy",
  ["A value type holds its data inline and is copied on assignment; a reference type points to a heap object, so assignment copies the reference.",
   "Value types always live on the stack and reference types always live on the heap; that location is the defining difference.",
   "Assigning a reference type makes a deep copy of the object, while value types share a single instance between variables.",
   "Value types can never be null or boxed, while reference types are always nullable at both compile time and runtime."], 0,
  "A value type holds its data inline and is copied on assignment. A reference type holds a pointer to a heap object, and assignment copies the pointer. \"Structs live on the stack\" is a simplification: a struct field inside a class lives on the heap. Mention default values, null and mutation surprises.",
  ["types", "structs-spec"]),
 ("When should you choose a struct, a class or a record?", [A1, "Records"], "easy",
  ["Choose a struct for large mutable entities, because copying a big struct is cheaper than passing a reference.",
   "Choose a class whenever you need value-based equality, because classes compare their fields by default.",
   "Struct for small, short-lived immutable values; class for identity, inheritance or shared state; record for value equality and concise immutable data.",
   "Records are always value types allocated on the stack, so they should replace structs wherever possible."], 2,
  "Struct for small, short-lived, immutable values; copying a big struct costs more than passing a reference. Class when you need identity, inheritance or shared state. Records give value-based equality, with copies and short immutable types; a record is a class, a record struct is a value type.",
  ["records", "structs-spec"]),
 ("What is boxing, and why does it matter for performance?", [A1], "easy",
  ["Boxing converts a reference type into a value type so it can be stored without any heap allocation.",
   "Converting a value type to object or an interface allocates a heap object and copies the value, adding GC pressure in hot paths.",
   "Boxing is a compile-time cast with no runtime cost; it only affects which overload the compiler picks.",
   "Boxing wraps a value in a struct so it can be passed by reference, which avoids copying large values."], 1,
  "Converting a value type to object or an interface allocates a heap object and copies the value; unboxing copies it back. The cost is allocations and garbage collection pressure in hot paths. Avoid it with generics, generic collections and constrained interface calls.",
  ["boxing", "conversions"]),
 ("How do nullable reference types differ from nullable value types?", [A1, "Nullability"], "medium",
  ["Both are runtime types: string? compiles to Nullable<string> in the same way int? compiles to Nullable<int>.",
   "Nullable reference types make the runtime throw at the assignment point, whereas int? simply stores null.",
   "The ! operator checks at runtime that a value is not null and throws an exception if it is.",
   "int? is a real runtime type, while nullable reference types are compile-time annotations that only produce warnings."], 3,
  "Nullable<T> (int?) is a real runtime type. Nullable reference types are compile-time annotations only: they warn, they do not change runtime behaviour. They do not protect you at boundaries such as JSON deserialization, and the ! operator silences the compiler without proving anything.",
  ["nrt", "nullable-value"]),
 ("What is deferred execution in LINQ?", [A1, "LINQ"], "medium",
  ["LINQ queries run as soon as they are declared and cache their results, so enumerating twice is free.",
   "Operators such as Where and Select build an iterator that runs only when enumerated, so enumerating twice runs the query twice.",
   "Deferred execution means LINQ runs each query on a background thread and returns a Task to await.",
   "It applies only to IQueryable; LINQ to Objects always evaluates the whole query eagerly when it is built."], 1,
  "Operators such as Where and Select build an iterator; nothing runs until you enumerate it. Enumerating twice runs the query twice, which against a database means two round trips. Materialize with ToList when you need a stable snapshot. Watch for captured variables that change before enumeration.",
  ["linq-intro", "linq-overview"]),
 ("What is the difference between IEnumerable<T> and IQueryable<T>?", [A1, "LINQ"], "medium",
  ["IQueryable builds an expression tree a provider such as EF Core translates to SQL; IEnumerable runs in memory with compiled delegates.",
   "They are interchangeable; IQueryable is simply IEnumerable with an extra Count property for databases.",
   "IEnumerable queries are translated to SQL by EF Core, while IQueryable queries always execute in memory.",
   "IQueryable can call any custom C# method inside the expression, because the provider compiles it into SQL."], 0,
  "IEnumerable runs in memory with compiled delegates. IQueryable builds an expression tree that a provider such as EF Core translates to SQL. Calling AsEnumerable or ToList too early pulls the whole table into memory, and a custom C# method inside the expression cannot be translated.",
  ["iqueryable", "linq-overview"]),
 ("How do delegates and events relate, and what is the classic event-handler memory leak?", [A1], "medium",
  ["Events are a runtime mechanism unrelated to delegates, and subscribers are held through weak references, so they cannot leak.",
   "Subscribers hold a reference to the publisher, so the leak happens when a subscriber outlives the object it listens to.",
   "An event restricts invoking a delegate to its declaring class; a long-lived publisher keeps every never-unsubscribed subscriber alive.",
   "Func and Action cannot be multicast, which is why events are required whenever several handlers must run."], 2,
  "A delegate is a type-safe function reference and can be multicast. An event restricts invocation to its declaring class. A subscriber is referenced by the publisher, so a long-lived publisher that is never unsubscribed keeps the subscriber alive.",
  ["delegates", "events"]),
 ("Which statement about covariance and contravariance in C# is correct?", [A1, "Generics"], "hard",
  ["IEnumerable<out T> is covariant because it only produces T, and Action<in T> is contravariant because it only consumes T.",
   "Covariance lets a List<string> be assigned to a List<object> safely, because List<T> is a class.",
   "Array covariance is fully type-safe, because the compiler rejects every invalid write into the array.",
   "Contravariance means an interface method may return a less derived type than the one it declares."], 0,
  "IEnumerable<out T> is covariant: an IEnumerable<string> can be used as IEnumerable<object>, because the type only produces values. Action<in T> is contravariant, because the type only consumes them. It applies to interfaces and delegates, not classes. Arrays are covariant too, but unsafe: a bad write throws at runtime.",
  ["variance-cs", "variance-generics"]),
 ("Why are strings immutable in .NET, and when should you use StringBuilder?", [A1, "Strings"], "easy",
  ["Strings are mutable internally; StringBuilder exists only to apply culture-aware formatting rules.",
   "Immutability exists only for thread safety, and the JIT turns concatenation in a loop into a single allocation.",
   "Use StringBuilder for every string operation, because plain concatenation is always slower and allocates more.",
   "Immutability makes strings safe to share and intern; concatenating in a loop allocates each time, so use StringBuilder for many appends."], 3,
  "Immutability makes strings safe to share and cache, and makes interning possible. Concatenating in a loop allocates a new string each time, so use StringBuilder for many appends. Prefer ordinal comparisons for speed and culture safety, and span-based APIs to slice without allocating.",
  ["string-ops"]),
 ("How must ==, Equals and GetHashCode relate when you define equality for a type?", [A1], "medium",
  ["Overriding Equals is enough; GetHashCode is only used for debugging output and can be left as is.",
   "If you override Equals you must override GetHashCode consistently, and never base the hash on mutable fields.",
   "== always calls Equals on reference types, so overloading == is never necessary once Equals is overridden.",
   "Mutable fields make the best hash codes, because the hash then reflects the object's current state."], 1,
  "== on a reference type compares references unless overloaded (string overloads it). If you override Equals you must override GetHashCode consistently, or dictionary lookups break. Never use mutable fields in a hash code. Implement IEquatable<T> on structs to avoid boxing. Records generate all of this.",
  ["value-equality", "equality-comparisons", "pattern-matching"]),

 ("What does async/await actually do?", [A2, "Async"], "medium",
  ["It runs the method on a new background thread, so the awaited work happens in parallel with the caller.",
   "It blocks the calling thread until the task finishes, but releases any locks the thread held while waiting.",
   "The compiler rewrites the method into a state machine; awaiting an incomplete task registers a continuation and returns, so no thread is blocked during I/O.",
   "It converts thrown exceptions into return codes, so callers no longer need try/catch around awaited calls."], 2,
  "The compiler rewrites the method into a state machine. An await on an incomplete task registers a continuation and returns to the caller, so no thread sits blocked during I/O. Exceptions are captured in the task. Async is about not blocking threads, not about running work in parallel.",
  ["async-faq", "tap-consuming"]),
 ("When should you use ConfigureAwait(false)?", [A2, "Async"], "medium",
  ["In library code, so continuations don't hop back to a captured context, avoiding deadlocks in context-bound hosts.",
   "In UI event handlers, so the code after the await can update controls directly on the UI thread.",
   "Never: it stops exceptions from the awaited task propagating to the caller.",
   "Only in ASP.NET Core controllers, because they run on a single-threaded synchronization context."], 0,
  "By default the continuation resumes on the captured context or scheduler. In library code, false avoids the hop back and avoids deadlocks in context-bound hosts. ASP.NET Core has no synchronization context, so it matters less in app code, but libraries should still do it.",
  ["configureawait"]),
 ("When should you return ValueTask instead of Task?", [A2, "Async"], "hard",
  ["Always, because ValueTask is strictly faster than Task and has no usage restrictions.",
   "When several callers need to await the same result many times, since ValueTask caches it.",
   "Whenever a method does CPU-bound work, because ValueTask runs on the thread pool automatically.",
   "When the result is often available synchronously and a benchmark shows the allocations matter; await it only once."], 3,
  "ValueTask avoids an allocation when the result is often ready synchronously. The price: await it once, never await it twice, never read .Result before it completes. Default to Task and switch only after a benchmark shows allocations matter.",
  ["valuetask", "valuetask-pooling"]),
 ("Why does blocking on async code with .Result or .Wait() cause deadlocks?", [A2, "Async"], "medium",
  ["Because .Result cancels the underlying task, and that cancellation never completes.",
   "Because the thread pool refuses to run tasks that were created from synchronous methods.",
   "It blocks the very thread the continuation needs in hosts with a single-threaded context, such as classic ASP.NET or UI apps.",
   "It deadlocks only in console apps, because console apps have no thread pool to run continuations."], 2,
  ".Result or .Wait() blocks the thread that the continuation needs, in hosts with a single-threaded context such as classic ASP.NET or UI apps. In ASP.NET Core the usual failure is thread-pool starvation instead. Fix: async all the way up, and ConfigureAwait(false) in libraries.",
  ["dont-block"]),
 ("When is Task.Run appropriate, and what is thread-pool starvation?", [A2, "Thread pool"], "hard",
  ["Task.Run offloads CPU-bound work; starvation happens when blocking calls tie up pool threads faster than the pool adds new ones.",
   "Wrap I/O calls in Task.Run so they don't use threads; starvation means CPU usage has reached 100%.",
   "Task.Run creates a dedicated OS thread every time, so it can never contribute to starvation.",
   "Starvation is when the GC pauses all threads, and Task.Run avoids it by running on a separate heap."], 0,
  "Task.Run moves CPU-bound work to the pool. Wrapping I/O in it just burns a pool thread. Blocking calls on pool threads starve it, because the pool adds threads slowly. Symptom: high latency with low CPU. Diagnose with queue length and thread counts.",
  ["threadpool", "threading-config"]),
 ("How does cancellation work in .NET?", [A2, "Async"], "medium",
  ["Cancelling a token forcibly aborts the thread that is running the operation, wherever it is.",
   "CancellationToken works only with Task.Run; I/O APIs ignore any token they are given.",
   "Disposing the CancellationTokenSource is what notifies every listener that it has been cancelled.",
   "It is cooperative: the caller signals a CancellationToken, and the callee checks it and throws OperationCanceledException."], 3,
  "Cooperative: the caller signals a CancellationToken, the callee checks it and throws OperationCanceledException. Pass the token through every async call, link tokens with CreateLinkedTokenSource, dispose sources, and use HttpContext.RequestAborted in web code.",
  ["cancellation", "cleary-cancellation"]),
 ("When do lock, SemaphoreSlim and Interlocked each fit?", [A2, "Synchronization"], "medium",
  ["lock for short synchronous sections, SemaphoreSlim.WaitAsync for async mutual exclusion or throttling, Interlocked for atomic single-variable updates.",
   "lock is the right choice around await calls, because it is released automatically while the method awaits.",
   "Interlocked is designed for throttling concurrent HTTP calls to a fixed maximum number at once.",
   "Locking on this or a string literal is best practice, because every caller can share the same lock."], 0,
  "lock guards a short synchronous section and cannot contain an await. SemaphoreSlim.WaitAsync gives async mutual exclusion or throttling. Interlocked makes single-variable updates atomic. Never lock on this, a public object or a string. Prefer immutable data or concurrent collections.",
  ["using-threads", "threading-basics"]),
 ("What are System.Threading.Channels used for?", [A2, "Channels"], "medium",
  ["Sending messages between separate processes over named pipes on the same machine.",
   "Replacing Kafka or RabbitMQ for durable messaging between services.",
   "Async producer-consumer queues; a bounded channel applies backpressure when it is full, which protects memory.",
   "Broadcasting UI events to every open window in a desktop application."], 2,
  "System.Threading.Channels gives async producer-consumer queues. A bounded channel applies backpressure when full, which protects memory. Use them to hand work between stages or to a background consumer, instead of BlockingCollection.",
  ["channels", "channels-intro"]),
 ("When should you prefer Parallel.ForEachAsync over Task.WhenAll?", [A2, "Async"], "medium",
  ["Never: Task.WhenAll already limits concurrency to the number of CPU cores on the machine.",
   "When you need to bound concurrency so a database or partner API isn't overwhelmed; WhenAll starts everything at once.",
   "When the work is purely synchronous CPU work, because ForEachAsync runs inline on the calling thread.",
   "When results must come back in the original order, which Task.WhenAll cannot guarantee."], 1,
  "WhenAll starts everything at once, which can overwhelm a database or partner API. Parallel.ForEachAsync bounds concurrency with MaxDegreeOfParallelism. Use Parallel.For for CPU-bound loops and an async-aware limit for I/O.",
  ["foreachasync"]),
 ("What commonly goes wrong in a BackgroundService?", [A2, "Hosting"], "hard",
  ["Nothing needs handling, because a BackgroundService restarts automatically after any exception.",
   "ExecuteAsync runs once per HTTP request, so it must finish within the request timeout.",
   "Background services cannot use dependency injection, so all services must be created manually.",
   "Since .NET 6 an unhandled exception in ExecuteAsync stops the host by default, so decide deliberately whether to catch, log and retry."], 3,
  "An unhandled exception in ExecuteAsync used to fail silently; since .NET 6 the host stops by default, so decide on purpose: catch, log and retry, or let it stop. Long loops must honour the stopping token, and work must be idempotent because a restart repeats it.",
  ["bgservice", "cleary-blog"]),

 ("How do garbage collection generations work in .NET?", [A3, "GC"], "medium",
  ["Objects start in generation 2 and are moved down toward generation 0 as they get older.",
   "Every collection scans the entire heap, regardless of which generation triggered it.",
   "New objects start in gen 0 and survivors are promoted to gen 1, then gen 2; gen 0 collections are cheap and frequent.",
   "Generations exist only in server GC; workstation GC keeps all objects in a single generation."], 2,
  "New objects start in generation 0. Survivors are promoted to 1, then 2. Most objects die young, so gen 0 collections are cheap and frequent; gen 2 collections are rare and expensive. Collections can compact memory, and background GC lets gen 2 work run concurrently.",
  ["gc-fundamentals", "gc-overview"]),
 ("What is the large object heap, and why can it cause problems?", [A3, "GC"], "hard",
  ["Objects of about 85,000 bytes and up go there; it is collected with gen 2 and not compacted by default, so it can fragment.",
   "It holds every object larger than 1 KB and is compacted after each gen 0 collection.",
   "It is unmanaged memory that you must free manually with Marshal.FreeHGlobal.",
   "Large objects are stored on the thread's stack, so allocating too many causes a stack overflow."], 0,
  "Large objects (about 85,000 bytes and up) go to a separate heap that is collected with gen 2 and by default is not compacted, so it can fragment. Repeated large short-lived arrays cause memory growth and pauses. Rent buffers from ArrayPool instead.",
  ["gc-fundamentals", "aspnet-memory"]),
 ("What is the difference between workstation and server GC?", [A3, "GC"], "medium",
  ["Server GC uses a single heap to minimize memory, while workstation GC uses one heap per core for throughput.",
   "Workstation GC favours low footprint and latency; server GC uses a heap and GC thread per core for throughput, using more memory.",
   "They are identical, and the setting only changes how much the GC writes to the logs.",
   "Server GC disables generations entirely to avoid pauses on busy servers."], 1,
  "Workstation uses one heap and favours low footprint and latency. Server uses a heap and thread per core and favours throughput, using more memory. In containers, CPU and memory limits change the outcome, so measure rather than assume.",
  ["workstation-server", "gc-config"]),
 ("How does IDisposable relate to finalizers?", [A3, "Resources"], "medium",
  ["Every class that implements IDisposable must also declare a finalizer.",
   "Finalizers run deterministically at the end of a using block, just before Dispose.",
   "The DI container never disposes the services it creates, so they must always be disposed manually.",
   "Dispose releases resources deterministically; a finalizer is only a safety net for unmanaged handles, and SafeHandle is usually better."], 3,
  "Dispose releases resources deterministically, usually through using. A finalizer is only a safety net for unmanaged handles, and SafeHandle is usually better. A class holding only managed objects needs no finalizer. For async cleanup use IAsyncDisposable. The DI container disposes what it creates.",
  ["dispose"]),
 ("What are Span<T> and Memory<T>?", [A3, "Span"], "hard",
  ["Span<T> is a thread-safe collection that grows automatically, much like List<T>.",
   "Memory<T> is stack-only, while Span<T> can be stored in class fields and used across awaits.",
   "Span<T> is a stack-only view over contiguous memory, so slicing allocates nothing; Memory<T> is its heap-friendly counterpart for async code.",
   "Both copy the underlying data on every slice, so that the original buffer stays immutable."], 2,
  "Span<T> is a stack-only view over contiguous memory, so slicing allocates nothing. Because it is a ref struct it cannot be a class field or live across an await. Memory<T> is the heap-friendly counterpart for async code. Typical use: parsing without substrings.",
  ["memory-span", "span-api", "span-video"]),
 ("What is the right way to cut allocations in an ASP.NET Core service?", [A3, "Performance"], "medium",
  ["Turn off the garbage collector in production so allocations never need to be collected.",
   "Measure first with a profiler or allocation counters, then pool buffers, avoid large objects and stream large payloads.",
   "Convert every class into a struct, which removes heap allocations from the service entirely.",
   "Call GC.Collect() at the end of every request so memory is freed as early as possible."], 1,
  "Find them first with a profiler or allocation counters. Then pool buffers, avoid large objects, avoid closures and LINQ in hot paths, reuse HttpClient through the factory, and stream large payloads instead of buffering them.",
  ["aspnet-memory"]),
 ("How do tiered compilation, ReadyToRun and Native AOT differ?", [A3, "Runtime"], "hard",
  ["Native AOT keeps the JIT but precompiles hot paths, so reflection and dynamic code work unchanged.",
   "ReadyToRun removes the runtime entirely and produces a single self-contained native executable.",
   "Tiered compilation interprets IL indefinitely and never produces optimized machine code.",
   "Tiering recompiles hot methods with more optimization, ReadyToRun precompiles for startup, and Native AOT has no JIT at all."], 3,
  "Tiered compilation starts with quick code, then recompiles hot methods with more optimization. ReadyToRun precompiles for faster startup. Native AOT compiles ahead of time: tiny startup and memory, but no JIT, so reflection and dynamic code are restricted. Pick by workload: long-running API versus short-lived function.",
  ["native-aot", "net9-runtime", "dotnet-blog"]),
 ("How do you benchmark .NET code correctly?", [A3, "Performance"], "easy",
  ["Wrap the code in a Stopwatch loop in a Debug build and keep the fastest run.",
   "Use BenchmarkDotNet in Release mode, which handles warmup, statistics and allocations, and compare against a baseline.",
   "Measure only the very first call, because that is what users actually experience.",
   "Run the benchmark under the debugger so you can step through the hot paths while timing them."], 1,
  "Use BenchmarkDotNet, which handles warmup, statistics and allocation reporting, instead of a stopwatch in a loop. Run in release mode, compare against a baseline and report allocations. Profile before optimizing, since most time is rarely where you think.",
  ["benchmarkdotnet"]),
 ("How do you diagnose a memory leak or high CPU in production?", [A3, "Diagnostics"], "hard",
  ["Start with live counters for GC and the thread pool, then capture traces or dumps and compare snapshots over time.",
   "Restart the service on a fixed schedule, since leaks cannot be diagnosed in production.",
   "Attach the Visual Studio debugger to the production process and step through requests.",
   "Raise the container memory limit until the symptoms stop appearing."], 0,
  "Start with live counters for GC and thread-pool behaviour, then capture a trace or a dump or GC dump, and compare snapshots over time to see what grows. Tools: dotnet-counters, dotnet-trace, dotnet-dump, dotnet-gcdump. Back it with metrics from OpenTelemetry.",
  ["diagnostics", "dotnet-counters"]),
 ("What do exceptions cost, and how should you use them?", [A3, "Exceptions"], "medium",
  ["Throwing is as cheap as a normal return, so exceptions are fine for ordinary control flow.",
   "Rethrow with throw ex; because it preserves the original stack trace.",
   "Catch Exception everywhere and swallow it, so that the service keeps running.",
   "Throwing captures a stack trace and unwinds, far slower than a return; use TryParse-style APIs for expected cases."], 3,
  "Throwing captures a stack trace and unwinds, which is far slower than a normal return. Do not use exceptions for expected flow: use TryParse-style methods. Catch only what you can handle, use throw; to keep the stack, and use exception filters.",
  ["exceptions"]),

 ("How does the ASP.NET Core middleware pipeline work, and why does order matter?", [A4, "Middleware"], "medium",
  ["Middleware runs in alphabetical order of class name, so registration order doesn't matter.",
   "Only the last middleware registered gets to see and modify the response.",
   "Each middleware acts before and after the next and can short-circuit; order is registration order, so auth must follow routing correctly.",
   "Authorization must run before authentication, so unauthenticated requests are rejected earlier."], 2,
  "Each middleware can act before and after the next one, and can short-circuit the request. Order is the order of registration, so exception handling, routing, CORS, authentication and authorization must sit in the right sequence. Know how to write custom middleware.",
  ["middleware", "custom-middleware", "lock-blog"]),
 ("What are the DI lifetimes, and what is a captive dependency?", [A4, "Dependency injection"], "medium",
  ["Transient, scoped (one per request) and singleton; a captive dependency is a singleton holding a scoped service, keeping it alive too long.",
   "Scoped means one instance per thread, and singletons can safely depend on services of any lifetime.",
   "A captive dependency is a transient service that the container never disposes.",
   "Singletons are created per request in development and once per application in production."], 0,
  "Transient is new each time, scoped is one per request, singleton is one per app. A singleton that holds a scoped service keeps it alive far too long (a captive dependency), often with thread-safety bugs. Scope validation in development catches this. Use IServiceScopeFactory in background services.",
  ["di"]),
 ("How should you choose between minimal APIs and controllers?", [A4], "easy",
  ["Minimal APIs bypass the middleware pipeline, so they cannot use authentication or authorization.",
   "Controllers are deprecated in current ASP.NET Core and should all be migrated to minimal APIs.",
   "Minimal APIs suit small services with less ceremony; controllers give filters and structure for large APIs; both share one pipeline.",
   "Minimal APIs can only handle GET requests, so write endpoints need controllers."], 2,
  "Minimal APIs have less ceremony, lower overhead and fit small services and endpoint groups. Controllers give filters, model binding conventions and a familiar structure for large APIs. Both share the same pipeline. Choose by team and size, not fashion.",
  ["minimal-apis", "aspnet-fundamentals"]),
 ("What does the options pattern give you in ASP.NET Core?", [A4, "Configuration"], "medium",
  ["IOptions reloads on every request, while IOptionsMonitor reads configuration once and never changes.",
   "It stores secrets encrypted inside appsettings.json, so they are safe to commit.",
   "It replaces configuration files, so settings can only come from environment variables.",
   "Typed configuration: IOptions is a singleton snapshot, IOptionsSnapshot is per request, IOptionsMonitor reacts to changes."], 3,
  "Bind configuration sections to typed classes. IOptions is a singleton snapshot, IOptionsSnapshot is per request, IOptionsMonitor reacts to changes. Validate with data annotations and ValidateOnStart so bad config fails at startup, not at 3am.",
  ["options"]),
 ("How should a web API handle errors consistently?", [A4, "Error handling"], "medium",
  ["Return the full exception and stack trace in the response, so clients can debug problems themselves.",
   "Use one global handler that maps exceptions to RFC 9457 ProblemDetails with a stable code and trace id, never leaking stack traces.",
   "Catch and log exceptions in every method, then return 200 OK with an error flag in the body.",
   "Return 500 for every error, including validation failures, so clients only handle one case."], 1,
  "One global handler (IExceptionHandler or middleware) that maps exceptions to RFC 9457 ProblemDetails, with a stable error code and trace id. Never leak stack traces. Validation errors return 400 with details; log once, at the boundary.",
  ["error-handling", "api-errors"]),
 ("How do authentication and authorization work with JWT bearer tokens?", [A4, "Security"], "medium",
  ["Authentication validates signature, issuer, audience and expiry to prove identity; authorization uses policies, roles and claims to decide access.",
   "A JWT is encrypted by default, so putting secrets in its claims is safe.",
   "Authorization happens first, and authentication then confirms the role that was granted.",
   "Expiry is optional; tokens should stay valid indefinitely to avoid refresh logic."], 0,
  "Authentication proves who the caller is: validate signature, issuer, audience and expiry. Authorization decides what they may do: policies, roles and claims, plus resource-based checks. Know token lifetime, refresh, key rotation and why you never put secrets in a JWT.",
  ["authn", "minimal-security"]),
 ("How should you use HttpClient and add resilience?", [A4, "HTTP"], "medium",
  ["Create a new HttpClient for every call and dispose it in a using block.",
   "Retry every request as many times as possible, including non-idempotent POSTs.",
   "Use one static HttpClient with an infinite timeout, so long calls never fail.",
   "Use IHttpClientFactory and typed clients, with timeouts, jittered retries and a circuit breaker; retry only idempotent calls."], 3,
  "Never new HttpClient() per call (socket exhaustion); use IHttpClientFactory and typed clients. Add timeouts, retries with jitter, circuit breaker and a total budget through the standard resilience handler. Retry only idempotent calls.",
  ["httpclientfactory", "http-resilience"]),
 ("How do you rate limit an ASP.NET Core API?", [A4, "Rate limiting"], "medium",
  ["In-process limiters coordinate automatically across all instances through the DI container.",
   "Return 503 with no headers, so clients back off at random intervals.",
   "Use the built-in middleware, partition by tenant or API key, and return 429 with Retry-After; in-process limits don't span instances.",
   "It can only be done at the load balancer, because ASP.NET Core has no built-in support."], 2,
  "Built-in middleware offers fixed window, sliding window, token bucket and concurrency limiters. Partition by tenant or API key, return 429 with Retry-After, and remember in-process limits do not span instances; use a gateway or shared store for that.",
  ["rate-limit", "rate-limit-samples"]),
 ("How does EF Core change tracking work, and what is the N+1 problem?", [A4, "EF Core"], "medium",
  ["Change tracking is off by default, and N+1 means N tables joined into a single query.",
   "The context diffs tracked entities on SaveChanges; N+1 is one query for parents plus one per child, fixed with Include or projection.",
   "N+1 only happens with raw SQL queries and never with LINQ queries.",
   "AsNoTracking makes reads slower, because entities must be fetched again before saving."], 1,
  "The context tracks entities and diffs them on SaveChanges. Use AsNoTracking for reads. N+1 is one query for parents plus one per child; fix with Include, projection or split queries. Check the generated SQL, and know when Dapper is the better tool.",
  ["change-tracking", "related-data", "ef-perf"]),
 ("How do you handle concurrency and transactions in EF Core?", [A4, "EF Core"], "hard",
  ["SaveChanges is not transactional, so every call must be wrapped in an explicit transaction.",
   "EF Core takes pessimistic row locks by default, so concurrency conflicts can never occur.",
   "Use optimistic concurrency with a row version, catch DbUpdateConcurrencyException and retry, merge or fail.",
   "DbUpdateConcurrencyException means the database is down, so the call should be retried forever."], 2,
  "Optimistic concurrency with a row version or concurrency token; catch DbUpdateConcurrencyException and decide to retry, merge or fail. SaveChanges is already transactional; use explicit transactions for multi-step work and execution strategies for transient retries.",
  ["ef-concurrency", "ef-saving", "ef-overview"]),

 ("How should a clean (layered) .NET solution be structured?", [A5, "Architecture"], "medium",
  ["The domain layer references Entity Framework and ASP.NET Core so entities can persist themselves.",
   "Dependencies point outward, so the UI project sits at the centre and everything depends on it.",
   "Every project should reference every other project, to avoid duplicating code between layers.",
   "Dependencies point inward: a framework-free domain at the centre, use cases around it, infrastructure implementing ports."], 3,
  "Dependencies point inward: domain at the centre, no framework references. Application layer holds use cases, infrastructure implements ports. Enforce the rules with architecture tests, and admit when the ceremony is not worth it for a small service.",
  ["web-architectures", "netarchtest"]),
 ("When should you choose microservices over a modular monolith?", [A5, "Architecture"], "hard",
  ["Always start with microservices, because they are simpler to operate than a monolith.",
   "When team size, scaling or release cadence demands it, since microservices trade independence for network and consistency costs.",
   "Whenever a project needs more than one database table, since each table needs its own service.",
   "Never, because a modular monolith cannot enforce boundaries between modules."], 1,
  "Microservices buy independent deploys and scaling at the cost of network failure, data consistency and operations. A modular monolith keeps boundaries without that cost. Split when team size, scaling or release cadence demands it. The Integration Hub is a justified split; say why.",
  ["microservices-guide", "distributed-data"]),
 ("What is CQRS, and when is it overkill?", [A5, "CQRS"], "medium",
  ["Separating the write model from read models, useful when reads and writes differ in shape or load, and overkill for simple CRUD.",
   "CQRS requires event sourcing; one cannot be used without the other.",
   "CQRS means caching every query result in Redis in front of the database.",
   "It is required for any API that exposes both GET and POST endpoints."], 0,
  "Separate the write model from read models, possibly with different stores. Useful when reads and writes have different shapes or load. Overkill for simple CRUD. Distinguish it from event sourcing.",
  ["cqrs"]),
 ("What do the transactional outbox and inbox patterns solve?", [A5, "Messaging"], "hard",
  ["They use a distributed two-phase commit across the database and the message broker.",
   "The outbox guarantees exactly-once delivery to every consumer, so consumers need no deduplication.",
   "The change and its event are written in one local transaction and relayed later; the inbox makes redelivery harmless.",
   "The inbox stores outgoing notification emails until the user has read them."], 2,
  "Write the business change and the event in one local transaction, then a relay (poller or CDC) publishes it. That gives at-least-once delivery without dual writes. The inbox records processed message ids so redelivery is harmless. Know the ordering and cleanup trade-offs.",
  ["outbox", "log-tailing"]),
 ("What is a saga, and how does Temporal fit?", [A5, "Sagas"], "hard",
  ["A saga is a distributed ACID transaction that locks every service until the final commit.",
   "Temporal replaces sagas by guaranteeing that network calls between services never fail.",
   "A saga has no compensations; when a step fails, the earlier steps are simply left as they are.",
   "A saga is a sequence of local transactions with compensations; Temporal makes the orchestration durable across crashes."], 3,
  "A saga is a sequence of local transactions with compensations in place of a distributed transaction. Temporal makes the orchestration durable: state survives crashes, retries are built in, and compensations are plain code. Know determinism rules and Continue-As-New.",
  ["saga", "temporal"]),
 ("How do you make operations idempotent and avoid retry storms?", [A5, "Resilience"], "hard",
  ["Store results against an idempotency key, and retry with exponential backoff, jitter, budgets and circuit breakers.",
   "Retry immediately in a tight loop until the call succeeds, to recover as fast as possible.",
   "Give every request a fresh random id, so duplicate requests are always processed again.",
   "Use the same fixed retry delay on every client, so that retries stay in sync."], 0,
  "Accept an idempotency key and store the result against it; use natural keys or upserts internally. Retries need exponential backoff with jitter, budgets and circuit breakers, or they amplify an outage.",
  ["retry-storm", "transient-faults"]),
 ("How should timeout, retry and circuit-breaker policies compose?", [A5, "Resilience"], "hard",
  ["Retry inside timeout inside circuit breaker, so retries continue until the overall timeout expires.",
   "Timeout inside retry inside circuit breaker; each prevents a different failure, verified with fault injection.",
   "They are mutually exclusive, so each HTTP client can use only one of them.",
   "A circuit breaker retries failed calls faster, so the dependency recovers sooner."], 1,
  "Timeout, retry, circuit breaker, bulkhead, fallback, rate limit, load shedding. Explain the failure each one prevents and how they compose (timeout inside retry inside breaker). Show how you would test them with fault injection.",
  ["resiliency-patterns", "resilience"]),
 ("What is a good testing strategy for a .NET service?", [A5, "Testing"], "medium",
  ["Only end-to-end UI tests, because they exercise every layer at once.",
   "Mock every dependency, including types you don't own such as DbContext and HttpClient.",
   "Many fast unit tests, integration tests with WebApplicationFactory and Testcontainers, a few end-to-end and contract tests.",
   "Skip automated tests and rely on production monitoring to catch regressions."], 2,
  "Many fast unit tests (xUnit, NSubstitute) on domain logic, integration tests with WebApplicationFactory and real dependencies in Testcontainers, a few end-to-end tests, and contract tests for the public API. Avoid mocking what you do not own.",
  ["test-services", "integration-tests", "testcontainers"]),
 ("How do you make a service observable?", [A5, "Observability"], "medium",
  ["Write every request to the console and alert on each individual error.",
   "Use metrics only, because traces and logs duplicate the same information.",
   "Alert on every exception as it happens, rather than on service-level objectives.",
   "Emit structured logs, metrics and traces via OpenTelemetry, propagate trace context, and alert on SLO burn."], 3,
  "Three signals: logs (structured, with correlation ids), metrics, and traces. OpenTelemetry gives one instrumentation API; propagate trace context across HTTP, Kafka and Temporal. Define SLIs and alert on SLO burn, not on every error.",
  ["otel"]),
 ("What delivery guarantees does Kafka give, and how do you consume safely?", [A5, "Kafka"], "hard",
  ["Exactly-once delivery to any external system is the default behaviour.",
   "Kafka guarantees global ordering across all partitions of a topic.",
   "At-least-once with ordering only within a partition; commit after processing and make handlers idempotent.",
   "Commit offsets before processing, so that messages are never redelivered."], 2,
  "At-least-once by default; ordering only within a partition, so key by entity. Disable auto-commit and commit after processing, make handlers idempotent, send poison messages to a dead-letter topic, and watch consumer lag. Exactly-once is limited to Kafka-to-Kafka.",
  ["confluent"]),
]


# Longer, still-wrong distractors so the correct answer isn't always the longest.
LONGER = {
 1: (1, "Value types always live on the stack and reference types always live on the heap; that storage location is the defining difference, and it is why structs are always faster."),
 2: (0, "Choose a struct for large mutable entities with many fields, because copying a big struct is cheaper than passing a reference and it keeps related state together."),
 4: (1, "Nullable reference types make the runtime throw at the point where null is assigned, whereas int? simply stores null and the check happens only when you read .Value."),
 5: (3, "It applies only to IQueryable; LINQ to Objects evaluates the whole query eagerly when it is built, so in-memory queries can never run twice."),
 6: (3, "IQueryable can call any custom C# method inside the expression, because the provider compiles the method body into SQL and runs it inside the database."),
 7: (1, "Subscribers hold a reference to the publisher, so the leak happens when a short-lived subscriber outlives the long-lived object whose events it listens to."),
 9: (1, "Immutability exists only for thread safety, and the JIT rewrites concatenation inside a loop into a single allocation, so StringBuilder is rarely worth using today."),
 10: (2, "== always calls Equals on reference types, so once Equals is overridden, overloading the == operator as well is never necessary."),
 11: (1, "It blocks the calling thread until the awaited task finishes, but releases any locks the thread held while waiting, so other requests can use those resources meanwhile."),
 13: (1, "When several callers need to await the same result many times, because ValueTask caches its result and can safely be awaited repeatedly."),
 14: (1, "Because the thread pool refuses to run continuations for tasks that were started from synchronous methods, so the awaited work never gets scheduled."),
 15: (1, "Wrap I/O calls in Task.Run so they don't occupy request threads; starvation means CPU usage has reached 100% and no core is free to run new work."),
 16: (2, "Disposing the CancellationTokenSource is what notifies every registered listener that the operation was cancelled, so you must dispose it to stop the work."),
 17: (1, "lock is the right choice around await calls, because the compiler releases the monitor automatically while the method is suspended and reacquires it on resumption."),
 19: (2, "When the work is purely synchronous CPU work, because ForEachAsync runs every iteration inline on the calling thread and so avoids thread-pool overhead."),
 20: (1, "ExecuteAsync runs once per incoming HTTP request, so it must finish within the request timeout or the host cancels it and logs a warning."),
 21: (3, "Generations exist only in server GC; workstation GC keeps all objects in a single generation and always compacts the whole heap in one pass."),
 23: (0, "Server GC uses a single shared heap to keep memory low, while workstation GC uses one heap per core so that desktop apps get maximum throughput."),
 24: (2, "The DI container never disposes the services it creates, so every IDisposable service must be disposed manually, which is why finalizers are always required."),
 25: (1, "Memory<T> is the stack-only type, while Span<T> is the heap-friendly one that can be stored in class fields and used freely across await boundaries."),
 27: (0, "Native AOT keeps the JIT available but precompiles the hot paths ahead of time, so reflection and dynamic code generation keep working unchanged."),
 28: (0, "Wrap the code in a Stopwatch loop in a Debug build, run it a few times and keep the fastest run, since that shows the code's true speed."),
 30: (1, "Rethrow with throw ex; inside the catch block, because it preserves the original stack trace while still letting you add context."),
 31: (3, "Authorization must run before authentication, so unauthenticated requests are rejected as early as possible and the authentication handler only sees allowed traffic."),
 32: (1, "Scoped means one instance per thread, and singletons can safely depend on services of any lifetime because the container resolves them lazily on each call."),
 34: (0, "IOptions reloads configuration on every request, while IOptionsMonitor reads it once at startup and never changes afterwards, which makes it the faster option."),
 35: (2, "Catch and log exceptions in every method, then return 200 OK with an error flag in the body so clients and proxies never see a failing status code."),
 36: (1, "A JWT is encrypted by default with the signing key, so putting secrets such as passwords or connection strings in its claims is safe as long as HTTPS is used."),
 38: (0, "In-process limiters coordinate automatically across all instances through the DI container, so a single AddRateLimiter call protects the whole cluster."),
 39: (0, "Change tracking is off by default, and N+1 means N tables joined into a single query, which you fix by splitting it into one query per table."),
 40: (0, "SaveChanges is not transactional, so every call must be wrapped in an explicit transaction or a partial save can leave inconsistent data."),
 42: (0, "Always start with microservices, because they are simpler to operate than a monolith and let every team pick its own stack from day one."),
 43: (1, "CQRS requires event sourcing; one cannot be used without the other, because the read models can only be built by replaying the full event history."),
 45: (0, "A saga is a distributed ACID transaction that locks the data in every participating service until the coordinator issues the final commit."),
 46: (3, "Use the same fixed retry delay on every client, so that retries stay in sync and the recovering service sees one predictable wave of traffic."),
 47: (0, "Retry inside timeout inside circuit breaker, so retries continue until the overall timeout expires and only then does the breaker record a failure."),
 49: (1, "Use metrics only, because traces and logs duplicate the same information and add cost without improving incident response."),
}
Q2 = []
for n, q in enumerate(Q, 1):
    q = list(q)
    if n in LONGER:
        idx, text = LONGER[n]
        assert idx != q[4], (n, "patched the correct option")
        assert len(text) > len(q[3][q[4]]), (n, len(text), len(q[3][q[4]]))
        q[3] = list(q[3]); q[3][idx] = text
    Q2.append(tuple(q))
Q = Q2

assert len(Q) == 50, len(Q)
materials = []
for key, (typ, title, url, author, desc, unverified) in M.items():
    materials.append({"key": key, "type": typ, "title": title, "url": url, "author": author,
                      "description": desc + (U if unverified else "")})
questions = []
used = set()
for i, (prompt, tags, diff, opts, correct, expl, mats) in enumerate(Q, 1):
    assert len(opts) == 4 and 0 <= correct < 4, i
    for k in mats:
        assert k in M, (i, k)
        used.add(k)
    questions.append({"prompt": prompt, "tags": mapped(tags), "difficulty": diff, "options": opts,
                      "correct": correct, "explanation": expl, "materials": mats})
unused = set(M) - used
assert not unused, unused
json.dump({"name": "50 .NET interview questions", "materials": materials, "questions": questions},
          open(sys.argv[1], "w"), indent=2, ensure_ascii=False)
dist = [sum(1 for q in Q if q[4] == k) for k in range(4)]
print(f"{len(questions)} questions, {len(materials)} materials, correct-letter spread A-D: {dist}")
lens = [(len(q[3][q[4]]), sum(len(o) for j, o in enumerate(q[3]) if j != q[4]) / 3) for q in Q]
longest = sum(1 for q in Q if len(q[3][q[4]]) == max(len(o) for o in q[3]))
print(f"correct option is the longest in {longest}/50 questions")
