import os, sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))  # tools/question-banks
from bankgen import build

GO, LEARN, FOWLER, CONF, PG, STRIPE = "The Go Authors", "Microsoft Learn", "Martin Fowler", "Confluent", "PostgreSQL documentation", "Stripe"
WRONG_LINK = " Note: in your notes this link is labelled 'API versioning with Asp.Versioning', but the URL points to the response-formatting page; search for 'ASP.NET Core API versioning' instead."

M = {
 "go-errors": ("article", "Error handling and Go", "https://go.dev/blog/error-handling-and-go", GO, "Errors as values, and the idioms around them.", False),
 "go113-errors": ("article", "Working with Errors in Go 1.13", "https://go.dev/blog/go1.13-errors", GO, "Wrapping with %w, errors.Is and errors.As.", False),
 "cs-exceptions": ("article", "Exceptions and exception handling (C#)", "https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/exceptions/", LEARN, "Re-read it to notice the contrast with Go.", False),
 "tour-pointers": ("article", "A Tour of Go: Pointers", "https://go.dev/tour/moretypes/1", GO, "Pointers and value semantics in Go.", False),
 "eff-pointers": ("article", "Effective Go: Pointers vs. values", "https://go.dev/doc/effective_go#pointers_vs_values", GO, "When to use pointer receivers.", False),
 "cs-value-types": ("article", "Value types (C# reference)", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/value-types", LEARN, "C# value versus reference semantics.", False),
 "tour-interfaces": ("article", "A Tour of Go: Interfaces", "https://go.dev/tour/methods/9", GO, "Implicit interface satisfaction.", False),
 "go-proverbs": ("link", "Go Proverbs", "https://go-proverbs.github.io/", "Rob Pike", "\"Accept interfaces, return structs\" and other Go idioms.", False),
 "cs-interfaces": ("article", "Interfaces (C# programming guide)", "https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/interfaces/", LEARN, "Nominal interfaces in C#.", False),
 "slices-intro": ("article", "Go Slices: usage and internals", "https://go.dev/blog/slices-intro", GO, "Length, capacity, nil and empty slices.", False),
 "faq-nil-error": ("article", "Go FAQ: Why is my nil error value not equal to nil?", "https://go.dev/doc/faq#nil_error", GO, "A related nil-comparison subtlety.", False),
 "eff-defer": ("article", "Effective Go: Defer", "https://go.dev/doc/effective_go#defer", GO, "How defer schedules cleanup.", False),
 "common-mistakes": ("article", "Go Wiki: Common Mistakes", "https://go.dev/wiki/CommonMistakes", GO, "Classic Go footguns, including loops.", False),
 "module-layout": ("article", "Organizing a Go module", "https://go.dev/doc/modules/layout", GO, "cmd/, internal/ and package layout.", False),
 "package-names": ("article", "Package names", "https://go.dev/blog/package-names", GO, "Naming and organizing packages.", False),
 "cs-access": ("article", "Access modifiers (C#)", "https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/access-modifiers", LEARN, "public, internal and friends.", False),
 "tour-range-close": ("article", "A Tour of Go: Range and Close", "https://go.dev/tour/concurrency/4", GO, "Closing channels and ranging over them.", False),
 "spec-close": ("article", "The Go spec: Close", "https://go.dev/ref/spec#Close", GO, "The precise semantics of close().", False),
 "channels-dotnet": ("article", "Channels", "https://learn.microsoft.com/en-us/dotnet/core/extensions/channels", LEARN, "Bounded and unbounded async producer-consumer queues.", False),
 "gc-guide": ("article", "A Guide to the Go Garbage Collector", "https://go.dev/doc/gc-guide", GO, "How Go's GC works and how to tune it.", False),
 "pprof": ("article", "Profiling Go Programs", "https://go.dev/blog/pprof", GO, "CPU and memory profiling with pprof.", False),
 "dotnet-gc": ("article", ".NET garbage collection", "https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/", LEARN, "Overview of automatic memory management in .NET.", False),
 "tour-concurrency": ("article", "A Tour of Go: Concurrency", "https://go.dev/tour/concurrency", GO, "Goroutines, channels and select.", False),
 "pipelines": ("article", "Go Concurrency Patterns: Pipelines and cancellation", "https://go.dev/blog/pipelines", GO, "Fan-out, fan-in and bounded parallelism.", False),
 "whenall": ("article", "Task.WhenAll method", "https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.whenall", LEARN, "Awaiting many tasks at once.", False),
 "race-detector": ("article", "Data Race Detector", "https://go.dev/doc/articles/race_detector", GO, "Using go test -race.", False),
 "race-blog": ("article", "Introducing the Go Race Detector", "https://go.dev/blog/race-detector", GO, "How the race detector works.", False),
 "sync-primitives": ("article", "Overview of synchronization primitives", "https://learn.microsoft.com/en-us/dotnet/standard/threading/overview-of-synchronization-primitives", LEARN, "lock, Monitor, Interlocked and friends.", False),
 "tour-buffered": ("article", "A Tour of Go: Buffered Channels", "https://go.dev/tour/concurrency/3", GO, "Channels with capacity.", False),
 "concurrency-talk": ("article", "Go Concurrency Patterns (talk)", "https://go.dev/talks/2012/concurrency.slide", "Rob Pike", "The classic talk on goroutines and channels.", False),
 "foreachasync": ("article", "Parallel.ForEachAsync method", "https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.parallel.foreachasync", LEARN, "Bounded-concurrency async loops.", False),
 "waza": ("video", "Concurrency is not Parallelism", "https://go.dev/blog/waza-talk", "Rob Pike", "The talk that draws the distinction.", False),
 "gomaxprocs": ("article", "runtime.GOMAXPROCS", "https://pkg.go.dev/runtime#GOMAXPROCS", GO, "How many OS threads run goroutines at once.", False),
 "aspnet-versioning-link": ("article", "ASP.NET Core response formatting", "https://learn.microsoft.com/en-us/aspnet/core/web-api/advanced/formatting?view=aspnetcore-8.0", LEARN, "Formatting response data in web APIs." + WRONG_LINK, False),
 "tolerant-reader": ("article", "Tolerant Reader", "https://martinfowler.com/bliki/TolerantReader.html", FOWLER, "Consumers that ignore what they don't need.", False),
 "google-versioning": ("article", "Google API design guide: Versioning", "https://cloud.google.com/apis/design/versioning", "Google Cloud", "Major versions and compatibility.", False),
 "pact": ("link", "Pact documentation", "https://docs.pact.io/", "Pact Foundation", "Consumer-driven contract testing.", False),
 "cdc": ("article", "Consumer-Driven Contracts: A Service Evolution Pattern", "https://martinfowler.com/articles/consumerDrivenContracts.html", "Ian Robinson", "Letting consumers state what they depend on.", False),
 "fielding": ("article", "Representational State Transfer (Fielding, chapter 5)", "https://ics.uci.edu/~fielding/pubs/dissertation/rest_arch_style.htm", "Roy Fielding", "The original definition of REST.", False),
 "richardson": ("article", "Richardson Maturity Model", "https://martinfowler.com/articles/richardsonMaturityModel.html", FOWLER, "Levels of RESTfulness in practice.", False),
 "no-offset": ("article", "No Offset: keyset pagination", "https://use-the-index-luke.com/no-offset", "Markus Winand", "Why OFFSET is slow and how keyset pagination fixes it.", False),
 "slack-pagination": ("article", "Evolving API Pagination at Slack", "https://slack.engineering/evolving-api-pagination-at-slack/", "Slack Engineering", "Moving from offset to cursor pagination.", False),
 "google-compat": ("article", "Google API design guide: Compatibility", "https://cloud.google.com/apis/design/compatibility", "Google Cloud", "What counts as a breaking change.", False),
 "acl": ("article", "Anti-corruption Layer pattern", "https://learn.microsoft.com/en-us/azure/architecture/patterns/anti-corruption-layer", LEARN, "Translating between your model and a foreign or legacy one.", False),
 "fowler-eda": ("article", "What do you mean by \"Event-Driven\"?", "https://martinfowler.com/articles/201701-event-driven.html", FOWLER, "Four different things people mean by event-driven.", False),
 "outbox": ("article", "Pattern: Transactional outbox", "https://microservices.io/patterns/data/transactional-outbox.html", "microservices.io", "Publishing events reliably without dual writes.", False),
 "masstransit-outbox": ("article", "MassTransit: Transactional Outbox", "https://masstransit.io/documentation/patterns/transactional-outbox", "MassTransit", "The built-in EF Core outbox in MassTransit.", False),
 "confluent-outbox": ("article", "Reliable Microservices Data Exchange With the Outbox Pattern", "https://www.confluent.io/blog/reliable-microservices-data-exchange-with-the-outbox-pattern/", CONF, "Outbox plus CDC with Kafka.", False),
 "kafka-semantics": ("article", "Kafka documentation: delivery semantics", "https://kafka.apache.org/documentation/#semantics", "Apache Kafka", "At-most-once, at-least-once and exactly-once.", False),
 "confluent-delivery": ("article", "Message Delivery Guarantees", "https://docs.confluent.io/kafka/design/delivery-semantics.html", CONF, "Kafka's delivery guarantees explained.", False),
 "sb-dupdetect": ("article", "Azure Service Bus duplicate detection", "https://learn.microsoft.com/en-us/azure/service-bus-messaging/duplicate-detection", LEARN, "Broker-side de-duplication by message id.", False),
 "msio-saga": ("article", "Pattern: Saga", "https://microservices.io/patterns/data/saga.html", "microservices.io", "Maintaining consistency across services with compensations.", False),
 "confluent-ooo": ("article", "Out-of-order events", "https://developer.confluent.io/patterns/event-processing/out-of-order-events/", CONF, "Handling events that arrive out of order.", False),
 "stripe-test": ("article", "Stripe: test mode", "https://docs.stripe.com/test-mode", STRIPE, "A sandbox model worth copying for partner onboarding.", False),
 "wiremock": ("link", "WireMock documentation", "https://wiremock.org/docs/", "WireMock", "HTTP test doubles for integration testing.", False),
 "circuit-breaker": ("article", "Circuit Breaker pattern", "https://learn.microsoft.com/en-us/azure/architecture/patterns/circuit-breaker", LEARN, "Failing fast when a dependency is unhealthy.", False),
 "stripe-idem-blog": ("article", "Designing robust and predictable APIs with idempotency", "https://stripe.com/blog/idempotency", STRIPE, "Why and how Stripe uses idempotency keys.", False),
 "stripe-idem-api": ("article", "Stripe API: Idempotent requests", "https://docs.stripe.com/api/idempotent_requests", STRIPE, "Client-supplied Idempotency-Key semantics.", False),
 "sb-receive": ("article", "Service Bus performance: receive mode", "https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-performance-improvements#receive-mode", LEARN, "PeekLock versus ReceiveAndDelete.", False),
 "temporal-concepts": ("article", "Temporal documentation: concepts", "https://docs.temporal.io/concepts", "Temporal", "Workflows, activities, event history and replay.", False),
 "event-sourcing-fowler": ("article", "Event Sourcing", "https://martinfowler.com/eaaDev/EventSourcing.html", FOWLER, "Capturing all changes to application state as events.", False),
 "temporal-101": ("article", "Temporal: getting started", "https://learn.temporal.io/getting_started/", "Temporal", "Hands-on introduction to Temporal.", False),
 "brandur": ("article", "Implementing Stripe-like Idempotency Keys in Postgres", "https://brandur.org/idempotency-keys", "Brandur Leach", "A detailed Postgres implementation of idempotency keys.", False),
 "sb-dlq": ("article", "Service Bus dead-letter queues", "https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-dead-letter-queues", LEARN, "MaxDeliveryCount and automatic dead-lettering.", False),
 "confluent-errors": ("article", "Error handling patterns in Kafka", "https://www.confluent.io/blog/error-handling-patterns-in-kafka/", CONF, "Retries, dead-letter topics and poison pills.", False),
 "pg-locking": ("article", "Explicit locking", "https://www.postgresql.org/docs/current/explicit-locking.html", PG, "Row locks, table locks and advisory locks.", False),
 "ef-concurrency": ("article", "Handling concurrency conflicts", "https://learn.microsoft.com/en-us/ef/core/saving/concurrency", LEARN, "Optimistic concurrency with tokens and row versions.", False),
 "pg-indexes": ("article", "Indexes", "https://www.postgresql.org/docs/current/indexes.html", PG, "Multicolumn, partial and expression indexes.", False),
 "sql-temporal": ("article", "Temporal tables (SQL Server)", "https://learn.microsoft.com/en-us/sql/relational-databases/tables/temporal-tables", LEARN, "A built-in analog for querying historical row versions.", False),
 "pg-json": ("article", "JSON types", "https://www.postgresql.org/docs/current/datatype-json.html", PG, "json versus jsonb, operators and indexing.", False),
 "ef-json": ("article", "What's new in EF Core 7: JSON columns", "https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew#json-columns", LEARN, "Mapping owned types to JSON columns.", False),
 "pg-dont": ("article", "PostgreSQL wiki: Don't Do This", "https://wiki.postgresql.org/wiki/Don%27t_Do_This", "PostgreSQL wiki", "Common PostgreSQL anti-patterns.", False),
 "braintree": ("article", "Safe Operations For High Volume PostgreSQL", "https://www.braintreepayments.com/blog/safe-operations-for-high-volume-postgresql/", "Braintree Engineering", "Zero-downtime schema changes at scale.", False),
 "sql-maxopen": ("article", "database/sql: DB.SetMaxOpenConns", "https://pkg.go.dev/database/sql#DB.SetMaxOpenConns", GO, "Configuring Go's connection pool.", False),
 "sql-interface": ("article", "Go Wiki: SQLInterface", "https://go.dev/wiki/SQLInterface", GO, "Using database/sql well, including pooling.", False),
 "httptest": ("article", "net/http/httptest package", "https://pkg.go.dev/net/http/httptest", GO, "Test servers and response recorders.", False),
 "table-driven": ("article", "Go Wiki: Table-driven tests", "https://go.dev/wiki/TableDrivenTests", GO, "The idiomatic Go testing style.", False),
 "integration-tests": ("article", "Integration tests in ASP.NET Core", "https://learn.microsoft.com/en-us/aspnet/core/test/integration-tests", LEARN, "WebApplicationFactory and in-memory test servers.", False),
 "otel-concepts": ("article", "OpenTelemetry concepts", "https://opentelemetry.io/docs/concepts/", "OpenTelemetry", "Traces, metrics, logs and context propagation.", False),
 "confluent-monitoring": ("article", "Monitoring Kafka", "https://docs.confluent.io/platform/current/kafka/monitoring.html", CONF, "Broker metrics and consumer lag.", False),
 "ai-tracing": ("article", "Application Insights: distributed tracing", "https://learn.microsoft.com/en-us/azure/azure-monitor/app/distributed-tracing", LEARN, "Correlation across services in Azure.", False),
 "test-pyramid": ("article", "Test Pyramid", "https://martinfowler.com/bliki/TestPyramid.html", FOWLER, "Many unit tests, fewer integration and end-to-end tests.", False),
 "canary": ("article", "Canary release", "https://martinfowler.com/bliki/CanaryRelease.html", FOWLER, "Rolling out to a small share of users first.", False),
 "feature-toggles": ("article", "Feature toggles (aka feature flags)", "https://martinfowler.com/articles/feature-toggles.html", "Pete Hodgson", "Kinds of toggles, and how to manage them.", False),
 "github-eng": ("link", "GitHub Engineering blog", "https://github.blog/engineering/", "GitHub", "Includes posts on dark launches and safe rollouts.", False),
 "sre-monitoring": ("article", "Monitoring distributed systems", "https://sre.google/sre-book/monitoring-distributed-systems/", "Google SRE", "The four golden signals and alerting philosophy.", False),
 "pd-symptoms": ("article", "PagerDuty: Alert on symptoms", "https://response.pagerduty.com/before/alert_on_symptoms/", "PagerDuty", "Paging on user impact, not internal causes.", False),
 "pd-runbook": ("article", "What is a runbook?", "https://www.pagerduty.com/resources/learn/what-is-a-runbook/", "PagerDuty", "What to put in an operational runbook.", False),
 "sre-troubleshooting": ("article", "Effective troubleshooting", "https://sre.google/sre-book/effective-troubleshooting/", "Google SRE", "A systematic approach to incidents.", False),
 "amazon-lp": ("article", "Amazon Leadership Principles", "https://www.amazon.jobs/en/principles", "Amazon", "\"Are Right, A Lot\": a useful frame for judgement stories.", False),
 "sre-postmortem": ("article", "Postmortem culture: learning from failure", "https://sre.google/sre-book/postmortem-culture/", "Google SRE", "Blameless postmortems and how to write them up.", "added"),
 "google-review": ("article", "Google engineering practices: code review", "https://google.github.io/eng-practices/review/", "Google", "Guides for both reviewers and change authors.", "added"),
 "go-tour": ("link", "A Tour of Go", "https://go.dev/tour/", "The Go Authors", "The fastest structured way to ramp up on Go.", "added"),
 "sd-primer": ("link", "System Design Primer", "https://github.com/donnemartin/system-design-primer", "Donne Martin", "Practice questions with worked answers.", False),
 "data-partitioning": ("article", "Data partitioning guidance", "https://learn.microsoft.com/en-us/azure/architecture/best-practices/data-partitioning", LEARN, "Choosing partition keys and avoiding hot partitions.", False),
}

EZ = "ezCater prep"
A, B, C, D, E, F, G, H, I = ("Go Language & Idioms", "Go Concurrency", "API & Contract Design", "Event-Driven Architecture",
                             "Idempotency & Durable Execution", "Database & Data Modeling", "Testing & Operations",
                             "Ownership & Judgement", "Integration Hub Design")


def ex(testing, model, parallel=None):
    parts = [f"What they're testing: {testing}", f"Model answer: {model}"]
    if parallel:
        parts.append(f".NET parallel: {parallel}")
    return "\n\n".join(parts)


Q = [
 ("How does error handling work in Go, and why doesn't Go use exceptions?", [A, EZ], "medium",
  "Errors are ordinary return values checked at each call site, wrapped with %w and inspected with errors.Is/As; panic is reserved for unrecoverable bugs.",
  ["Go has try/catch under the names defer and recover, and idiomatic code panics on any expected failure such as a missing record or a closed file.",
   "Errors propagate up the stack automatically until a top-level handler catches them.",
   "Wrapping an error with %w discards the original, so errors.Is can no longer match it."],
  ex("Whether you've internalized Go's philosophy or are translating exception habits into Go syntax.",
     "Go treats errors as ordinary return values, not a separate control-flow channel. A function that can fail returns (result, error), and the caller checks err != nil immediately rather than letting failures propagate implicitly. This makes failure paths visible in the code, at the cost of verbosity. Errors can be wrapped with fmt.Errorf(\"doing X: %w\", err) to add context while preserving the original for errors.Is and errors.As.",
     "The sharpest philosophical difference from C#. In .NET, exceptions are the default for anything unexpected and can bubble to global middleware. Go treats all failure as values, even expected ones like \"not found\", so every call site needs an explicit decision. panic/recover exists, but idiomatic Go reserves it for truly unrecoverable programmer errors; using panic like a C# exception is a tell of someone still thinking in .NET."),
  ["go-errors", "go113-errors", "cs-exceptions"]),
 ("What's the difference between a pointer receiver and a value receiver on a Go method?", [A, EZ], "easy",
  "A value receiver works on a copy, so mutations are lost; a pointer receiver works on the original. If any method needs a pointer, use pointers for all.",
  ["They behave identically, because Go passes every struct by reference automatically, just like a class instance in C#.",
   "Pointer receivers copy the struct, while value receivers mutate the original.",
   "Mixing both receiver kinds on one type is the recommended idiom for clarity."],
  ex("Whether you understand Go's value semantics well enough to avoid subtle mutation and copying bugs.",
     "A method with a value receiver (func (s Subscriber) Name() string) operates on a copy; mutating fields doesn't affect the original. A pointer receiver (func (s *Subscriber) SetName(n string)) operates on the original. Rule of thumb: if any method needs a pointer receiver (to mutate, or because the struct is large), make all methods on that type use pointer receivers.",
     "Loosely like C# struct versus class. The twist: in Go everything defaults to value semantics unless you use a pointer, whereas in C# anything declared class is a reference. A C# developer's instinct is to assume Go structs behave like classes, and they don't unless you hold a pointer."),
  ["tour-pointers", "eff-pointers", "cs-value-types"]),
 ("How does Go's interface system differ from interfaces in C# or Java?", [A, EZ], "medium",
  "Go interfaces are satisfied implicitly by matching method sets, so small interfaces are defined at the point of use: accept interfaces, return structs.",
  ["A Go type must declare implements on every interface it satisfies, which is why large interface hierarchies are designed up front before any type exists.",
   "Types from third-party packages can never satisfy an interface you define later.",
   "Go interfaces can only contain fields, never methods."],
  ex("Understanding of structural typing, which changes how you'd design the adapter contract.",
     "Go interfaces are satisfied implicitly: a type has the right method signatures and the compiler matches it, with no implements keyword. You can define an interface after a type exists, describing only the behaviour a call site needs, and any type, even from a third-party library, satisfies it if the shapes line up.",
     "C# interfaces are nominal (class Adapter : IPartnerAdapter). In Go it's idiomatic to define small, narrow interfaces where they're used. For the Integration Hub, a new partner adapter just needs a Send(Event) error method to satisfy the platform's interface; it doesn't register anything."),
  ["tour-interfaces", "go-proverbs", "cs-interfaces"]),
 ("What's the difference between make([]T, 0) and var s []T, and when does it matter?", [A, EZ], "medium",
  "var s []T is a nil slice and make([]T, 0) is an empty non-nil one; most operations treat them alike, but nil marshals to JSON null and empty to [].",
  ["make([]T, 0) allocates a large default capacity, while var s []T can't be appended to until it has been initialized with make.",
   "They are identical in every way, including how encoding/json serializes them.",
   "A nil slice panics on len and range, so it must always be checked first."],
  ex("Attention to Go's nil-versus-empty slice distinction, a classic quick-fire question.",
     "var s []T creates a nil slice (len 0, cap 0, s == nil); make([]T, 0) creates a non-nil empty slice. len, append and range behave the same on both. It matters for JSON: a nil slice marshals to null, an empty slice to []. If an API promises an array is never null, initialize with make or check before marshaling.",
     "Directly analogous to a null List<T> versus new List<T>(), with the same JSON gotcha: System.Text.Json also serializes a null collection as null."),
  ["slices-intro", "faq-nil-error"]),
 ("What does defer do, and what's the common mistake with defer inside a loop?", [A, EZ], "medium",
  "defer runs a call when the enclosing function returns; deferring in a long loop delays every cleanup until the function ends, so resources pile up.",
  ["defer runs its call at the end of each loop iteration, so deferring Close() inside a loop releases every file as soon as that iteration finishes.",
   "defer runs the call immediately but asynchronously on a new goroutine.",
   "Deferred calls are skipped when the function returns an error or panics."],
  ex("Practical Go hygiene: resource cleanup and a classic footgun.",
     "defer schedules a call to run when the enclosing function returns, however it returns, and is used for cleanup right next to where a resource is opened. The mistake: deferring inside a loop with many iterations. None of the deferred calls run until the whole function returns, so resources stay open far longer than intended. Fix: extract the loop body into its own function so defer scopes to each iteration.",
     "Comparable to C#'s using, but inverted: a using inside a for loop disposes per iteration (block-scoped), while Go's defer in a loop waits for function end. Explaining that contrast shows real command of both languages."),
  ["eff-defer", "common-mistakes"]),
 ("How would you structure a Go project with multiple packages, and what goes in internal/?", [A, EZ], "medium",
  "cmd/ holds entry points and internal/ holds code only this module may import (compiler-enforced); the adapter contract other teams use stays exported.",
  ["Put everything, including the adapter contract that partner teams must implement against, under internal/ so that external code can depend on it safely.",
   "internal/ is only a naming convention, and the compiler does not enforce anything.",
   "Go projects must keep all code in a single package called main."],
  ex("Familiarity with Go project layout, relevant for a platform other teams integrate with.",
     "A typical layout separates cmd/ (entry points), internal/ (importable only from within the module, enforced by the compiler) and sometimes pkg/ (shared code; a debated convention). For the Integration Hub, the adapter contract other teams implement should live in an exported package, while routing and storage internals sit under internal/ so others can't depend on details that might change.",
     "internal/ is like C#'s internal access modifier, restricting a type to its assembly; Go enforces it per directory tree within a module. Marking shared-library types internal versus public to control what other teams reference is the same instinct."),
  ["module-layout", "package-names", "cs-access"]),
 ("What happens if you send on a closed channel, and what about receiving from one?", [A, EZ], "medium",
  "Sending on a closed channel panics; receiving returns the zero value immediately, and v, ok := <-ch reports ok == false. Only the sender closes.",
  ["Sending on a closed channel blocks until it's reopened, and receiving from one blocks forever, so a receiver can never tell a channel was closed.",
   "Both operations silently do nothing and return without any error.",
   "Receivers should close a channel once they've read enough values."],
  ex("Precise channel semantics, a common quick technical check.",
     "Sending on a closed channel panics. Receiving from a closed channel never blocks: it returns the zero value, and the two-value form (v, ok := <-ch) returns ok == false to distinguish closed from a real zero value. Convention: only the sender closes, to signal no more values; closing from the receiver or closing twice panics.",
     "The closest analog is a completed Channel<T> from System.Threading.Channels: reading after completion returns immediately and writing throws. BlockingCollection<T>.CompleteAdding() is an older, rougher parallel."),
  ["tour-range-close", "spec-close", "channels-dotnet"]),
 ("How does Go's garbage collector affect how you write a high-throughput service?", [A, EZ], "hard",
  "The GC is concurrent and low-pause, but allocation churn still costs CPU; profile with pprof, reuse buffers with sync.Pool, and avoid needless heap allocs.",
  ["It doesn't matter at all: Go has no garbage collector, because every value lives on the stack and is freed when its function returns.",
   "Disable the GC in production, since its pauses are always seconds long.",
   "Allocate more pointers, because heap allocations are cheaper than values."],
  ex("Whether you think about performance beyond \"write correct code and hope.\"",
     "Go's GC is concurrent and generally low-pause, so it rarely needs tuning, but heavy allocation churn still adds GC pressure and CPU overhead. Mitigations: reuse buffers via sync.Pool, prefer values over pointers where a heap allocation isn't needed, and profile with pprof before optimizing. For an integration platform this matters most in the hot path: validation and serialization.",
     "Comparable to .NET's generational GC with the same advice: avoid allocations in hot paths, use ArrayPool<T> or pooling, and profile (dotnet-trace) instead of guessing. Only the tool names change."),
  ["gc-guide", "pprof", "dotnet-gc"]),

 ("How would you fetch data from five APIs concurrently in Go and combine the results?", [B, EZ], "medium",
  "Start a goroutine per call writing to a channel or an indexed slice, wait with sync.WaitGroup, then close the channel; decide upfront how partial failures behave.",
  ["Call the five APIs one after another inside a single goroutine, because Go's scheduler parallelizes sequential HTTP calls on its own behind the scenes.",
   "Start the goroutines and read the results immediately without waiting for them to finish.",
   "Use a global variable that every goroutine appends to without any synchronization."],
  ex("Practical fluency with goroutines, channels and sync.WaitGroup; likely live-coding.",
     "Launch a goroutine per API call, each writing its result to a shared channel (or a pre-sized slice by index, which avoids a mutex). Use sync.WaitGroup to know when all have finished, then close the channel so a range over it terminates. Handle partial failure explicitly: does one failed call fail everything or just get omitted?",
     "Directly analogous to Task.WhenAll over a list of Task<T>. Goroutines are lighter-weight and have no async state machine; channels are the explicit way to get results back instead of an awaited return value."),
  ["tour-concurrency", "pipelines", "whenall"]),
 ("What is a race condition, and how would you detect one in Go?", [B, EZ], "medium",
  "Concurrent access to the same memory with at least one write and no synchronization; Go's built-in race detector (go test -race) reports the exact accesses.",
  ["A race condition is any slow goroutine, and you detect it by timing each function call and flagging whichever one finishes last in the benchmark.",
   "Go prevents races at compile time, so no runtime tooling is needed.",
   "Races only happen in programs that use more than one CPU core."],
  ex("Awareness of Go's built-in tooling, not just the concept.",
     "A race occurs when two goroutines access the same memory concurrently, at least one writes, and there's no synchronization, so the outcome is non-deterministic. Go ships a race detector (go test -race, go run -race) that instruments memory accesses and reports both conflicting accesses with stack traces. It's a standard part of Go CI.",
     ".NET has no built-in single-flag race detector as mature as Go's; you rely on review of lock and Interlocked use or platform tools. That Go's detector is a first-class test flag is worth mentioning as a genuine strength of the toolchain."),
  ["race-detector", "race-blog", "sync-primitives"]),
 ("What's the difference between a buffered and an unbuffered channel in Go?", [B, EZ], "medium",
  "An unbuffered send waits for a receiver (a rendezvous); a buffered channel accepts up to n values without one, decoupling producer and consumer.",
  ["An unbuffered channel stores an unlimited number of values, while a buffered one can hold only a single value at a time before every send blocks.",
   "Buffered channels are always faster, so unbuffered channels are deprecated.",
   "Only buffered channels can be closed or used with range."],
  ex("Whether you understand the synchronization implications, not just the syntax.",
     "An unbuffered channel (make(chan T)) makes send and receive rendezvous: the sender blocks until a receiver is ready, useful when you need that handoff. A buffered channel (make(chan T, n)) lets sends succeed without a waiting receiver, up to n, useful for decoupling speeds or for results := make(chan Result, len(items)) so goroutines don't block on send.",
     "Roughly a SemaphoreSlim(0)-style rendezvous versus a bounded BlockingCollection<T> or capacity-bounded Channel<T>: the same coupling-versus-decoupling trade-off."),
  ["tour-buffered", "concurrency-talk"]),
 ("How would you limit how many goroutines run concurrently, so you don't open 10,000 HTTP connections?", [B, EZ], "medium",
  "Use a buffered channel of capacity n as a semaphore, or a fixed pool of worker goroutines reading from a shared jobs channel.",
  ["Set GOMAXPROCS to the connection limit, because GOMAXPROCS caps the total number of goroutines a Go program may create at any one moment.",
   "Start all 10,000 goroutines and rely on the HTTP client to queue them safely.",
   "Call runtime.Gosched() in each goroutine to slow them down."],
  ex("The worker-pool and semaphore pattern, directly relevant to fanning out to many subscribers.",
     "Use a buffered channel as a semaphore: sem := make(chan struct{}, maxConcurrent); each goroutine sends into it before working and receives when done, so once it's full further sends block until a slot frees. Alternatively, run a fixed pool of worker goroutines reading from a jobs channel instead of one goroutine per item.",
     "Identical to wrapping tasks in SemaphoreSlim(maxConcurrent) or using Parallel.ForEachAsync with MaxDegreeOfParallelism."),
  ["pipelines", "foreachasync"]),
 ("What's the difference between concurrency and parallelism, and what does GOMAXPROCS control?", [B, EZ], "medium",
  "Concurrency structures work as independent pieces; parallelism runs them at the same instant. GOMAXPROCS sets how many OS threads run goroutines simultaneously.",
  ["They're synonyms, and GOMAXPROCS sets the maximum number of goroutines a program can create, which defaults to one per CPU core on the machine.",
   "Concurrency requires multiple cores, while parallelism can run on a single core.",
   "GOMAXPROCS controls the garbage collector's heap size target."],
  ex("Conceptual precision, a classic Rob Pike talking point.",
     "Concurrency is about structuring a program as independently progressing pieces (dealing with many things at once); parallelism is executing several at the same instant (doing many things at once). GOMAXPROCS sets how many OS threads run goroutines simultaneously, defaulting to the CPU count. A highly concurrent program can still run on one core by interleaving.",
     "The same distinction as async/await (concurrency: freeing a thread during I/O) versus Parallel.For or Task.Run across cores (CPU-bound parallelism). If you've explained why async isn't automatically faster, you've reasoned through this."),
  ["waza", "gomaxprocs"]),

 ("How would you version a public API so you can make breaking changes without breaking existing clients?", [C, EZ], "medium",
  "Prefer additive changes; when a break is unavoidable, version in the URL or a header and run both versions with a communicated deprecation timeline.",
  ["Make breaking changes in place and notify clients afterwards, since keeping two versions running in parallel doubles the code and is never worth the effort.",
   "Version every endpoint on every release, even for purely additive changes.",
   "Embed the version only in internal logs, so clients never need to send one."],
  ex("Whether you treat API evolution as an ongoing discipline, not a one-time decision.",
     "Prefer additive, backward-compatible changes (new optional fields, new endpoints) so most changes need no versioning. When a break is unavoidable, version explicitly, in the path (/v2/orders) or a header, and run both versions in parallel with a communicated deprecation timeline. For event contracts, include a version field in the payload so one topic can carry several versions during a migration.",
     "ASP.NET Core has first-class support via the Asp.Versioning package; the judgement (additive versus breaking, deprecation windows) is the same. In Go, versioning is usually explicit routing you write yourself."),
  ["aspnet-versioning-link", "tolerant-reader", "google-versioning"]),
 ("A partner team says your API response lacks a field they need. How do you handle it, and prevent it next time?", [C, EZ], "medium",
  "Add the field as an optional, additive change now; prevent repeats with consumer-driven contract tests and a published schema or OpenAPI spec.",
  ["Rename an existing field to the name they expect, which is the quickest fix, and then ask every other consumer to update their code to match.",
   "Tell them to parse the data out of a different endpoint's response instead.",
   "Add the field as required, so every consumer is forced to handle it immediately."],
  ex("Process maturity, not just a technical fix: the JD's self-service tooling and contracts.",
     "Immediate fix: add the field as optional and additive so no existing consumer breaks. Systemic fix: consumer-driven contract testing closes this gap; had the team published a contract of what they depend on, the gap could have surfaced in your CI first. Also propose better self-service discovery (a schema registry or published OpenAPI spec).",
     "Like an internal NuGet contracts library or a gateway with published Swagger docs: the fix isn't just adding the field, it's asking why nobody saw this coming, and the answer is usually better contract visibility."),
  ["pact", "cdc"]),
 ("What makes an API RESTful, and does the Integration Hub need to be strictly REST?", [C, EZ], "medium",
  "Resources at URLs, standard verbs, statelessness and meaningful status codes; use REST for subscription CRUD but messaging (Kafka) for the event flow.",
  ["Every endpoint must implement full HATEOAS and the event flow must also be synchronous REST calls, because mixing paradigms breaks consistency.",
   "An API is RESTful as long as it uses JSON, whatever the URLs and verbs look like.",
   "REST requires server-side sessions so clients don't resend context."],
  ex("Whether you treat REST as dogma or as one tool among several.",
     "Core REST ideas: resources identified by URLs, standard HTTP verbs mapped to actions, statelessness, and meaningful status codes. Most \"RESTful\" APIs are pragmatic subsets (few implement HATEOAS), which is fine. For the Integration Hub, subscription management is naturally REST-shaped CRUD, but the event flow is better modelled as asynchronous messaging (Kafka) than forced into request/response.",
     "ASP.NET Web API's controller-per-resource convention nudges toward the same pragmatic subset; the senior half of the question is knowing when not to force something into REST."),
  ["fielding", "richardson"]),
 ("How do you paginate an endpoint that could return millions of rows?", [C, EZ], "medium",
  "Use keyset (cursor) pagination, WHERE created_at > $last ORDER BY created_at LIMIT n, which stays fast and stable where OFFSET degrades.",
  ["Use OFFSET and LIMIT, because the database jumps straight to the requested offset in constant time, however deep the page and however many rows change.",
   "Return all rows in a single response and let the client page through them.",
   "Pick rows at random for each page, which avoids hot spots in the index."],
  ex("Awareness that offset pagination breaks down at scale.",
     "OFFSET 100000 LIMIT 20 gets slower as the offset grows, because the database still scans and discards the skipped rows, and it's unstable when rows are inserted or deleted between requests. Keyset pagination uses the last-seen sort key (WHERE created_at > $last_seen ORDER BY created_at LIMIT 20): consistent performance and stable results under concurrent writes.",
     "The same trade-off EF Core developers hit with .Skip().Take(), which compiles to offset SQL; keyset pagination has to be written by hand in EF too."),
  ["no-offset", "slack-pagination"]),
 ("How do you design an API so a partner integration built today doesn't break when you add a required field next year?", [C, EZ], "medium",
  "Never add a required field to an existing version: new fields are optional with defaults, and anything mandatory ships in a new version with deprecation.",
  ["Add the required field to the current version and reject requests without it, because partners are expected to update within a release cycle.",
   "Make every field required from day one, so nothing ever has to change later.",
   "Accept any payload without validation, so new fields never break anyone."],
  ex("Whether required fields in a growing contract are understood as a long-term liability.",
     "Never add a genuinely required field to an existing contract version: anything new is optional with a sensible default, or ships in a new explicit version old clients never see. If a field must eventually become mandatory, that's a deprecation process (announce, support both, monitor adoption, retire), not a flag flip.",
     "Like a public NuGet package where you can't add a required constructor parameter without breaking every caller: additive only, or a new major version."),
  ["google-compat", "tolerant-reader"]),

 ("How would you design a system that normalizes events from 50 partners, each with its own format, into one internal model?", [D, EZ], "hard",
  "Separate ingestion, a per-partner adapter that translates into a versioned internal model, and the internal routing bus, so one partner can't break the others.",
  ["Make all 50 partners send your internal format directly, and push their translation logic into each subscriber service that later consumes the events.",
   "Write one shared parser with a branch per partner inside a single function.",
   "Store each partner's raw payload and translate it only when a report is run."],
  ex("A near restatement of the actual job; expect a version of it in the technical round.",
     "Separate ingestion (accept the raw format, minimal validation) from translation (an adapter per partner mapping into your internal versioned event model) from the internal bus that routes normalized events to subscribers. Each adapter is isolated, so one partner's malformed payload or format change can't break the other 49. New partners self-serve: implement the adapter contract, register it, and the platform handles delivery, retries and routing.",
     "Architecturally an Anti-Corruption Layer, as in translating five shipping carriers' APIs into one IShippingProvider. Say it out loud if you've built something like this in .NET; it's a strong, honest answer even without Go production experience."),
  ["acl", "fowler-eda"]),
 ("How do you guarantee an event is never lost between your database write and publishing it to Kafka?", [D, EZ], "hard",
  "Transactional outbox: write the event to an outbox table in the same transaction as the change, then publish it by polling or CDC and mark it sent.",
  ["Publish to Kafka first and only then write to the database, because Kafka acknowledges every write durably, so the two systems can never disagree.",
   "Wrap the database write and the Kafka publish in a try/catch and retry both.",
   "Use a larger Kafka replication factor, which removes the need for an outbox."],
  ex("Whether you know the transactional outbox by name and reasoning.",
     "A database write and a broker publish are two systems with no shared transaction, so a crash between them loses the event. The outbox writes the event into an outbox table in the same transaction as the business change; a separate poller (or CDC reading the WAL, like Debezium) publishes it afterwards and marks it sent once confirmed.",
     "MassTransit's AddEntityFrameworkOutbox does this transparently with EF Core. A strong answer: \"MassTransit's EF outbox does this automatically; the pattern is the same in any language, and in Go I'd implement it by hand.\""),
  ["outbox", "masstransit-outbox", "confluent-outbox"]),
 ("A consumer processes the same Kafka message twice. Is that a bug?", [D, EZ], "medium",
  "No: Kafka delivers at least once, so redelivery is expected. The bug would be a consumer that isn't idempotent and double-applies the side effect.",
  ["Yes: Kafka guarantees exactly-once delivery by default, so a duplicate always means the broker is misconfigured and should be fixed on the cluster.",
   "Yes, and the fix is to commit offsets before processing each message.",
   "No, and consumers can safely ignore duplicates because side effects never repeat."],
  ex("Whether you understand Kafka's actual delivery guarantee.",
     "Kafka's default is at-least-once delivery, so redelivery after a crash or rebalance is normal. The bug would be a consumer that isn't idempotent and double-applies the side effect. Fix it at the consumer with an idempotency check, not by forcing Kafka into exactly-once (possible in narrow transactional cases, rarely the simplest answer).",
     "A property of the messaging system, not the language. Azure Service Bus's PeekLock mode and RabbitMQ have similar at-least-once defaults, so experience there transfers directly."),
  ["kafka-semantics", "confluent-delivery", "sb-dupdetect"]),
 ("What's the difference between choreography and orchestration, and which fits the Integration Hub?", [D, EZ], "hard",
  "Choreography lets services react to events with no coordinator; orchestration has a central engine like Temporal. Use orchestration for the core flow, choreography for fan-out.",
  ["Orchestration means every subscriber reacts on its own, while choreography uses a central workflow engine, so Temporal is a choreography tool by design.",
   "Use one central workflow that controls every downstream team's business logic.",
   "They are identical, so the choice only affects naming."],
  ex("A named architectural distinction directly relevant to how the platform's flows are structured.",
     "Choreography: each service reacts to events independently and the flow emerges from local decisions; decoupled, but the end-to-end flow is hard to see. Orchestration: a central coordinator (Temporal) directs each step and tracks progress. For the Integration Hub: orchestration for the platform's own core delivery flow, so failure, retry and replay state is visible, and choreography for fan-out, where each subscriber decides what to do with an event.",
     "A MassTransit state-machine saga is orchestration; services that just react to messages via consumers are choreography. Name honestly which you've built."),
  ["msio-saga", "fowler-eda"]),
 ("A partner sends events out of order, with \"order shipped\" arriving before \"order created\". How do you handle it?", [D, EZ], "hard",
  "Assume no ordering: buffer briefly and reorder, make state transitions order-tolerant and idempotent, or park events that reference unseen parents and retry.",
  ["Reject the partner's integration, since events generated in order are guaranteed to arrive in order across the internet and any deviation is a partner bug.",
   "Process events by arrival time and overwrite state with whatever came last.",
   "Sort all events globally by timestamp before processing any of them."],
  ex("Real-world messiness handling, since partner-controlled contracts rarely behave perfectly.",
     "Layered options: buffer and reorder within a short window if delays are small and bounded; make consumers tolerate out-of-order arrival with idempotent, order-independent transitions (\"shipped\" sets a flag instead of assuming a prior state); or park an event that references a not-yet-seen parent and retry after a delay. The wrong answer is assuming external events arrive in logical order.",
     "The same problem space as out-of-order messages in Service Bus sessions, or a payment processor's \"pending\" and \"succeeded\" webhooks arriving in either order."),
  ["confluent-ooo"]),
 ("How would you let a new partner test their integration without touching production data?", [D, EZ], "medium",
  "Provide a sandbox with production's contract but isolated data, synthetic event generators, versioned example payloads and a schema-validation endpoint.",
  ["Give the partner read access to a copy of production data, since realistic data matters more than isolation and partners can be trusted with it.",
   "Let partners test directly against production during off-peak hours.",
   "Skip testing and fix contract mismatches once they show up in production."],
  ex("A direct match to the JD's self-service tooling and developer experience.",
     "A sandbox environment mirroring production's contract but backed by isolated test data, plus synthetic event generators so a new adapter can be exercised without a live partner. Add clear, versioned example payloads and a validation endpoint that checks outgoing events against the schema before they reach the real pipeline.",
     "Like Stripe's test mode, or a WireMock test-double server for a .NET team building against a third-party contract."),
  ["stripe-test", "wiremock"]),
 ("Do you need both a dead-letter queue and a circuit breaker?", [D, EZ], "medium",
  "Yes: a circuit breaker stops calls to a fully down dependency, while a DLQ quarantines individual messages that fail even when the dependency is healthy.",
  ["No: a circuit breaker already dead-letters every failing message automatically, so adding a separate dead-letter queue just duplicates the same protection.",
   "No: retries make both unnecessary as long as they're unlimited.",
   "Yes, but only one may be active at a time."],
  ex("Whether you see the two as complementary rather than redundant.",
     "They solve different failure shapes. A circuit breaker protects against a fully down dependency by stopping calls for a cooldown, avoiding wasted retries. A dead-letter queue catches individual messages that fail even when the dependency is healthy (a malformed payload, a permanent rejection). Use the breaker to stop hammering a dead endpoint and the DLQ to quarantine messages that fail while it's up."),
  ["circuit-breaker"]),

 ("How would you implement idempotency for an endpoint that processes payments?", [E, EZ], "hard",
  "Require a client-supplied idempotency key, insert it under a unique constraint in the same transaction as the side effect, and return the stored result on repeats.",
  ["Hash the request body and compare it to the last ten requests in memory, silently doing nothing on a match so the client doesn't receive a duplicate response.",
   "Check whether the key exists after charging the card, then roll back if it does.",
   "Rely on the payment provider to reject duplicates, so no key is needed on your side."],
  ex("Precision; payments are the canonical example because subtle mistakes are expensive.",
     "Require the caller to supply an idempotency key (a UUID per logical attempt). Atomically check-and-insert it into a table with a unique constraint before any side effect, in the same transaction as the side effect. If the key exists, return the stored result of the original attempt rather than reprocessing, and don't silently no-op, because the caller still needs a response.",
     "Stripe's .NET SDK supports RequestOptions.IdempotencyKey; if you've integrated Stripe you've used this from the client side. Implementing it server-side in Go is the same idea, inverted."),
  ["stripe-idem-blog", "stripe-idem-api"]),
 ("What's the difference between at-most-once, at-least-once and exactly-once delivery, and which suits the Integration Hub?", [E, EZ], "hard",
  "At-most-once can lose messages, at-least-once can duplicate them, and exactly-once is effectively at-least-once plus idempotency. Choose at-least-once with idempotent consumers.",
  ["Choose exactly-once delivery, because modern brokers guarantee it end to end across independent systems at no extra cost or added complexity.",
   "Choose at-most-once, since losing an occasional event is simpler than handling duplicates.",
   "At-least-once never produces duplicates, so idempotency isn't required."],
  ex("Precise definitions plus a defensible choice; answering \"exactly-once\" without the cost is the trap.",
     "At-most-once: zero or one deliveries, so silent loss is possible. At-least-once: one or more, no silent loss but duplicates. Exactly-once: the ideal, but across independent systems it usually means effectively-once via at-least-once plus idempotent consumers. For the Integration Hub: at-least-once with idempotent consumers everywhere; simpler and more robust.",
     "The same trade-off as Service Bus's PeekLock (at-least-once, explicit completion) versus ReceiveAndDelete (at-most-once)."),
  ["confluent-delivery", "sb-receive"]),
 ("How does Temporal achieve durability without explicit checkpoint and recovery code?", [E, EZ], "hard",
  "It records each step in an append-only event history; after a crash a worker replays the workflow, reusing recorded activity results, so the code must be deterministic.",
  ["It snapshots the whole worker process memory to disk every few seconds and restores the latest snapshot after a crash, so any code works unchanged.",
   "It re-runs every activity from scratch after a crash, so side effects simply repeat.",
   "It stores the workflow's state in the client application's database tables."],
  ex("Whether you understand the event-sourcing mechanism underneath, not just \"it works.\"",
     "Temporal records every meaningful step (activity start and completion, timers, signals) in an append-only event history. If the worker crashes, another replays the history against the same workflow code, but replayed activity calls return their recorded results instead of re-executing, so the code arrives back where it crashed and continues. That's why workflow code must be deterministic: no direct randomness or wall-clock reads.",
     "The same idea as event sourcing (rebuilding state by replaying a log), as with EventStoreDB or Marten; Temporal applies it to orchestration logic rather than domain state."),
  ["temporal-concepts", "event-sourcing-fowler", "temporal-101"]),
 ("What's a compensating transaction, and when do you need one instead of a retry?", [E, EZ], "medium",
  "When a step already succeeded but a later step failed: instead of retrying, run an explicit, business-aware inverse such as sending a cancellation.",
  ["A compensating transaction is the database rolling back automatically when a later step fails, which works across services because every system shares one log.",
   "It means retrying the failed step until it eventually succeeds.",
   "It's only needed for read-only operations that never change state."],
  ex("Whether you distinguish retrying an operation from undoing a completed one.",
     "Retrying assumes the operation hasn't succeeded yet. A compensating transaction is needed when an operation did succeed but a later step failed, so the completed step must be deliberately undone (a partner was notified but billing failed, so you send a cancellation rather than re-notifying). Compensations aren't automatic rollbacks; they're inverse actions designed per step, and not everything has a clean inverse.",
     "If you've built a MassTransit state-machine saga or hand-rolled compensation in an order pipeline, you've designed these; only the orchestration mechanism differs."),
  ["msio-saga"]),
 ("Your idempotency key is a hash of the request body. What could go wrong?", [E, EZ], "hard",
  "Different requests with identical bodies collide, and retries that vary any field (like a timestamp) hash differently and slip through; use a client-supplied key.",
  ["Nothing can go wrong, because a cryptographic hash guarantees that two logically identical requests always produce the same key, whatever metadata changes.",
   "Hashing is too slow for idempotency, so keys should be random per request.",
   "A body hash makes retries impossible, because every retry is always rejected."],
  ex("Whether you've thought through edge cases of key design, not just the existence of a key.",
     "Hashing the body dedupes identical retries, but two genuinely different requests with the same body collide, and a client that sends the same logical operation with slightly different metadata (a timestamp) gets a different hash each time, silently defeating deduplication. A client-supplied key representing \"this one logical attempt\" is more robust.",
     "This is why Stripe requires the client to generate and send the key explicitly rather than deriving it from the body."),
  ["stripe-idem-api", "brandur"]),
 ("How would you handle a poison-pill message that crashes your consumer every time?", [E, EZ], "medium",
  "Catch the failure instead of crashing, and cap attempts per message so it moves to a dead-letter queue instead of retrying forever.",
  ["Retry it indefinitely with a short delay, because given enough attempts every message eventually succeeds and dead-lettering hides real bugs.",
   "Restart the whole consumer group whenever the message is read.",
   "Delete the topic partition that contains the message."],
  ex("Recognition of a failure mode that naive retry logic makes worse.",
     "Without a cap, a message that crashes the consumer causes a restart, a re-read (it was never acknowledged) and another crash: an infinite loop that can take down the consumer group. Fix it in two parts: catch and log the failure so the consumer keeps processing other messages, and enforce a maximum attempt count, after which the message goes to the DLQ. \"Retry forever\" is never the right default.",
     "Azure Service Bus's MaxDeliveryCount dead-letters a message automatically after N failed deliveries: the platform-native version of this pattern."),
  ["sb-dlq", "confluent-errors"]),

 ("Two requests race to update the same order's status. How do you prevent a lost update?", [F, EZ], "hard",
  "Under read committed a plain transaction isn't enough: lock the row with SELECT ... FOR UPDATE, or use optimistic concurrency with a version column.",
  ["Wrapping both updates in transactions is enough, because PostgreSQL's default isolation level serializes all writes to the same row automatically.",
   "Use a longer database timeout so the second request waits its turn.",
   "Cache the order in memory and update the cache instead of the database."],
  ex("Practical knowledge of database locking, not just \"use a transaction.\"",
     "Under Postgres's default read committed, both transactions can read the old value before either commits, and the second write overwrites the first. Fix with row locking (SELECT ... FOR UPDATE) so the second blocks until the first commits, or optimistic concurrency with a version column (UPDATE ... WHERE id = $1 AND version = $2, checking rows affected) and a retry on conflict.",
     "Exactly what EF Core's optimistic concurrency (a RowVersion column and DbUpdateConcurrencyException) is for; in Go with Postgres the version check is just explicit in your SQL."),
  ["pg-locking", "ef-concurrency"]),
 ("How would you design a schema that supports replaying events from an arbitrary point in the past?", [F, EZ], "medium",
  "Store every accepted event durably with type, version, payload, idempotency key and created_at, index the time column, and replay through the same idempotent path.",
  ["Keep only the latest event per entity and rebuild older history from application logs whenever a replay is needed, since logs record every event anyway.",
   "Store events in Kafka only, with a retention of a few hours.",
   "Replay by re-sending events directly to subscribers, skipping the idempotency check."],
  ex("Whether you treat the event log as a durable, queryable source of truth.",
     "Store every accepted event durably: an events table with id, type, version, payload, idempotency_key and created_at, indexed on created_at and type. Replay becomes a query (WHERE created_at BETWEEN $1 AND $2) feeding rows back through the same ingestion and routing path, reusing the idempotency check so already-delivered events aren't duplicated downstream.",
     "Structurally the same as an audit or event-sourcing table in SQL Server with EF: append-only, timestamp-indexed, queried by range."),
  ["pg-indexes", "event-sourcing-fowler", "sql-temporal"]),
 ("When would you use a JSONB column in Postgres instead of a fully normalized schema?", [F, EZ], "medium",
  "JSONB for variable payloads you rarely filter on; real indexed columns for fields you query, filter or join on, often both in one hybrid table.",
  ["Always prefer JSONB, because Postgres indexes every key inside it automatically and it is faster to filter than regular columns for any query shape.",
   "Never use JSONB, since Postgres can't store or query JSON at all.",
   "Store the idempotency key and event type inside the JSONB blob only."],
  ex("Practical schema-design judgement, relevant to storing flexible event payloads.",
     "JSONB fits data whose shape varies by event type or version and isn't queried by its internal fields often, such as the payload itself, avoiding an ever-migrating column-per-field schema. Structured columns fit what you query, filter, index or join on and whose shape is stable (idempotency key, type, status, timestamps). The events table is a hybrid: fixed columns plus a JSONB payload.",
     "EF Core's JSON column mapping exists for exactly this hybrid case."),
  ["pg-json", "ef-json"]),
 ("How would you add a NOT NULL column to a production Postgres table without downtime?", [F, EZ], "hard",
  "Add it as nullable, deploy code that writes it, backfill in batches, then add the NOT NULL (or a validated CHECK) once no nulls remain.",
  ["Add the column as NOT NULL with a default in one migration during peak traffic, since running application code never inserts rows while a migration runs.",
   "Drop and recreate the table with the new column, then reload the data.",
   "Add the column as NOT NULL first and backfill it afterwards."],
  ex("Operational schema-change discipline, a common senior trap question.",
     "Adding NOT NULL in one step can rewrite or validate the whole table under a lock, and the constraint immediately breaks in-flight inserts from code that doesn't supply the field yet. The safe sequence: add the column nullable, deploy code that writes it, backfill existing rows in batches, then add NOT NULL (or a CHECK validated separately) once no nulls remain; each step deployable and reversible.",
     "The same multi-step discipline as splitting an EF Core migration across deploys: add nullable, backfill, then enforce."),
  ["pg-dont", "braintree"]),
 ("What's a connection pool, and why does it matter more in Go than you might expect from .NET?", [F, EZ], "medium",
  "Reuse open connections instead of opening one per query; Go's database/sql defaults (unlimited open, 2 idle) usually need explicit tuning.",
  ["Go's database/sql opens a new connection per query and has no pool, so you must build one yourself; its defaults cap connections at your CPU count.",
   "Connection pooling only matters for read replicas, never the primary.",
   "Setting MaxOpenConns to unlimited is the safest production default."],
  ex("Awareness of database/sql's pooling behaviour, which feels less automatic than EF Core's.",
     "A pool reuses open connections across requests instead of paying TCP and authentication per query. database/sql manages one, but its defaults (MaxOpenConns unlimited, MaxIdleConns = 2) are often wrong for production; unbounded open connections under load can exceed Postgres's max_connections and fail during spikes. Tune SetMaxOpenConns, SetMaxIdleConns and SetConnMaxLifetime.",
     "ADO.NET and EF Core pool transparently with saner defaults; in Go the configuration is explicit, worth knowing cold."),
  ["sql-maxopen", "sql-interface"]),

 ("How would you unit test a Go function that calls an external partner API?", [G, EZ], "medium",
  "Depend on a small interface (PartnerClient) and swap in a fake in tests; use httptest.NewServer when you want to exercise the real HTTP client code.",
  ["Replace http.DefaultClient globally inside the test, so that every package in the test binary uses your mock without any changes to the production code.",
   "Call the real partner API from unit tests, so the tests prove the integration works.",
   "Skip unit tests for code that does I/O and rely on end-to-end tests."],
  ex("Whether you reach for interfaces to isolate the network call rather than mocking http.DefaultClient globally.",
     "Define a small interface (PartnerClient with Send(Event) error) instead of calling http.Post inline. Production uses a real implementation; tests use a fake that returns canned responses or errors, so retry, error-handling and idempotency logic are tested without the network. httptest.NewServer spins up a real local server for integration-style tests of the HTTP code path.",
     "Equivalent to injecting IHttpClientFactory or a custom interface and substituting a mock (Moq, NSubstitute); Go uses implicit interfaces instead of a DI container registering the mock."),
  ["httptest", "table-driven", "integration-tests"]),
 ("Production is dropping events intermittently. How would you debug it?", [G, EZ], "hard",
  "Trace known-dropped events by correlation id, check dead-letter contents and consumer lag for that window, and only then suspect silent, unlogged loss.",
  ["Restart every consumer and redeploy the latest build first, since intermittent drops are almost always cleared by a restart and need no investigation.",
   "Add more Kafka partitions, which fixes dropped events in most cases.",
   "Assume silent data loss in Kafka and open a ticket with the broker vendor."],
  ex("A structured incident-response approach, not just \"I'd check the logs.\"",
     "Start with observability: search logs and traces by correlation id for a few dropped events to see which hop they stopped at. Check dead-letter counts and contents for the window: if events are there, the drop is a caught failure with a stored reason. Check consumer lag: rising lag suggests a slow or crashing consumer, not loss. Only then is silent, unlogged loss the working theory.",
     "The method is identical in .NET with Application Insights: operation_Id instead of a hand-rolled correlation header, same sequence."),
  ["otel-concepts", "confluent-monitoring", "ai-tracing"]),
 ("What distinguishes unit, integration and contract tests, and where does each fit in the Integration Hub?", [G, EZ], "medium",
  "Unit tests isolate logic, integration tests cover real Postgres and Kafka wiring, and contract tests protect the adapter interface other teams build against.",
  ["Contract tests replace integration tests by running the full system end to end against production, so unit tests aren't needed for platform code.",
   "Unit tests should use the real database so they catch wiring problems.",
   "Integration tests are only for the front end; back ends need unit tests only."],
  ex("A structured testing vocabulary, matching the JD's quality mindset.",
     "Unit tests exercise one function or type with dependencies mocked (idempotency logic, retry classification). Integration tests exercise real interactions with Postgres and a Kafka broker via Docker, verifying the wiring. Contract tests verify producer and consumer expectations still match without a full environment. Unit tests dominate core logic, integration tests cover infrastructure wiring, contract tests protect the adapter interface.",
     "xUnit or NUnit unit tests, WebApplicationFactory integration tests and Pact contract tests: the same pyramid with different tooling."),
  ["test-pyramid"]),
 ("How would you roll out a risky change to the Integration Hub without risking all partner traffic?", [G, EZ], "medium",
  "Canary to a small share of traffic or low-risk partners, gate behaviour behind feature flags, or shadow-launch and compare outputs without using them.",
  ["Deploy to every instance at once during a quiet hour, since rolling back a full release is faster than managing a gradual rollout across partners.",
   "Ask partners to test the change in production for you before launch.",
   "Skip monitoring during the rollout so alerts don't distract the team."],
  ex("Safe deployment practice, tied to the JD's safe rollout language.",
     "A canary (route a small percentage of traffic, or a few low-risk partners, to the new version and watch error rates); feature flags to toggle behaviour without redeploying; or a shadow launch (run new logic alongside old and compare, using only the old result) to validate correctness first. For a new routing algorithm, shadow mode gives real production comparison with zero delivery risk.",
     "Azure App Service deployment slots with traffic percentages, or Microsoft.FeatureManagement and LaunchDarkly: the same practice with different tooling."),
  ["canary", "feature-toggles", "github-eng"]),
 ("How do you decide what should page someone at 3am versus just log a warning?", [G, EZ], "medium",
  "Page on user-impacting symptoms that need a human now, such as rising DLQ depth or a partner fully down; log everything else, to avoid alert fatigue.",
  ["Page on every warning and every retried message, because over-alerting is always safer than missing an incident and engineers can mute what they don't need.",
   "Never page at night; collect every problem for the morning stand-up.",
   "Page only when CPU usage crosses a fixed threshold on any host."],
  ex("On-call and alerting judgement; the JD mentions an on-call rotation they keep uneventful.",
     "Page on symptoms that are user- or business-impacting and need a human now: DLQ depth past a threshold, a partner integration fully down, elevated ingestion error rates. Log or notify non-urgently for informative things: a message retried then succeeded, a background job running slow. Alert on symptoms of real or imminent impact, not every internal anomaly; over-alerting causes fatigue, which is itself a reliability risk.",
     "The same philosophy applies to Application Insights alert rules or Datadog monitors."),
  ["sre-monitoring", "pd-symptoms"]),
 ("What would you put in a runbook for the Integration Hub's on-call engineer?", [G, EZ], "medium",
  "Map each alert to where to look, likely causes and safe first actions, plus how to replay events, check consumer lag and escalate.",
  ["A full architecture history of the platform, so the on-call engineer understands every design decision before taking any action during an incident.",
   "Just the phone number of the engineer who built the system.",
   "Commands to drop and recreate topics, so incidents can be reset quickly."],
  ex("Operational thinking beyond writing code, including tooling non-engineers can use.",
     "Map specific alert conditions to first actions: for \"DLQ depth alert for partner X\", where to look (a dashboard or query), likely causes (partner outage, bad deploy, schema mismatch) and the safe first response (nothing destructive; check before acting). Document how to replay a batch of events, check consumer lag, and whom to escalate to, so someone unfamiliar with the internals can handle common cases at 3am."),
  ["pd-runbook", "sre-troubleshooting"]),

 ("How should you answer \"tell me about a technical decision you made with incomplete information\"?", [H, EZ], "medium",
  "Tell a real story where you decided: what was unclear, what you chose and why, what you'd change, and how you validated it afterwards.",
  ["Describe a situation where your manager eventually decided for you, since showing you deferred to authority under uncertainty is the safest answer.",
   "Give a hypothetical answer about what you would do, rather than a real story.",
   "Say you avoid decisions until all information is available."],
  "What they're testing: A direct match to the JD's \"comfort making decisions with an incomplete picture.\" They want a real story, not a hypothetical.\n\nHow to prepare: Pick a real example where you designed rather than just implemented, such as the NTT Data microservices architecture or the Andritz real-time pipeline. Structure it: what was unclear, what you decided anyway and why, what you'd do differently with more information, and how you validated the decision (metrics, feedback, it held up in production). Avoid a story where someone else resolved the ambiguity for you.",
  ["amazon-lp"]),
 ("How do you decide when to use AI-assisted tooling and when rigor matters more?", [H, EZ], "medium",
  "AI helps with boilerplate, scaffolding and exploring unfamiliar APIs; slow down and review closely for money, concurrency, idempotency, security and live migrations.",
  ["Use AI-generated code everywhere without extra review, because AI tools are most reliable on exactly the concurrency and security code that's hardest to write.",
   "Never use AI tools, since they can't help with any part of back-end work.",
   "Only use AI to write tests, and never production code."],
  "What they're testing: A direct match to the JD's \"AI-assisted delivery fluency, and clear judgment on where it helps vs. where rigor matters.\"\n\nModel answer shape: AI tools are strong for boilerplate, first-draft scaffolding and exploring an unfamiliar API quickly, which is genuinely useful when ramping up on Go. Rigor matters more, and AI-generated code needs closer review, for anything touching money, idempotency or concurrency logic, security boundaries (secrets, auth) or live database migrations: exactly this role's domain. A concrete personal example of each lands better than a generic policy.",
  ["google-review"]),
 ("How should you answer \"tell me about a time you learned a new technology quickly to deliver something\"?", [H, EZ], "easy",
  "Use a real example (such as RabbitMQ/InfluxDB or Python/Node) and frame the Go ramp-up as the same proven pattern repeating.",
  ["Claim existing production experience in Go even if you don't have it, because admitting you're still learning the language is always disqualifying.",
   "Explain that you prefer to stay in the technologies you already know.",
   "Describe a technology you read about but never actually delivered with."],
  "What they're testing: Directly relevant to your situation, ramping up on Go under time pressure; a chance to tell a true, on-topic story.\n\nHow to prepare: Use a real example (RabbitMQ and InfluxDB at Andritz, or picking up Python and Node at Coderoad) and be honest that the Go ramp-up for this role is the same pattern repeating. Framed as \"here's my track record of getting productive in a new stack fast\", backed by a concrete prior example, it's a plus, not a liability.",
  ["go-tour", "amazon-lp"]),
 ("How do you approach code review, both giving and receiving it?", [H, EZ], "easy",
  "Separate real bugs and security issues from style preferences, suggest concrete alternatives, and review AI-generated code hardest in risky areas.",
  ["Treat every comment as a blocking change request regardless of severity, and avoid suggesting alternatives so the author learns to find the fix themselves.",
   "Approve quickly without reading, since trust matters more than review.",
   "Only review code from senior engineers, since juniors' code is reviewed by others."],
  "What they're testing: Collaboration style, relevant to a role building tooling and standards other teams will use.\n\nHow to prepare: Distinguish comments by severity (a genuine bug or security issue versus a style preference), explain how you give actionable feedback (suggest a concrete alternative, don't just flag a problem), and mention how AI-assisted changes shift your review posture: reviewing AI-generated code for the same risk categories as before, such as concurrency, security and money-handling logic.",
  ["google-review"]),
 ("How should you describe a production incident you were involved in?", [H, EZ], "easy",
  "Cover what broke, how it was detected, the immediate fix, the root cause, and above all what changed afterwards so it can't silently recur.",
  ["Focus on how quickly you personally fixed it and who caused it, leaving out the follow-up work because postmortems are mostly paperwork that interviewers skip.",
   "Only mention incidents that took down the whole company.",
   "Say you've never been involved in an incident."],
  "What they're testing: Real incident experience and whether you drive follow-through (a postmortem, an actual fix) rather than just firefighting.\n\nHow to prepare: Structure it as what broke, how it was detected, the immediate fix, the root cause, and, most important, what changed afterwards (a new alert, a new test, a runbook entry) so the same failure can't recur silently. A smaller \"caught a bug before it became one\" story is fine; the interviewer is gauging your instinct toward systemic fixes, not the size of the fire.",
  ["sre-postmortem", "sre-troubleshooting"]),

 ("When asked to \"design the Integration Hub\", what should you do first?", [I, EZ], "medium",
  "Clarify scope out loud: partner count and peak events/sec, push or pull, latency needs and delivery guarantees, and state your assumptions.",
  ["Start drawing Kafka, Temporal and the outbox straight away, because asking questions signals uncertainty and wastes the limited time of the interview.",
   "Ask the interviewer to design it first, then critique their design.",
   "Pick the most scalable architecture possible, regardless of the stated scale."],
  "Step 1 of the walkthrough: clarify scope and requirements, always out loud.\n\nAsk how many partners and events per second at peak (assume dozens of partners, low thousands per second), whether partners push webhooks or you poll them (assume inbound webhooks), what latency is acceptable (seconds), and whether exactly-once is a hard requirement (assume at-least-once with idempotent consumers, and say why). Stating assumptions aloud rather than silently picking them is itself part of what's evaluated: it shows you know these are real design decisions, not defaults.\n\nThen draw the pipeline: ingestion API (HMAC verification, per-partner rate limits), schema validation, outbox plus DB in one transaction, Kafka partitioned by a stable key, independent consumer groups per subscribing team, idempotency checks, and a dead-letter table, with correlation ids and secrets management cutting across.",
  ["sd-primer"]),
 ("In the Integration Hub's ingestion path, where does the idempotency check belong relative to the outbox insert?", [I, EZ], "hard",
  "Before the outbox insert and in the same transaction, so a partner's retried webhook is rejected as a duplicate and never reaches the outbox.",
  ["After the event has been published to Kafka, so that every consumer can decide independently whether a partner's retried webhook was really a duplicate.",
   "In a separate transaction after the outbox insert has committed.",
   "Nowhere; partners never retry webhooks, so duplicates can't happen."],
  "Deep dive from the walkthrough: \"How do you handle a partner retry causing a duplicate?\"\n\nCheck the idempotency key at ingestion before the outbox insert, inside the same transaction, so a duplicate never even reaches the outbox. The outbox row and the business write commit atomically, which is the point where \"we accepted this event\" becomes durable regardless of whether Kafka is reachable; the background publisher retries until the row is published.\n\nTrade-off worth naming: putting the outbox at the ingestion boundary is simpler than trying to make Kafka transactional with the source database, and doesn't require Kafka transactions spanning services you don't own.",
  ["outbox", "stripe-idem-api"]),
 ("If the Integration Hub must handle 10x the partners, what is the main bottleneck to watch?", [I, EZ], "hard",
  "The single Postgres instance behind the outbox: ingestion scales horizontally and consumers scale with partitions, but write volume eventually needs sharding.",
  ["The stateless ingestion API, because it can't run more than one instance behind a load balancer and therefore caps the platform's throughput entirely.",
   "Kafka consumer groups, which can never have more than one consumer each.",
   "The correlation-id middleware, which serializes all requests."],
  "Deep dive from the walkthrough: \"How do you scale this to 10x the partners?\"\n\nKafka scales horizontally by adding consumer instances per group, up to the partition count. The ingestion API scales behind a load balancer because it's stateless. The bottleneck to watch is the single Postgres instance backing the outbox: past a certain write volume, sharding or read replicas become a real conversation, worth naming even if you wouldn't build it on day one.\n\nRelated trade-offs to say out loud: at-least-once plus idempotent consumers over exactly-once; orchestration (Temporal) for the core pipeline but choreography for subscriber reactions, since one workflow controlling every downstream team would recreate the coupling the platform exists to remove.",
  ["data-partitioning"]),
]


# Lengthen the leading distractor where it came out shorter than the correct
# answer, so length doesn't give the answer away (see gen_lib.build).
LONGER = {
 1: ", which is why the standard library never returns error values",
 2: ", and a pointer receiver is only needed when the method is called from another package",
 4: ", which is why idiomatic Go code always prefers make over var for every slice",
 5: ", and nothing piles up even in very long-running loops",
 8: ", which also makes pprof and sync.Pool pointless",
 9: ", merging the responses once they all arrive",
 13: ", so raising it always makes any program faster",
 15: ", since renaming a field is not a breaking change for JSON consumers",
 18: ", which is how additive contract evolution is meant to work",
 20: ", even if the process crashes between the two calls",
 23: ", so reordering logic is never needed on your side",
 26: ", which also survives restarts and works across instances",
 28: ", and its activities run outside the workflow history",
 32: ", which also keeps every query fast",
 39: ", since contract tests already exercise the real database and broker",
}
Q = [(p, t, d, c, [w[0].rstrip('.') + LONGER[i] + '.'] + w[1:] if i in LONGER else w, e, m)
     for i, (p, t, d, c, w, e, m) in enumerate(Q, 1)]

assert len(Q) == 50, len(Q)
build("ezCater Integration Hub interview questions", M, Q, sys.argv[1])
